apache/celeborn

.github/workflows/maven.yml

correct ci branch name.

---

client/src/main/java/com/aliyun/emr/rss/client/write/LifecycleManager.scala

Reserve slots retry, avoid allocating both master and slave peer
If allocate duplicate PartitionLocations will cause client read hang
N/A
#19 
N/A
current ut
/cc @waitinfuture @FMX 
/assign @wangshengjie123

[BUG] Fix reserve slots with retry allocate duplicate PartitionLocations

---

client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java

[BUG] fix compile error with spark3.2.0

---

README.md
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleManager.scala
pom.xml

[FEATURE] Support Spark3.0

---

CONFIGURATION_GUIDE.md
client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
common/src/main/java/com/aliyun/emr/rss/common/network/TransportContext.java
common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportClientFactory.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/GlobalChannelLimiter.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/MemoryTracker.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/TransportRequestHandler.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/TransportServer.java
common/src/main/java/com/aliyun/emr/rss/common/network/util/ByteUnit.java
common/src/main/java/com/aliyun/emr/rss/common/protocol/PartitionLocation.java
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
server-worker/pom.xml
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/FileWriterSuiteJ.java
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/MiniClusterFeature.scala

[FEATURE]Worker-Wise Current-Limiting

---

server-worker/pom.xml
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

fix import order.

---

CONFIGURATION_GUIDE.md
README.md
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/test/java/com/aliyun/emr/rss/common/haclient/RssHARetryClientSuiteJ.java
common/src/test/scala/com/aliyun/emr/rss/common/RssConfSuite.scala
common/src/test/scala/com/aliyun/emr/rss/common/util/UtilsSuite.scala

Shall we allow host/port config from properties file to cover the system environment variables?
#26 
N/A
UT
/cc @FMX @waitinfuture 
/assign @FMX

[Feature] Split ha and non-ha config and update doc

---

README.md
client-spark/shuffle-manager-2/pom.xml
client-spark/shuffle-manager-3/pom.xml
client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/java/com/aliyun/emr/rss/client/write/LifecycleManager.scala
client/src/test/java/com/aliyun/emr/rss/client/ShuffleClientSuiteJ.java
common/pom.xml
common/src/main/java/com/aliyun/emr/rss/common/network/protocol/TransportMessage.java
common/src/main/java/com/aliyun/emr/rss/common/protocol/PartitionLocation.java
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/RpcEndpointVerifier.scala
common/src/main/scala/com/aliyun/emr/rss/common/serializer/JavaSerializer.scala
common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala
pom.xml
server-common/pom.xml
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

Multi Client Support

---

README.md

Add instructions for JDK.

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HARaftServer.java

Fix some rpc error
Without fix,  worker cannot send heartbeat to master
none
#55 
none
cluster test
/cc @FMX @TonyDoen 
/assign @wangshengjie123

[BUG] Fix Rpc error: worker cannot send heartbeat to master

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala

Fix incorrect collection type.
/cc @waitinfuture 
/assign @wangshengjie123

[BUG]fix error: incorrect collection type.

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala

/cc @wangshengjie123 
/assign @waitinfuture

[bug]fix a npe error.

---

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

Fix bug https://github.com/alibaba/RemoteShuffleService/issues/63

Fix Issue 63

---

common/src/main/java/com/aliyun/emr/rss/common/network/server/TransportServer.java

minor fix for useless tcp_nodelay flag

---

CONFIGURATION_GUIDE.md
README.md
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/test/java/com/aliyun/emr/rss/common/haclient/RssHARetryClientSuiteJ.java
conf/rss-defaults.conf.template
server-master/src/test/scala/com/aliyun/emr/rss/service/deploy/master/MasterSuite.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/MiniClusterFeature.scala

Refactor the configuration

---

assets/spark-patch/RSS_RDA_spark2.patch
pom.xml

/cc @wangshengjie123 
/assign @waitinfuture

[Feature]Update spark2 patch

---

README.md

[Bug] update README.md for single master cluster.

---

common/src/main/java/com/aliyun/emr/rss/common/network/server/MemoryTracker.java

[bug]fix parameter position error.

---

client-spark/shuffle-manager-2/pom.xml
client-spark/shuffle-manager-3/pom.xml

shade guava and netty packages.

[Feature] shade package.

---

pom.xml

[FEATURE] deactivate all profiles by default.

---

client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java

[ISSUE-110] ShuffleWriteTime should include pushMergeData

---

README.md
assets/spark-patch/RSS_RDA_spark3.patch

RSS support spark3 RDA.

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/java/com/aliyun/emr/rss/client/write/PushState.java
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

1.Fix a null pointer exception.
2.Add partitionlocation to inflight batches to help resolve problems.
3.Reduce driver logs.

[BUG]Fix a null pointer exception.

---

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-120] [BUG] Master‘s metrics of WorkerSlotsCount / WorkerSlotsUsed/ OverloadWorkerCount not update

---

common/pom.xml
common/src/main/scala/com/aliyun/emr/rss/common/serializer/JavaSerializer.scala
common/src/main/scala/com/aliyun/emr/rss/common/serializer/Serializer.scala

[FEATURE] Remove dependency on spark-tags from common module (#126)

---

CONFIGURATION_GUIDE.md
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/java/com/aliyun/emr/rss/common/protocol/PartitionLocation.java
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[issue-146] Add storage hint to indicate storage location.

---

CONFIGURATION_GUIDE.md
common/src/main/java/com/aliyun/emr/rss/common/haclient/RssHARetryClient.java
common/src/main/scala/com/aliyun/emr/rss/common/util/RpcUtils.scala

[BUG]Fix worker lost in HA mode when leader lost.

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java

ISSUE-152. Show target host:port when push data callback onFailure

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

[ISSUE-160] [BUG] requestReserveSlot failed loss root cause

---

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-176][BUG] Handle RegisterWorker use wrong worker info when trigger lost event

---

common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala

[ISSUE-178][BUG] RSS should not limit the io. numConnectionsPerPeer to 1, stability is not good enough

---

CONFIGURATION_GUIDE.md
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala

[ISSUE-180][FEATURE] Disable rss.worker.closeIdleConnections by default

---

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/FileWriterSuiteJ.java
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitorSuite.scala

[Feature] Multithread disk flusher

---

README.md
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

Add instructions about restart cluster in HA mode.

---

common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-190][BUG] After WorkerLost, response to worker heartbeat RPC to, then worker can clean the data.

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-208] Refine log levels

---

server-worker/pom.xml
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-217][FEATURE] Re-register worker after worker lost

---

README.md

[ISSUE-229][README] Fix README.md use fixed port 9097 for spark configuration example 

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/Outbox.scala

[ISSUE-228][BUG] When CommitFile, worker endpoint may be closed by ReserveSlots failed, we should try reconnect endpoint when endpoint not active

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/Outbox.scala

[ISSUE-228]Fix unexpected closed exceptions occurred while committing files

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-222][BUG] RequestSlotResponse/RegisterShuffleResponse should handle null issue

---

common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportClient.java
common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportResponseHandler.java
common/src/main/java/com/aliyun/emr/rss/common/network/protocol/ChunkFetchFailure.java
common/src/main/java/com/aliyun/emr/rss/common/network/protocol/ChunkFetchRequest.java
common/src/main/java/com/aliyun/emr/rss/common/network/protocol/ChunkFetchSuccess.java
common/src/main/java/com/aliyun/emr/rss/common/network/protocol/StreamChunkSlice.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/FileManagedBuffers.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/OneForOneStreamManager.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/StreamManager.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/TransportRequestHandler.java
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyStreamManager.scala
common/src/test/java/com/aliyun/emr/rss/common/network/ChunkFetchIntegrationSuiteJ.java
common/src/test/java/com/aliyun/emr/rss/common/network/RequestTimeoutIntegrationSuiteJ.java
common/src/test/java/com/aliyun/emr/rss/common/network/TransportRequestHandlerSuiteJ.java
common/src/test/java/com/aliyun/emr/rss/common/network/TransportResponseHandlerSuiteJ.java
common/src/test/java/com/aliyun/emr/rss/common/network/server/OneForOneStreamManagerSuiteJ.java
pom.xml
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/ChunkFetchRpcHandler.java

[ISSUE-216] Support sized chunk fetch request

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala

[ISSUE-222][BUG] GetBlacklist/GetBlacklistResponse should replace null value with empty list

---

pom.xml

[ISSUE-240] Revert pom modification about profiles

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-222] CommitFiles and CommitFilesResponse should remove null check

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/java/com/aliyun/emr/rss/common/protocol/message/StatusCode.java
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala

[ISSUE-222][BUG] GetReduceFileGroups should remove code about return null value

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-222] Destroy and DestroyResponse  should remove null check

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala

[ISSUE-222][FOLLOWUP] GetBlacklist/GetBlacklistResponse should replace null value with empty list 

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java

[ISSUE-249] Fix OutOfBounds when shuffle has no data(q24b)

---

common/src/main/java/com/aliyun/emr/rss/common/protocol/TransportModuleConstants.java

[ISSUE-231][FOLLOWUP] Remove unused FILE_MODULE

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
common/src/main/java/com/aliyun/emr/rss/common/network/TransportContext.java
common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportClientFactory.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/TransportServer.java
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-262] Remove unused bootstrap

---

common/src/main/java/com/aliyun/emr/rss/common/network/util/TransportFrameDecoder.java
common/src/test/java/com/aliyun/emr/rss/common/network/util/TransportFrameDecoderSuiteJ.java

[ISSUE-269] Remove unused inceptor in TransportFrameDecoder

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala

[BUG] multi-thread flusher causes data inconsistent with chunk offsets

---

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client-spark/shuffle-manager-3/pom.xml
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/SendBufferPool.java
client/pom.xml
common/pom.xml
pom.xml
server-common/pom.xml
server-master/pom.xml
server-worker/pom.xml

[REFACTOR] Refactor pom import issue

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala

[BUG] Fix reserve slots failed due to take buffer stuck

---

client-spark/shuffle-manager-2/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-2/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java
client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java

```
at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.write0(SortBasedShuffleWriter.java:215)
at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.write(SortBasedShuffleWriter.java:160)
at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
at org.apache.spark.scheduler.Task.run(Task.scala:131)
at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1465)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
at …
```

[ISSUE-289][BUG] Write data should use default object class to avoid NPE

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala

[BUG] DiskFlusher nextWorkerIndex update incorrectly.

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

[ISSUE-293][REFACTOR] Init worker rpc endpoint and reserve slot in parallel to speed up register shuffle process

---

README.md
common/pom.xml
pom.xml
server-master/pom.xml

Bump Ratis 2.3.0 and related toolchains
To bring native Apple Sillicon support.
Successful build on M1 chips using `./dev/make-distribution.sh -Pspark-3 -Plog4j-1`

Bump Ratis 2.3.0 and related toolchains

---

client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/ShuffleInMemorySorter.java

Refer to https://github.com/apache/spark/pull/26349
https://github.com/alibaba/RemoteShuffleService/issues/297

[ISSUE-297] NPE in TaskCompletionListener due to Spark OOM in ShuffleInMemorySorter causing tasks to hang

---

CONFIGURATION_GUIDE.md
README.md

Fix the wrong configuration doc of `rss.ha.port` and provide example in readme. 
Provide correct doc and guide user how to customize HA port.
#308 
unit test

[ISSUE-308][DOC] Fix the wrong configuration doc of rss.ha.port and provide example in readme.

---

docker/DEPLOY_ON_K8S.md
docker/Dockerfile

To close #315 
User may need this arg to build their own images with specific version.
#315 
Local

[Feature] Dockerfile add ARG rss_version

---

common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportResponseHandler.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/FetchHandler.scala

[ISSUE-325] Log error msg for ChunkFetchFailure

---

common/src/main/java/com/aliyun/emr/rss/common/network/protocol/ChunkFetchSuccess.java
common/src/main/java/com/aliyun/emr/rss/common/network/util/TransportFrameDecoder.java

[ISSUE-288] fix netty memory leak in chunk fetch

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

https://github.com/alibaba/RemoteShuffleService/issues/327

[ISSUE-327][REFACTOR] Remove unused logAvailableFlushBuffersTask

---

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at com.aliyun.emr.rss.service.deploy.master.clustermeta.AbstractMetaManager.updateReleaseSlotsMeta(AbstractMetaManager.java:104)
at com.aliyun.emr.rss.service.deploy.master.clustermeta.SingleMasterMetaManager.handleReleaseSlots(SingleMasterMetaManager.java:53)
at com.aliyun.emr.rss.service.deploy.master.Master.handleReleaseSlots(Master.scala:456)
at com.aliyun.emr.rss.service.deploy.master.Master$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$12(Master.scala:189)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at com.aliyun.emr.rss.service.deploy.master.Master.executeWithLeaderChecker(Master.scala:156)
at …
```

[ISSUE-273][FOLLOW-UP] Fix IndexOutOfBoundsException when release slots

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceInfo.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala

[ISSUE-273][FOLLOW-UP] Fix device stat file not found exception

---

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-273][FOLLOW-UP] Remove duplicate handleWorkerHeartBeat

---

common/src/main/scala/com/aliyun/emr/rss/common/meta/DeviceInfo.scala
common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitorSuite.scala

[ISSUE-273][FOLLOW-UP] Merge MountInfo with DiskInfo

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

[ISSUE-357][REFACTOR] Remove unused handleStageEnd

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/doc_report.md

Add DOC template

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/FileWriterSuiteJ.java
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitorSuite.scala

[Feature] choose usable disk while reserving slots.

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Controller.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

As designed, worker should reject new ReserveSlots request when shutting down
https://github.com/alibaba/RemoteShuffleService/issues/364

[ISSUE-364][FEATURE] Worker should reject ReserveSlots request when shutting down

---

.github/workflows/maven.yml
README.md
dev/check-spark-2.3.sh
dev/check-spark-3.2.sh
dev/check-spark-3.3.sh
pom.xml

Add maven profile for Spark 3.1/3.2/3.3
Enable CI for Spark 3.1/3.2/3.3

Add profile for Spark 3.2/3.3

---

docker/helm/Chart.yaml

Improve Chart.yaml to better indicate Chart content.

Improve Helm Chart.yaml modify description

---

common/src/main/java/com/aliyun/emr/rss/common/network/server/ChannelsLimiter.java

closes #375 
/cc @waitinfuture @AngersZhuuuu

[BUG] After trigger pausePushData, new added channel still can push data

---

common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/IMetadataHandler.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/SingleMasterMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/MetaHandler.java
server-master/src/main/proto/Resource.proto
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

[ISSUE-367][FEATURE] Master support worker re-register with same port and worker miss heartbeat only delete expired data

---

common/src/main/java/com/aliyun/emr/rss/common/network/server/ChannelsLimiter.java

[Doc]Add a comment about channel limiter synchronization.

---

client/src/main/java/com/aliyun/emr/rss/client/read/RetryingChunkClient.java

[ISSUE-385][Feature] RetryingChunkClient  openChunk don't wait for first request to each replicate

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala

[ISSUE-399] Duplicate code in notifyHealthy

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitorSuite.scala

[ISSUE-401] Remove DeviceObserver.reportError()

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala

[ISSUE-403][FOLLOW-UP] Minor fix

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala

#413 minor fix disk totalSpace not right

---

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/MasterArguments.scala
server-master/src/test/scala/com/aliyun/emr/rss/service/deploy/master/MasterSuite.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerArguments.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/MiniClusterFeature.scala

[ISSUE-418][BUG] Start master/worker should respect rpc port setting

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/meta/DeviceInfo.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Controller.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala

[ISSUE-434] Refine log

---

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/AbstractSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/NetWorkSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/MasterSource.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerSource.scala

Replace all essConf with rssConf

---

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-441] Refactor cluster load check to cluster alive check

---

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java

HAMasterMetaManager should log exception stacktrace

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala

[Feature]hdfs writer respects working dir configuration.

---

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/MasterUtil.java

When compare TPC-DS 3T between main branch and branch-0.1, we found that round-robin is slower than branch-0.1, which is unexpected because the high-level allocation algorithm are basically the same.
```
main roundrobin:   5332s
branch-0.1:        5027s
```
After digging deeper I found that's because branch-0.1 first allocates master locations round-robin, then slave locations round-robin, however in main branch it allocates (master, slave) pairs round-robin. As a result, say one worker has two disks disk1 and disk2, we find all master partitions are allocated on disk1 and all slave partitions are allocated on disk2, which is different from branch-0.1 which disk1 and disk2 have the same number of both master partitions and slave partitions.
Experiments show that when change main branch …

[ISSUE-450] Fix performance regression

---

docker/DEPLOY_ON_K8S.md
docker/helm/templates/master-service.yaml
docker/helm/templates/worker-service.yaml

On Kubernetes case, worker should have headless service.
To close #454 

[Feature] Add worker service for k8s case 

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java

If during shutdown worker, FileSorter task is interrupted and remain partial sorted file under path, after restart worker, same FileSorter task may write corrupted sortedFile.
We should make sure when starting sorted file, no partial file remain.
https://github.com/alibaba/RemoteShuffleService/issues/457

[ISSUE-457][BUG] After worker recover, we should make sure there is no partial sortedFile and indexFile when new FileSorter task started

---

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/MasterUtil.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/SlotsAllocator.java
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/SlotsAllocatorSuiteJ.java

[ISSUE-453] [REFACTOR] Refine code in MasterUtils

---

server-worker/pom.xml

[ISSUE-332][FOLLOWUP] Add deps in worker's pom

---

sbin/restart-worker.sh
sbin/rss-daemon.sh
sbin/start-all.sh
sbin/stop-all.sh
sbin/stop-worker.sh

[ISSUE-388][SHELL] Add restart script for worker's quick recover

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/Flusher.scala

```
22/08/18 18:05:34,498 ERROR [worker-disk-checker] DiskFlusher: DiskFlusher@1558830771-/mnt/ssd/0/rss-worker/shuffle_data is notified Device sda Error ReadOrWriteFailure! Stop Flusher.
22/08/18 18:05:34,498 ERROR [DiskFlusher@1558830771-/mnt/ssd/0/rss-worker/shuffle_data-1] DiskFlusher: com.aliyun.emr.rss.service.deploy.worker.DiskFlusher$$anon$2@58d7b86a thread terminated.
java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at …
```

[ISSUE-411][BUG] Device Error should return buffer too

---

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/MetaHandler.java
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java

[BUG] update partition size failed in HA mode

---

.gitignore
client-spark/shuffle-manager-common/pom.xml
dev/make-distribution.sh
pom.xml
server-master/pom.xml
server-worker/pom.xml

Flatten Jars for master and worker instead of a single shaded jar.

[BUILD] Flatten Jars for Master and Worker

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Compressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Decompressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Trait.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdTrait.java
client/src/main/java/com/aliyun/emr/rss/client/read/Replica.java
client/src/main/java/com/aliyun/emr/rss/client/read/RetryingChunkClient.java
client/src/main/java/com/aliyun/emr/rss/client/read/RssInputStream.java
client/src/main/java/com/aliyun/emr/rss/client/write/PushState.java
client/src/main/java/com/aliyun/emr/rss/client/write/PushTask.java

[REFACTOR] Some minor changes in client module

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java

[ISSUE-493][BUG] Should sync update sortingFiles and sortedFiles

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/FlushTask.scala

Fix the problem of write loss when the buffer is too large

---

client/src/main/java/com/aliyun/emr/rss/client/read/Replica.java
client/src/main/java/com/aliyun/emr/rss/client/read/RetryingChunkClient.java

Add log for retrying.
Currently, there is no log for first-time retry.

Improve logging for RetryingChunkClient

---

pom.xml
server-master/pom.xml
server-worker/pom.xml

Remove unused git maven plugin
I don't see anywhere using this plugin, remove it to speed up building.

Remove unused git maven plugin

---

CONFIGURATION_GUIDE.md
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
server-common/src/main/scala/com/aliyun/emr/rss/server/common/http/HttpServer.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-master/src/test/scala/com/aliyun/emr/rss/service/deploy/master/MasterSuite.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/MiniClusterFeature.scala

HTTP server netty thread should has prefix and allow to bind host

---

common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorterSuiteJ.java

Skip leveldb test on Apple Silicon.
LevelDB does not support Apple Silicon.

Skip leveldb test on Apple Silicon

---

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala

https://github.com/alibaba/RemoteShuffleService/issues/511

[ISSUE-511][DOC] Keep rss.ha.ratis.snapshot.auto.trigger.enabled 's default value same in code and doc

---

client-spark/shuffle-manager-2/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-2/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java
client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java
client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java
client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/OpenByteArrayOutputStream.java
client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/SendBufferPool.java
client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/java/com/aliyun/emr/rss/client/write/DataPusher.java
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/SlotsAllocator.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

It's a minor refactor PR, that extracts duplicated code and fixes typos
When I am reading the code, found and fixed those minor issues.

Extract OpenByteArrayOutputStream

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/OneForOneStreamManager.java
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/FetchHandler.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/PushDataHandler.scala

`streamManager.connectionTerminated` should be called when `channelInactive`
To avoid resource leak

[WORKER] Cleanup StreamState when channel inactive

---

assets/spark-patch/RSS_Columnar_Shuffle_spark3.patch

[ISSUE-517] Spark3 patch to support columnar shuffle

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/FetchHandler.scala

[WORKER] Fast fail when rss.shuffle.maxChunksBeingTransferred exceeded

---

common/src/main/scala/com/aliyun/emr/rss/common/metrics/MetricsConfig.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/MetricsSystem.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/JVMCPUSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/JVMSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/RPCSource.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerSource.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/storage/FileWriterSuiteJ.java

```
-  val ROLE_WOKRER = "Worker"
+ val ROLE_WORKER = "Worker"
```
https://github.com/alibaba/RemoteShuffleService/issues/531

[ISSUE-531][REFACTOR] Fix wrong MetricsSystem.WORKER_ROLE

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

```
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 INFO LifecycleManager: [handleGetReducerFileGroup] Wait for handleStageEnd complete cost 0ms
22/09/05 15:58:51 …
```

[ISSUE-534][REFACTOR] Refactor log when call `handleGetReducerFileGroup`

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

https://github.com/alibaba/RemoteShuffleService/issues/543

[ISSUE-543][FEATURE] Worker should enable HttpServer even not enable metric system

---

client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/SparkUtils.java

[ISSUE-518] Get schema from shuffle dependency

---

docker/helm/templates/configmap.yaml
docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml

Now, rss-svc rename to rss-master-svc, should change related.

[BUG] Fix start up and defaults config map using `rss-svc`

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorterSuiteJ.java

[ISSUE-496][BUG]Ensure all file channels write whole buffer.

---

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/PartitionFilesSorter.java
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/PartitionFilesSorterSuiteJ.java

[ISSUE-496][BUG]Ensure all file channels write whole buffer. (#561)

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

[ISSUE-567] Optimize LifecycleManager.getLatestPartition

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/MiniClusterFeature.scala

https://github.com/alibaba/RemoteShuffleService/issues/568

[ISSUE-568][BUG] MiniClusterFeature.createWorker should use correct RpcEnv

---

server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorterSuiteJ.java

[BUG]fix ci failure.

---

METRICS.md
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerSource.scala
server-worker/src/test/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorterSuiteJ.java

https://github.com/alibaba/RemoteShuffleService/issues/580

[ISSUE-580] Add sorted file related metrics to collect PartitionSorter status

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala
client/src/main/java/com/aliyun/emr/rss/client/read/RssInputStream.java
common/src/main/java/com/aliyun/emr/rss/common/network/client/TransportResponseHandler.java

[ISSUE-588][BUG] Fix memory leak in shuffle read

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnBuilder.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnStats.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnType.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressibleColumnBuilder.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressionScheme.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressionSchemes.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssNullableColumnBuilder.scala

[ISSUE-519] Support row to columnar for shuffle writer

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

[IMPROVEMENT] Improve revive or partition split log readability.

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala

improve revive log readability. (#603)

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClient.java
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/storage/DeviceMonitorSuite.scala

Translate found Chinese character to English 
All matches found by the script
#600 

[ISSUE-600][Refactor] Translate Chinese comments to English

---

common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala

Change env JSS_LOCAL_IP to RSS_LOCAL_IP
I guess JSS_LOCAL_IP is a typo, we should keep consistent w/ other env vars like RSS_LOCAL_HOSTNAME

Correct environment variable RSS_LOCAL_IP

---

client-spark/shuffle-manager-3/src/main/java/org/apache/spark/sql/execution/columnar/RssColumnDictionary.java
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressionSchemes.scala

[ISSUE-523] Support encoding for shuffle writer

---

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java

[ISSUE-625][BUG] Incorrect result when kill worker while pushMergedData

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnAccessor.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressibleColumnAccessor.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssNullableColumnAccessor.scala

[ISSUE-521] Support columnar to row for shuffle reader

---

common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/proto/Resource.proto

https://github.com/alibaba/RemoteShuffleService/issues/631

[ISSUE-631][FEATURE] Add UserIdentifier proto class

---

client/src/main/java/com/aliyun/emr/rss/client/read/RetryingChunkClient.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/PushDataHandler.scala

Fix worker replied ack at the wrong time when a soft split is triggered.

---

common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/proto/Resource.proto

https://github.com/alibaba/RemoteShuffleService/issues/634

[ISSUE-634][FEATURE] Add ResourceConsumption class to indicate resource usage

---

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleManager.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/cluster/ClusterReadWriteTest.scala

Minor refine

---

CONFIGURATION_GUIDE.md
client/pom.xml
client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
client/src/main/java/com/aliyun/emr/rss/client/compress/Compressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/Decompressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Compressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Decompressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Trait.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdCompressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdDecompressor.java
client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdTrait.java
client/src/main/java/com/aliyun/emr/rss/client/read/RssInputStream.java
client/src/test/java/com/aliyun/emr/rss/client/ShuffleClientSuiteJ.java
client/src/test/java/com/aliyun/emr/rss/client/compress/CodecSuite.java
common/pom.xml
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/test/scala/com/aliyun/emr/rss/common/RssConfSuite.scala
pom.xml
server-master/pom.xml
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/cluster/ClusterReadWriteTest.scala
server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/integration/SkewJoinTest.scala

Branch 0.1

---

common/src/main/java/com/aliyun/emr/rss/common/util/PbSerDeUtils.java
common/src/main/proto/TransportMessages.proto
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/LevelDBProvider.java
server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/StorageManager.scala

Refactor protobuf related name format
keep protobuf related name consistent
#640 

[ISSUE-640][Refactor] Refactor Protobuf related name format

---

docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml
docker/helm/values.yaml

In some cases, we need to set the resources of the Master and Worker separately, so we provide templates for setting them separately

[IMPROVE] Split resource into master resource and worker resource

---

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/RPCSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

https://github.com/alibaba/RemoteShuffleService/issues/637

[ISSUE-637][FEATURE] Change CheckAlive to CheckAvailable and reply checkQuota result

---

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala

[BUG]Fix flusher default-thread-count-setting is not effective

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchSerializer.scala

[ISSUE-664] [FEATURE] Add serializer for shuffle read and write

---

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala

[ISSUE-668] [FEATURE] Add columnar shuffle configuration for RSS

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/serializer/JavaSerializer.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

Drop control message Scala wrapper - CheckForWorkerTimeOut

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

Drop control message Scala wrapper - CheckForApplicationTimeOut

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala

Drop control message Scala wrapper - RemoveExpiredShuffle

---

common/src/main/java/com/aliyun/emr/rss/common/haclient/RssHARetryClient.java
common/src/main/java/com/aliyun/emr/rss/common/util/PbSerDeUtils.java
common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/RPCSource.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

Drop control message Scala wrapper - RegisterWorker/RegisterWorkerResponse

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala

[ISSUE-522] Support columnar shuffle for RSS shuffle reader

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala

Fix main branch UT failure.

---

common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/AbstractSource.scala

[BUG]Fix query metrics caused NPE when there are no chunk fetch data.

---

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
common/src/main/scala/com/aliyun/emr/rss/common/internal/config/ConfigBuilder.scala
common/src/main/scala/com/aliyun/emr/rss/common/internal/config/ConfigEntry.scala
common/src/main/scala/com/aliyun/emr/rss/common/internal/config/ConfigProvider.scala
common/src/main/scala/com/aliyun/emr/rss/common/internal/config/ConfigReader.scala
common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala

Ref Apache Spark to implement the structured configuration system

Initial implement structured configuration system

---

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Controller.scala

Add UserIdentifier in ReserveSlots and RequestSlots RPC
To collect user info by RPC
#632 

[ISSUE-632][FEATURE] LifecycleManager side ReserveSlots & RequestSlots RPC with UserIdentifier

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/StorageManager.scala

Code format: remove useless `case`

Remove useless case in StorageManager

---

common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/test/scala/com/aliyun/emr/rss/common/identity/UserIdentifierSuite.scala

[ISSUE-631][FOLLOWUP] UserIdentifier support to/from string

---

common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/AbstractSource.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/FetchHandler.scala
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerSource.scala

remove chunkfetchsize metric.

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala

Get total size code refactoring when writing row to columnar

---

client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/HashBasedShuffleWriter.java

[FEATURE] Support columnar shuffle for RSS shuffle writer

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchSerializer.scala

[ISSUE-526][FEATURE]Support code generation in the process of columnar to row

---

common/src/main/java/com/aliyun/emr/rss/common/util/PbSerDeUtils.java
common/src/main/proto/TransportMessages.proto
common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala
common/src/test/scala/com/aliyun/emr/rss/common/identity/UserIdentifierSuite.scala
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/IMetadataHandler.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/MetaUtil.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/SingleMasterMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/MetaHandler.java
server-master/src/main/proto/Resource.proto
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java
server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java
server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala

Send user usage in RPC RegisterWorker & HeartbeatFromWorker to Master  and Master update usage
Collect user resource usage from worker to master
#636 

[ISSUE-636][FEATURE] worker sent user usage to master through register worker/heartbeat from worker and master update usage

---

README.md

[DOC] Update the calculation method of the worker's slot count

---

client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleFallbackPolicyRunner.scala
common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala
common/src/main/scala/com/aliyun/emr/rss/common/quota/Quota.scala
server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala

[ISSUE-704][FEATURE] Master check quota when LifecycleManager request CheckQuota

---

client-spark/shuffle-manager-2/src/test/scala/org/apache/spark/shuffle/celeborn/RssShuffleManagerSuite.scala
client-spark/shuffle-manager-3/src/test/scala/org/apache/spark/shuffle/celeborn/RssShuffleManagerSuite.scala

Replace foreach(println) to count() to shrink UT output

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/write/LifecycleManager.scala
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala

Drop control message Scala wrapper - RegisterShuffle/RegisterShuffleResponse

---

pom.xml

[BUILD] `mvn clean` shoud remove Spark generated temporary files

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/write/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/metrics/source/RPCSource.scala
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

Drop control message Scala wrapper - UnregisterShuffle/UnregisterShuffleResponse

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/ShuffleClientHelper.scala
client/src/main/scala/org/apache/celeborn/client/write/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala

Drop control message Scala wrapper - Revive/PartitionSplit/ChangeLocationResponse

---

pom.xml

Housekeeping, upgrade the building tools to the latest version.

[BUILD] Bump scala-maven-plugin from 3.3.2 to 4.7.2

---

common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
server-master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

Drop control message Scala wrapper - WorkerLost/WorkerLostResponse

---

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-2/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteSuite.scala

[REFACTOR]move lifecycle manager to correct package.

---

client/src/main/scala/org/apache/celeborn/client/write/LifecycleManager.scala

[BUG] Fix a npe that stuck lifecycle manager when a worker is offline.

---

docker/helm/Chart.yaml
docker/helm/templates/NOTES.txt
docker/helm/templates/_helpers.tpl
docker/helm/templates/configmap.yaml
docker/helm/templates/master-service.yaml
docker/helm/templates/master-statefulset.yaml
docker/helm/templates/prometheus-podmonitor.yaml
docker/helm/templates/worker-service.yaml
docker/helm/templates/worker-statefulset.yaml
docker/helm/values.yaml

[Celeborn #729] Rename helm template and values

---

client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client/src/main/scala/org/apache/celeborn/client/write/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/quota/DefaultQuotaManager.scala
common/src/main/scala/org/apache/celeborn/common/quota/Quota.scala
common/src/main/scala/org/apache/celeborn/common/quota/QuotaManager.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

[ISSUE-630][REFACTOR] Minor change of storage resource quota, include code style, comment unused code etc..

---

client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleReader.scala

[ISSUE-588][FOLLOWUP] Keep same code as spark2

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

https://github.com/alibaba/celeborn/issues/739

[ISSUE-739][REFACTOR] Use object wrap pb message method

---

common/src/main/scala/org/apache/celeborn/common/RssConf.scala

[BUG] In a certain scenario, the worker will still use HA when HA is turned off

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala

[BUG] Scala match exception in columnar shuffle writer

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressionScheme.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressionSchemes.scala

[FEATURE] Support dictionary decoding for columnar shuffle reader

---

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
common/src/test/scala/org/apache/celeborn/RssFunSuite.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/MasterArguments.scala
master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java

Celeborn should respect CELEBORN_* env vars

---

client-spark/common/pom.xml
client-spark/spark-2/pom.xml
client-spark/spark-3/pom.xml

[BUILD] Unify name style for module celeborn-client-spark-common

---

.github/workflows/license.yml
.github/workflows/maven.yml
.github/workflows/style.yml
pom.xml

Use Google mirror in GA

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssBatchBuilder.scala

[FEATURE] Add common parent class for columnar shuffle writer codegen

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

Meet a case that Celeborn only shoe below logs when shuffle data lost, it's not convenient to help debug
```
22/10/14 03:14:24 INFO LifecycleManager: Last MapperEnd, call StageEnd with shuffleKey:application_1665646136650_68159_1-1.
22/10/14 03:14:32 ERROR LifecycleManager: For 1 partition 928-8: data lost.
``` 
https://github.com/alibaba/celeborn/issues/768

[ISSUE-768][REFACTOR] Shuffle data lost should show more clear about lost data in which worker

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[ISSUE-770][Refactor] Batch handle change partition should ignore empty batch and avoid print log of empty result

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

[BUG]Fix rss worker register failure problem.

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnBuilder.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssNullableColumnBuilder.scala

[FEATURE] Add new ColumnBuilder types to support columnar shuffle codegen

---

client-spark/spark-2/pom.xml
client-spark/spark-3/pom.xml

Shade commons-lang3 pacakge to avoid conflicts.

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/java/org/apache/celeborn/client/read/DfsPartitionReader.java
client/src/main/java/org/apache/celeborn/client/read/RetryingChunkClient.java
client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java
client/src/main/java/org/apache/celeborn/client/write/DataPusher.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/RssConf.scala
common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala
docker/helm/values.yaml
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Continue work on configuration migration, this PR also addressed the comments left in #775.

Migrate a bunch of configurations

---

common/src/main/scala/org/apache/celeborn/common/RssConf.scala

[DOC] Refine doc for config celeborn.worker.storage.dirs

---

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[Feature]Only keep one copy of roaringbitmap to reduce memory usage.

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

https://github.com/alibaba/celeborn/issues/795

[ISSUE-795][BUG] Batch handle change partition throw NPE

---

pom.xml

https://github.com/trustin/os-maven-plugin/releases

Bump os-maven-plugin 1.7.0

---

pom.xml

Bump SLF4J 1.7.36

---

pom.xml

Bump maven-shade-plugin 3.4.0

---

pom.xml

Bump maven-surefire-plugin 3.0.0-M7

---

common/src/main/java/org/apache/celeborn/common/network/protocol/PushData.java

[ISSUE-555][REFACTOR] Delete epoch from PushData

---

client-spark/common/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedPusher.java
client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java
client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java
client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/java/org/apache/celeborn/client/compress/Compressor.java
client/src/main/java/org/apache/celeborn/client/read/DfsPartitionReader.java
client/src/main/java/org/apache/celeborn/client/read/RetryingChunkClient.java
client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java
client/src/main/java/org/apache/celeborn/client/write/DataPusher.java
client/src/main/java/org/apache/celeborn/client/write/PushState.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/test/java/org/apache/celeborn/client/compress/CodecSuite.java
common/src/main/java/org/apache/celeborn/common/haclient/RssHARetryClient.java
common/src/main/scala/org/apache/celeborn/common/RssConf.scala
common/src/main/scala/org/apache/celeborn/common/metrics/source/AbstractSource.scala
common/src/test/scala/org/apache/celeborn/common/RssConfSuite.scala
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/MasterArguments.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterClusterInfo.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/Service.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

close https://github.com/alibaba/celeborn/issues/818

[ISSUE-818][REFACTOR] Move existing RssConf.xxx conf method to RssConf class

---

.github/workflows/check_stale_prs.yml

[FEATURE]Add action to process stale pull requests.

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
common/src/main/java/org/apache/celeborn/common/protocol/message/StatusCode.java
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

[ISSUE-829][REFACTOR] Unify name of PUSH_DATA_FAIL_MAIN

---

common/src/main/scala/org/apache/celeborn/common/RssConf.scala
docs/configuration/worker.md
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

[FOLLOWUP][ISSUE-813]Update doc and fix typo.

---

.github/workflows/benchmark.yml
.github/workflows/regression.yml

[BUG]Fix incorrect action command type configs.

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

```
2022-10-24 04:27:20 [ERROR] [worker-forward-message-scheduler] org.apache.celeborn.common.util.Utils#80 - Uncaught exception in thread worker-forward-message-scheduler
java.lang.UnsupportedOperationException: null
at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_345]
at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[?:1.8.0_345]
at org.apache.celeborn.common.meta.WorkerInfo.updateThenGetUserResourceConsumption(WorkerInfo.scala:226) ~[celeborn-common_2.12-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
at org.apache.celeborn.service.deploy.worker.Worker.org$apache$celeborn$service$deploy$worker$Worker$$heartBeatToMaster(Worker.scala:234) ~[celeborn-worker_2.12-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
at org.apache.celeborn.service.deploy.worker.Worker$$anon$1.$anonfun$run$1(Worker.scala: …
```

[BUG] Fix worker lost caused by UnsupportedOperationException

---

client-spark/common/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedPusher.java
client-spark/spark-2/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docker/helm/values.yaml
docs/configuration/client.md

[ISSUE-841][REFACTOR] Migrate shuffle client side conf to Celeborn Configuration System

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md

Change slot to slots for consistency

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssBatchBuilder.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchCodeGenBuild.scala

[FEATURE] Add new ColumnarBatchBuild for columnar shuffle codegen

---

client/src/main/java/org/apache/celeborn/client/compress/Compressor.java
client/src/main/java/org/apache/celeborn/client/compress/Decompressor.java
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/test/scala/org/apache/celeborn/common/CelebornConfSuite.scala
docs/configuration/client.md
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala

[ISSUE-847][REFACTOR] Migrate codec conf to Celeborn Configuration System

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md
toolkit/scripts/genConfs.py

[ISSUE-845][REFACTOR] Migrate partition split related conf to Celeborn Configuration System

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md

[Refactor] Refine rpc cache configs

---

.github/workflows/benchmark.yml
.github/workflows/benchmark_manual.yml
.github/workflows/regression.yml
.github/workflows/regression_manual.yml
.gitignore
README.md
dev/make-distribution.sh
docker/DEPLOY_ON_K8S.md
docker/Dockerfile
docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml
toolkit/reg.sh

The apache release requires the source/binary tarball name contains "apache"

[BUILD] Add apache- prefix in release tarball name

---

DISCLAIMER

It's required for Apache Podling release

[INFRA] Add DISCLAIMER

---

NOTICE

It's required for Apache Podling release

[INFRA] Add NOTICE

---

client-spark/spark-2/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/identity/IdentityProvider.scala
common/src/main/scala/org/apache/celeborn/common/quota/DefaultQuotaManager.scala
common/src/main/scala/org/apache/celeborn/common/quota/QuotaManager.scala
common/src/test/scala/org/apache/celeborn/ConfigurationSuite.scala
common/src/test/scala/org/apache/celeborn/common/quota/DefaultQuotaManagerSuite.scala
docs/configuration/index.md
docs/configuration/quota.md

[ISSUE-851][REFACTOR] Migrate quota configruation to Celeborn Configuration System

---

common/src/main/java/org/apache/celeborn/common/haclient/RssHARetryClient.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
common/src/test/java/org/apache/celeborn/common/haclient/RssHARetryClientSuiteJ.java
docs/configuration/client.md
docs/configuration/master.md
docs/configuration/worker.md
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
master/src/test/java/org/apache/celeborn/service/deploy/master/SlotsAllocatorSuiteJ.java

[ISSUE-849][REFACTOR] Migrate master and common Celeborn Configuration System

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

[ISSUE-866][BUG] Create File twice should show clear log

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerArguments.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

[ISSUE-871][REFACTOR] Migrate Worker conf to Celeborn Configuration System

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/master.md
docs/configuration/worker.md
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/SingleMasterMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

[ISSUE-869][REFACTOR] Migrate partition size/sorter related conf to Celeborn ConfigEntity

---

.github/workflows/maven.yml
dev/make-distribution.sh

Replace the missing `Remote Shuffle Service` for `maven.yml` and `make-distribution.sh`.

[REFACTOR] Replace the missing `Remote Shuffle Service` 

---

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client/src/main/java/org/apache/celeborn/client/compress/Compressor.java
client/src/main/java/org/apache/celeborn/client/compress/Decompressor.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
common/src/main/java/org/apache/celeborn/common/protocol/CompressionCodec.java
common/src/main/java/org/apache/celeborn/common/protocol/ShuffleMode.java
common/src/main/java/org/apache/celeborn/common/protocol/SlotsAssignPolicy.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
docs/configuration/client.md
docs/configuration/master.md
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithLZ4.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithZSTD.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala

[ISSUE-887][REFACTOR] Configuration type convert to Enum

---

client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SparkUtils.java
client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleReader.scala
common/src/main/java/org/apache/celeborn/reflect/DynClasses.java
common/src/main/java/org/apache/celeborn/reflect/DynConstructors.java
common/src/main/java/org/apache/celeborn/reflect/DynFields.java
common/src/main/java/org/apache/celeborn/reflect/DynMethods.java
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala

These reflect tools are adopted by Apache Parquet/Iceberg/Kyuubi, which simplify the reflection usage.
Simplify the reflection usage.

Introduce reflect helper tools

---

pom.xml

Bump Spark from 3.3.0 to 3.3.1, and upgrade related deps as well
Bump to the latest patched version.

Bump Spark from 3.3.0 to 3.3.1

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala

[MINOR] Fix typo

---

client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

Clean up some code in LifecycleManager and ShuffleClientImpl

[MINOR][CLEANUP] Clean up some code in LifecycleManager and ShuffleClientImpl

---

client-spark/spark-2-shaded/pom.xml
client-spark/spark-3-shaded/pom.xml
pom.xml

[Feature] Shade netty native libraries

---

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala

[ISSUE-918][BUG] Utils.toStatus code is not complete

---

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala

[ISSUE-902][FOLLOWUP] Complete Utils.toStatus

---

docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml

Remove duplicate affinity in master and worker statefulSet yaml.
Tested in own cluster.

[K8S] Remove duplicate affinity in master and worker statefulSet yaml

---

client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java
client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleReader.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssBatchBuilder.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/columnar-shuffle.md

[FEATURE] Support columnar shuffle codegen

---

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/DeviceMonitor.scala

[ISSUE-929][BUG] Flusher thread interrupted and won't recover

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala

[ISSUE-921][BUG] Flush Error should report non critical error

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala

[ISSUE-932][REFACTOR] Device check should not directly reportError

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Shutdown worker if initialized failed.

Shutdown worker if initialized failed.

---

common/src/main/scala/org/apache/celeborn/common/exception/CelebornException.scala
common/src/main/scala/org/apache/celeborn/common/identity/UserIdentifier.scala
common/src/main/scala/org/apache/celeborn/common/rpc/RpcEndpoint.scala
common/src/main/scala/org/apache/celeborn/common/rpc/RpcEndpointAddress.scala
common/src/main/scala/org/apache/celeborn/common/rpc/RpcEndpointNotFoundException.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/Dispatcher.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/Inbox.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/Outbox.scala
common/src/main/scala/org/apache/celeborn/common/util/ThreadUtils.scala
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
common/src/test/java/org/apache/celeborn/common/haclient/RssHARetryClientSuiteJ.java
common/src/test/scala/org/apache/celeborn/common/identity/UserIdentifierSuite.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

Rename RssException to CelebornException

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnBuilder.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchBuilder.scala
client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssNullableColumnBuilder.scala

[FEATURE] Optimize columnar shuffle writer performance without encoding

---

master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java
pom.xml

[ISSUE-939][REFACTOR] Bump up ratis to 2.4.0

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala

Cleanup some code

---

client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java

[ISSUE-925][FOLLOWUP] Refactor class name of RetryingChunkReceiveCallback

---

.asf.yaml

https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
ASF supports using `.asf.yaml` to setup git repo.

[INFRA] Setup .asf.yaml

---

.gitignore

[CELEBORN-1] Test celeborn jira

---

README.md

[COMMUNITY] Update README

---

README.md

https://issues.apache.org/jira/browse/CELEBORN-5

[CELEBORN-5] Update README for jira and slack.

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

PushDataHandler code refactor(#957)
callback code reuse (#959)
#959 

[CELEBORN-6] [REFACTOR] PushDataHandler code refactor

---

common/src/main/java/org/apache/celeborn/common/network/server/MemoryTracker.java
common/src/main/java/org/apache/celeborn/common/unsafe/Platform.java

[CELEBORN-9] [ISSUE-861] Support multiple JDK version build

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
conf/celeborn-defaults.conf.template
docker/helm/values.yaml
docs/configuration/network.md

[ISSUE-911] Decrease numConnectionsPerPeer to achieve better performance

---

common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
common/src/main/java/org/apache/celeborn/common/network/protocol/PushDataHandShake.java
common/src/main/java/org/apache/celeborn/common/network/protocol/RegionFinish.java
common/src/main/java/org/apache/celeborn/common/network/protocol/RegionStart.java

[CELEBORN-10] Add Message Support MapPartition

---

CONTRIBUTING.md

[CELEBORN-5] Update contributing guide.

---

common/src/main/proto/TransportMessages.proto
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
docs/configuration/master.md
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/IMetadataHandler.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/SingleMasterMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MetaHandler.java
master/src/main/proto/Resource.proto
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/metrics/AppDiskUsageMetric.scala
master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java
master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java
master/src/test/scala/org/apache/celeborn/service/deploy/master/AppDiskUsageMetricSuite.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

[CELEBORN-4] Add metrics about top disk used apps.

---

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java

[CELEBORN-46] Refine log for RssInputStream.close()

---

client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java
common/src/main/java/org/apache/celeborn/common/network/server/OneForOneStreamManager.java
common/src/main/java/org/apache/celeborn/common/network/server/StreamManager.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala

1. Remove unused code of `StreamManager`
2. Add debug level log for each register stream after open stream success
3. Client side logError each fetch failed's exception

[CELEBORN-47][IMPROVEMENT] Refine logs about tracking fetch chunk

---

client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java
client/src/main/java/org/apache/celeborn/client/read/Replica.java
client/src/main/java/org/apache/celeborn/client/read/RetryingChunkClient.java
client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java
client/src/test/java/org/apache/celeborn/client/read/RetryingChunkClientSuiteJ.java
common/src/main/java/org/apache/celeborn/common/network/client/ChunkReceivedCallback.java
common/src/main/java/org/apache/celeborn/common/network/client/TransportClient.java
common/src/main/java/org/apache/celeborn/common/network/client/TransportResponseHandler.java
common/src/main/java/org/apache/celeborn/common/network/server/OneForOneStreamManager.java
common/src/main/java/org/apache/celeborn/common/network/server/StreamManager.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/test/java/org/apache/celeborn/common/network/ChunkFetchIntegrationSuiteJ.java
common/src/test/java/org/apache/celeborn/common/network/RequestTimeoutIntegrationSuiteJ.java
common/src/test/java/org/apache/celeborn/common/network/TransportResponseHandlerSuiteJ.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java

[CELEBORN-67] Revert "Fix fetch incorrect data chunk" related commits

---

common/src/main/java/com/aliyun/emr/rss/common/network/client/ChunkFetchFailureException.java
common/src/main/java/com/aliyun/emr/rss/common/network/server/FileManagedBuffers.java

[CELEBORN-69] Fullyread check in FileManagedBuffers is not accurate

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
common/src/main/proto/TransportMessages.proto
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

1. Back compatibility tested by using client jar before this pr and use server-side jar of this pr.
2. When spark.celeborn.test.retryCommitFiles set true, test code for epoch will run.

[CELEBORN-70] Add epoch for each commitFiles request

---

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java

When I test the lasted PR of #1007 , when I quickly restart worker during read data, will directly failed, we should have a retry interval

[CELEBORN-68][FOLLOWUP] Retry on same partition location should have a retry wait interval

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[CELEBORN-79][REFACTOR] Remove unused responseCheckerThread from LifecycleManager

---

client/src/main/scala/org/apache/celeborn/client/ApplicationHeartbeater.scala
client/src/main/scala/org/apache/celeborn/client/Heartbeater.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[CELEBORN-78][REFACTOR] Extract heartbearter from LifecycleManager

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

CELEBORN-76][FOLLOWUP] Support batch commit hard split partition before stage end

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java

[CELEBORN-93][BUG] Rss Raft reject install snapshot

---

bin/celeborn-class
sbin/celeborn-daemon.sh

Improve celeborn scripts `celeborn-daemon.sh` and `celeborn-class.sh` print log and logic.
`CELEBORN_PRINT_LAUNCH_COMMAND` was not used in `celeborn-daemon.sh`, move it to `celeborn-class.sh` and set default to 0 for help developer debug java command. 

[IMPROVEMENT] Improve celeborn script logic

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

[CELEBORN-96][REFACTOR] PushMergedData return partition not found use same code path

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[CELEBORN-76][FOLLOWUP] fix inFlightCommitRequest counting problem

---

.asf.yaml

To eliminate the error message.

[CELEBORN-97] Correct notification mailing list.

---

common/src/main/java/org/apache/celeborn/common/protocol/message/StatusCode.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala

[CELEBORN-71] pushdatahandler supports mappartition write: handshake/regionstart/regionfinish

---

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

In our test env, during the test, I found that sometimes critical reason blacklist workers will be covered by some normal reason, then removed from the blacklist during the next blacklist response.

[CELEBORN-84][IMPROVEMENT] Blacklist critical reason should avoid been covered by normal reason

---

common/src/main/java/org/apache/celeborn/common/network/server/ChannelsLimiter.java
common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java
common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferDispatcher.java
common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferListener.java
common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferRequest.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorterSuiteJ.java

[CELEBORN-91] Refactor memory tracker to support read buffer.

---

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/main/scala/org/apache/celeborn/client/ReviveManager.scala

[CELEBORN-21][REFACTOR] Extract request new partition related logical from LifecycleManager

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md
docs/configuration/network.md

[CELEBORN-102][REFACTOR] TIMEOUT default value should be changed with network timeout

---

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala
client/src/main/scala/org/apache/celeborn/client/CommitManager.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala

[CELEBORN-20][REFACTOR] Extract CommitManager from LifecycleManager

---

worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/ReducePartitionFileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java

[CELEBORN-80] FileWriter supports MapPartition

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java
client-flink/flink-common/pom.xml
client-flink/flink-common/src/main/java/org/apache/celeborn/plugin/flink/utils/Utils.java
client/src/main/java/org/apache/celeborn/client/ShuffleClient.java
client/src/test/java/org/apache/celeborn/client/DummyShuffleClient.java
pom.xml

[CELEBORN-106] flink-plugin supports shufflewrite:OutputGate

---

client/src/main/java/org/apache/celeborn/client/ShuffleClient.java
client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/test/java/org/apache/celeborn/client/DummyShuffleClient.java
client/src/test/java/org/apache/celeborn/client/ShuffleClientBaseSuiteJ.java
client/src/test/java/org/apache/celeborn/client/ShuffleClientImplSuiteJ.java

pushdataByteBuf
@RexXiong @FMX @waitinfuture 

[CELEBORN-11] ShuffleClient supports MapPartition shuffle write:pushdata

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
worker/src/test/java/org/apache/celeborn/service/deploy/worker/WorkerSuiteJ.java

[CELEBORN-61][CELEBORN-62][FEATURE] Shuffle client support slow start, congestion avoidance and congestion control

---

.github/workflows/maven.yml
pom.xml

[CELEBORN-81] Add codecov.

---

.github/workflows/maven.yml
pom.xml

[Celeborn-81][FOLLOWUP]Correct sure fire plugin args.

---

common/src/main/java/org/apache/celeborn/common/meta/FileInfo.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

[CELEBORN-126] Fileinfo adds member bufferSize

---

pom.xml

Rename maven property `maven.plugin.jacoco-maven-plugin.version` to `maven.plugin.jacoco.version` and reorder properties.
Keep consistent.

[CELEBORN-81][FOLLOWUP] Rename and reorder maven properties

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala

[CELEBORN-130] Correct CommitFilesTime metric

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala

[CELEBORN-130] Correct CommitFilesTime metric (#1073)

---

pom.xml

Bump Ratis 2.4.1
Apache Ratis released 2.4.1 recently, it includes bug fixes and improvement.
https://ratis.apache.org/post/2.4.1.html
Especially, https://issues.apache.org/jira/browse/RATIS-1743 fixed a memory leak issue.
This PR is target to both main and branch-0.2

[CELEBORN-127] Bump Ratis 2.4.1

---

.asf.yaml

[CELEBORN-131]Notify pull request event to Jira.

---

.github/PULL_REQUEST_TEMPLATE.md

This PR proposes a new PULL_REQUEST_TEMPLATE.
It is learned from [Apache Spark](https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE), but removed some comments, to make the template cleaner.
No, it's developer only.
Manually review.

[CELEBORN-134][INFRA] Enhance PULL_REQUEST_TEMPLATE

---

common/src/main/scala/org/apache/celeborn/common/quota/Quota.scala

Make exceed log of quota show byte string, more human readable

[CELEBORN-141][IMPROVEMENT] Refactor error log about quota exceed

---

docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml
docker/helm/values.yaml

Move affinity to `values.yaml`.
We should expose the details of the pod for users to view and modify in values.yaml
Local test

[CELEBORN-143][HELM]Exposing pods details to users

---

codecov.yml

[CELEBORN-144]Lower code coverage requirements.

---

.github/workflows/maven.yml

Using github action upload unit test logs
For developer debug

[CELEBORN-149] Upload failure CI unit test logs for developer debug

---

client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala

[CELEBORN-142]Keep committed partition locations semantic consistent when commit files on HDFS.

[CELEBORN-142]Keep committed partition locations semantic consistent when commit files on HDFS.

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGateSuiteJ.java

[CELEBORN-154] replace shuffleclient's shutDown to shutdown

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/java/org/apache/celeborn/client/write/PushState.java
common/src/main/java/org/apache/celeborn/common/network/client/TransportClient.java
common/src/main/java/org/apache/celeborn/common/protocol/message/StatusCode.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md
docs/configuration/worker.md
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushdataTimeoutTest.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

Add timeout for PushData to actively trigger revive instead of waiting for limitMaxInFlight timeout

[CELEBORN-119] Add timeout for pushdata

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartition.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java
client-flink/flink-common/src/main/java/org/apache/celeborn/plugin/flink/buffer/PartitionSortedBuffer.java
client-flink/flink-common/src/main/java/org/apache/celeborn/plugin/flink/buffer/SortBuffer.java

[CELEBORN-156] add remoteShuffleResultPartition in flink-plugin

---

CONTRIBUTING.md
common/src/main/java/org/apache/celeborn/common/util/ShutdownHookManager.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala
common/src/main/scala/org/apache/celeborn/common/metrics/MetricsConfig.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/Dispatcher.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/NettyRpcEnv.scala
docs/configuration/client.md
docs/configuration/index.md
docs/configuration/worker.md
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala

[CELEBORN-157] Change prefix of configurations to celeborn.

[CELEBORN-157] Change prefix of configurations to celeborn.

---

requirements.txt

Upgrade `requirements.txt` to keep consistent w/ [celeborn-website](https://github.com/apache/incubator-celeborn-website/blob/main/requirements.txt)
Keep buiding tool consistent for website.
No.
Manually test.

[CELEBORN-159][INFRA] Upgrade requirements.txt to keep consistent w/ celeborn-website

---

.github/workflows/benchmark.yml
.github/workflows/benchmark_manual.yml
.github/workflows/license.yml
.github/workflows/maven.yml
.github/workflows/regression.yml
.github/workflows/regression_manual.yml
.github/workflows/style.yml
dev/reformat
pom.xml

Split CI workflow into service/spark
Fast CI, prepare to enable Flink CI
No.
CI

[CELEBORN-160][BUILD] Spilt CI workflow

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala

[CELEBORN-165] Fix ut RetryCommitFilesTest failure.

---

common/src/main/scala/org/apache/celeborn/common/meta/AppDiskUsageMetric.scala
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/SingleMasterMetaManager.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java
master/src/test/scala/org/apache/celeborn/service/deploy/master/AppDiskUsageMetricSuite.scala

AppDiskUsage related class should be move to meta package and it will be used in PB serde related class
Refactor code
No

[CELEBORN-174][REFACTOR] Move AppDiskUsage related to meta package

---

client/pom.xml
client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala
tests/spark-it/pom.xml
tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala

Extract common test cases for the previously existing MiniCluster integration tests.
Before we conduct integration tests for Kubernetes, we should extract common test cases for the previously existing MiniCluster integration tests as traits for easy reuse.

[CELEBORN-147][IT]Extraction of common integration test cases

---

build/release/create-package.sh

This PR proposes to add script for creating source release artifacts. 
For releasing.
No, developer only.
```
build/release/create-package.sh source
```
```
(celeborn) ➜  apache-celeborn git:(CELEBORN-177) ll tmp                                
total 26216
-rw-r--r--  1 chengpan  staff   6.8M Dec 29 11:52 apache-celeborn-0.2.0-SNAPSHOT-source.tgz
-rw-r--r--  1 chengpan  staff   833B Dec 29 11:52 apache-celeborn-0.2.0-SNAPSHOT-source.tgz.asc
-rw-r--r--  1 chengpan  staff   172B Dec 29 11:52 apache-celeborn-0.2.0-SNAPSHOT-source.tgz.sha512
```

[CELEBORN-177][BUILD] Script for creating source release artifact

---

client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala
common/src/test/scala/org/apache/celeborn/CelebornFunSuite.scala
common/src/test/scala/org/apache/celeborn/common/CelebornConfSuite.scala
common/src/test/scala/org/apache/celeborn/common/identity/UserIdentifierSuite.scala
common/src/test/scala/org/apache/celeborn/common/meta/WorkerInfoSuite.scala
common/src/test/scala/org/apache/celeborn/common/quota/BaseQuotaManagerSuite.scala
common/src/test/scala/org/apache/celeborn/common/util/PbSerDeUtilsTest.scala
common/src/test/scala/org/apache/celeborn/common/util/UtilsSuite.scala

Rename RssFunSuite to CelebornFunSuite
Make consistent.
No.
Existing UT.

[CELEBORN-181][TEST] Rename RssFunSuite to CelebornFunSuite

---

NOTICE
NOTICE-binary

Update NOTICE to mention 2023
Happy new year!
No.
Review.

[CELEBORN-187][LICENSE] Update NOTICE for 2023

---

build/release/release.sh

Add `build/release/release.sh` to auto upload/move release artifacts to SVN
For releasing.
No, this is for the release manager.
MT.

[CELEBORN-186][BUILD] Auto upload/move release artifacts to svn

---

build/make-distribution.sh
build/release/release.sh
pom.xml

There are a few differences between main and branch-0.2, this PR fixes the gap of those.
Recovering the build of branch-0.2
No.
`build/make-distribution.sh --release`

[CELEBORN-180][FOLLOWUP][0.2] Fix build_service should pass w/o profile

---

.github/workflows/benchmark.yml
.github/workflows/benchmark_manual.yml
.github/workflows/regression.yml
.github/workflows/regression_manual.yml
README.md

Update CI workflow and docs because of `make-distribution.sh` moved.
`make-distribution.sh` was moved from `dev/` to `build/`
No.
CI.

[CELEBORN-180][BUILD][FOLLOWUP] Update CI workflow and docs

---

build/make-distribution.sh
client-flink/common/pom.xml
client-flink/flink-1.14-shaded/pom.xml
client-flink/flink-1.14/pom.xml
pom.xml

This pr will support release packages include celeborn-flink-plugin. Now we can use `./dev/make-distribution.sh -Pflink-1.14 ` to package.

[CELEBORN-175][BUILD] Include Flink client into the binary release tarball

---

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala

Rename batchHandleRequestPartitions to handleRequestPartitions

[CELEBORN-196][REFACTOR] Rename batchHandleRequestPartitions to handleRequestPartitions

---

client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/HugeDataTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushdataTimeoutTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RetryCommitFilesTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RssHashSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RssSortSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SparkTestBase.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithLZ4.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithZSTD.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala

refactor minicluster for ut, and fix failed ut
No
UT

[CELEBORN-173] refactor minicluster and fix ut

---

tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/HugeDataTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushdataTimeoutTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RetryCommitFilesTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RssHashSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RssSortSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SparkTestBase.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithLZ4.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ClusterReadWriteTestWithZSTD.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala

[CELEBORN-173] refactor minicluster and fix ut (#1147)

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala
common/src/main/java/org/apache/celeborn/common/protocol/message/StatusCode.java
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

Change FAILED status to REQUEST_FAILED since it's all used when RPC request failed. Make it more accurate.

[CELEBORN-192][IMPROVEMENT] Change FAILED status to REQUEST_FAILED since it's all used when RPC request failed.

---

pom.xml

[CELEBORN-205] bump version to 0.3.0-SNAPSHOT.

---

docker/helm/templates/configmap.yaml
docker/helm/templates/master-service.yaml
docker/helm/templates/master-statefulset.yaml
docker/helm/templates/prometheus-podmonitor.yaml
docker/helm/templates/worker-service.yaml
docker/helm/templates/worker-statefulset.yaml
docker/helm/values.yaml

Add recommend labels
The changes are needed to be compliant with official Kubernetes and Helm recommendations:
- https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
- https://helm.sh/docs/chart_best_practices/labels/#standard-labels
Helm install on Minikube

[CELEBORN-210][HELM] Add recommended labels in celeborn chart

---

pom.xml
sbin/start-worker.sh

[CELEBORN-171] Support JDK11.

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java

[CELEBORN-228]Refactor PartitionFileSorter to avoid specific JDK dependency.

---

common/src/main/scala/org/apache/celeborn/common/meta/AppDiskUsageMetric.scala

[CELEBORN-230] AppDiskUsageSnapShot overrides equals() without override hashCode()

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/buffer/BufferPacker.java
common/src/main/java/org/apache/celeborn/common/haclient/RssHARetryClient.java

[CELEBORN-248] Non-ASCII characters in source code

---

charts/celeborn/templates/master-statefulset.yaml
charts/celeborn/templates/worker-statefulset.yaml
charts/celeborn/values.yaml

Improve helm values, helps users configure custom security context for master/worker statefulsets.

[CELEBORN-256][HELM] Improve master/worker statefulset security context

---

sbin/celeborn-daemon.sh

Correct wrong comment in restart.sh

[CELEBORN-259][BUG] Correct wrong comment in restart.sh

---

common/src/main/java/org/apache/celeborn/common/network/client/TransportResponseHandler.java

Avoid one time of search hash key when handling response.

[CELEBORN-257][IMPROVEMENT] Avoid one hash searching when process message in TransportResponseHandler

---

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
master/src/test/scala/org/apache/celeborn/service/deploy/master/AppDiskUsageMetricSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushdataTimeoutTest.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/ShuffleFallbackSuite.scala
tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
toolkit/scripts/genConfs.py

Fix wrong old version configurations

[CELEBORN-266] Fix wrong old version configurations

---

tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushDataTimeoutTest.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

[CELEBORN-269][BUG] Disable replication throw NPE when removeBatch in pushDataHandler

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

Add replication information to PushState should should use peer location's hostAndPort

[CELEBORN-271][BUG] PushState should should use peer's location

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

ResourceConsumptionSource should add to metricsSystem

[CELEBORN-247][FOLLOWUP] ResourceConsumptionSource should add to metricsSystem

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

Master need to check whether the user is congest or not if enables `push.data.replicate`
Master could miss the congestion status if enable `push.data.replicate`
no
MT.

[CELEBORN-207][FOLLOW_UP] Master could miss the congestion status if enable `push.data.replicate`

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

Return soft split status if soft split is true
PushDataHandle callback could miss soft split status
no
Existing UT.

[CELEBORN-277] PushDataHandle callback could miss soft split status

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md

fix typo in CelebornConf
fix typo in CelebornConf
No
Integration test.

[CELEBORN-284] Fix typo in CelebornConf

---

.gitattributes

Exclude licenses-binary from source pakcage.

[CELEBORN-286] Fix source package contains license-binary.

---

common/src/main/scala/org/apache/celeborn/common/metrics/source/AbstractSource.scala
common/src/main/scala/org/apache/celeborn/common/metrics/source/Source.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/CongestionController.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala
worker/src/test/java/org/apache/celeborn/service/deploy/worker/congestcontrol/TestCongestionController.java

Add user level push data speed metric
With the user level metrics, it's convenient for us to track the user behavior, to monitor the worker status 
no
Added UT

[CELEBORN-279] Add user level push data speed metric

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssCompressibleColumnBuilder.scala
client/src/main/java/org/apache/celeborn/client/ShuffleClient.java
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala

Change celeborn.$module.io.clientThreads to celeborn.$module.io.serverThreads
and fix some typo 
The fromCelebornConf method in Utils should set celeborn.$module.io.serverThreads instead of setting celeborn.$module.io.clientThreads twice
NO

[CELEBORN-304] Change celeborn.$module.io.clientThreads to celeborn.$module.io.serverThreads

---

common/src/main/java/org/apache/celeborn/common/network/protocol/BacklogAnnouncement.java
common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

Add BacklogAnnouncement RPC.
BufferStream needs it to implement its functionality.
NO
Integration test.

[CELEBORN-282] Add BacklogAnnouncement RPC.

---

client-flink/flink-1.14-shaded/pom.xml

include roaringbitmap which is celeborn needed in plugin
include roaringbitmap which is celeborn needed in plugin
NO
manual

[CELEBORN-310] include roaringbitmap in flink plugin

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/buffer/BufferPacker.java
client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java
client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartition.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGateSuiteJ.java

add logs
optimize RemoteShuffleOutputGate: modify the time registershuffle from setup to pushdatahandshake
optimize RemoteShuffleResultPartition: optimize close code and add new method

[CELEBORN-290] optimize flink-plugin RemoteShuffleOutputGate/RemoteShuffleResultPartition

---

common/src/main/java/org/apache/celeborn/common/meta/FileInfo.java
common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
common/src/main/java/org/apache/celeborn/common/network/protocol/ReadData.java
common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java
common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferDispatcher.java
common/src/main/java/org/apache/celeborn/common/network/util/TransportConf.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
docs/configuration/worker.md
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

This pr enable Celeborn to support buffer stream and credit-based data flow.
To support buffer stream.
NO.
Flink Integration test.

[CELEBORN-234] Implement buffer stream.

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/buffer/BufferPacker.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/BufferPackSuitJ.java

[CELEBORN-314] Add ut for BufferPack and fix npe while logging

---

common/src/main/proto/TransportMessages.proto
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala

support transport message for map partition register
need trans message when register map partition shuffle
No
UT & manual test

[CELEBORN-317] add REGISTER_MAP_PARTITION_TASK message type

---

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java

fix deadlock & bugs in bufferStreamManager
1.sendData need mapPartition ownership when execute cleanResource while hold readers lock at the same time
2.readBuffers holds map partition ownership but need also reader lock when execute readAndSend.
NO
UT

[CELEBORN-318][FLINK] fix deadlock & bugs in bufferStreamManager

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala

1. Correct fetch handler about readAndCredit.
1. To improve code readability.
NO.
UT.

[CELEBORN-320][FLINK] fix handle wrong message type in FetchHandler.

---

pom.xml
tests/flink-it/pom.xml
tests/flink-it/src/test/java/org/apache/celeborn/tests/flink/WordCountHelper.java
tests/flink-it/src/test/resources/log4j2-test.xml
tests/flink-it/src/test/scala/org/apache/celeborn/tests/flink/WordCountTest.scala

Add flink e2e test with celeborn.
NO.
UT.

[CELEBORN-289] Add flink integration test module.

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/FlinkTransportClientFactory.java
client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java
client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java
common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java
common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java

[CELEBORN-324][FLINK] Flink plugin needs reuse connections.

---

client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/PartitionSortedBufferSuitJ.java

[CELEBORN-315] [Flink] add ut for flink-plugin PartitionSortedBuffer

---

docker/helm/templates/configmap.yaml
docker/helm/templates/master-statefulset.yaml
docker/helm/templates/worker-statefulset.yaml
docker/helm/values.yaml

Add the k8s cluster name configuration.

[CELEBORN-343] Add configuration for k8s cluster name

---

common/src/main/scala/org/apache/celeborn/common/meta/DeviceInfo.scala

to make getDeviceAndDiskInfos log print cleaer
NO
NO

[CELEBORN-351] Add \n to the log to make log print clearer

---

common-shade/pom.xml
pom.xml

Create shaded module for Celeborn common

[CELEBORN-355][BUILD] Create shaded module for Celeborn common

---

client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala

…artitionIds
1.return lastSucceedPartitionIds when actually replay to current rpc context
2.remove shuffleSucceedPartitionIds when shuffle expired
we may get updated shuffleSucceedPartitionIds by other thread while reducerFileGroupsMap.get the older file groups result(which may not contains newly finished partitions). So we need get the snapshot shuffleSucceedPartitionIds before 
we return current reducerFileGroups of that shuffle. No need to lock here as currentHashMap will get the volatile result.
So reducerFileGroupsMap will get the newly current result when response.
No
tpcds99 1T

[CELEBORN-354][Flink] fix map partition may return the wrong result

---

master/pom.xml
pom.xml

Add ratis-shell jar to celeborn

[CELEBORN-359] Add ratis-shell to celeborn

---

assets/grafana/rss-dashboard.json

Add sorted files metric in dashboard.json
NO.
Manual test.

[CELEBORN-373] Add sorted files into grafana dashboard

---

.github/workflows/maven.yml
.github/workflows/style.yml

Enable GitHub CI on `branch-*`
I notice that branch-0.2 does not trigger CI, and there are some style errors
No.
Pass CI.

[CELEBORN-375][INFRA] Enable CI on branch-*

---

dev/reformat
pom.xml

CI on branch-0.2 is broken now
Recover CI on branch-0.2
No
Pass CI.

[CELEBORN-376][BUILD] Recover CI on branch-0.2

---

bin/celeborn-class
bin/celeborn-ratis
sbin/celeborn-daemon.sh
sbin/load-celeborn-env.sh
sbin/restart-worker.sh
sbin/start-all.sh
sbin/start-master.sh
sbin/start-worker.sh
sbin/stop-all.sh

Export necessary env in load-celeborn-env.sh

[CELEBORN-360] Export necessary env in load-celeborn-env.sh

---

.github/workflows/maven.yml

Enable flink integration test module.
To enable flink integration in GitHub CI.
NO.
UT.

[CELEBORN-380][FLINK] Enable flink integration test in GitHub CI.

---

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java

1.Refine register/release synchronization
2.initial credit may equal to 0, we can bypass that.
Avoid useless synchronization.
No
UT & Tpcds 1T pass

[CELEBORN-391][Flink] Refine register/release synchronization

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java

Make fileSorterExecutors thread num can be customized

[CELEBORN-399] Make fileSorterExecutors thread num can be customized

---

common/src/main/scala/org/apache/celeborn/common/metrics/source/RPCSource.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala

Add RPC metrics for OpenStream

[CELEBORN-400] Add RPC metrics for OpenStream

---

common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala

1. Add log about read buffer usage and limit.
2. Add log about memory manager action transmission log.
3. Change trim relative logs to debug to reduce worker log size.
Ditto.
NO.
UT.

[CELEBORN-394] Refine memory manager's log.

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Add lost worker infos to http request

[CELEBORN-408] Add lost worker infos to http request

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Add blacklist to http request to indicate blacklisted worker

[CELEBORN-406] Add blacklist to http request to indicate blacklisted worker

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Add PartitionLocationInfo to worker's http request

[CELEBORN-409] Add PartitionLocationInfo to worker's http request

---

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java
client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java
common/src/main/java/org/apache/celeborn/common/network/protocol/TransportableError.java
common/src/main/java/org/apache/celeborn/common/util/ExceptionUtils.java

Notify related task fail when channel inactive.
Task may get stuck when channel inactive.
No
TPCDS 1T with random kill workers.

[CELEBORN-381][FLINK] fail task when channel inactive

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Add unavailablePeers to http request

[CELEBORN-420] Add unavailablePeers to http request

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala

Add shutdown and registered to http request

[CELEBORN-421] Add shutdown and registered to http request

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
service/src/main/scala/org/apache/celeborn/server/common/http/HttpRequestHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala

[CELEBORN-423] Format http request result

---

service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala

[CELEBORN-423][FOLLOWUP] Format http request

---

README.md
conf/hosts.template
sbin/start-all.sh

1. Add hosts template to simplify deploy process.
2. Add a clear description that if you have only one worker, replication should be disabled.
3. update deploy docs.
Ditto.
NO.
Manual test on the cluster.

[CELEBORN-420] Add hosts template and docs about start-all scripts.

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGateFactory.java
client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGateSuiteJ.java
client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java

Refine code in RemoteShuffleOutputGate
ditto
NO
UT

[CELEBORN-432][FLINK] Refine RemoteShuffleOutputGate and RemoteShuffleInputGateFactory

---

common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md

1. remove range validation.
2. Add constrain to make sure that memory parameters are valid.
Ditto.
NO.

[CELEBORN-434] Add constrain about memory manager's parameters.

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGate.java

Code refine for RemoteShuffleInputGate
ditto
NO
UT

[CELEBORN-435][FLINK] Code refine for RemoteShuffleInputGate

---

client/src/main/scala/org/apache/celeborn/client/CommitManager.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala
client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala
client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala
common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala

Code refine for client and common
Code refine for client and common
NO
UT

[CELEBORN-443] Code refine for client and common

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java
client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGate.java
client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGateFactory.java

1. Implement concurrent reading limit.
Ditto.
NO.

[CELEBORN-440][FLINK] Implement numConcurrentReading in RemoteShuffleInputGate.

---

common/src/main/scala/org/apache/celeborn/common/metrics/MetricsSystem.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
master/src/main/scala/org/apache/celeborn/service/deploy/master/MasterSource.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala

ServletPath not belong to source, move it to MetricsSystem object

[CELEBORN-438] Move ServletPath to MetricsSytsem

---

common/src/main/java/org/apache/celeborn/common/meta/FileInfo.java
common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java
common/src/test/java/org/apache/celeborn/common/network/server/BufferStreamManagerSuiteJ.java
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

Code refine for worker.
Code refine for worker.
No
UT

[CELEBORN-454] Code refine for worker

---

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java

String format fails because of type mismatch.
No

[CELEBORN-471] Fix String.format wrong type in ShuffleClientImpl

---

client/src/main/java/org/apache/celeborn/client/compress/Compressor.java
client/src/main/java/org/apache/celeborn/client/compress/Decompressor.java
client/src/main/java/org/apache/celeborn/client/compress/RssLz4Trait.java
common/src/main/java/org/apache/celeborn/common/haclient/RssHARetryClient.java
master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java
service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/ReducePartitionFileWriter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerArguments.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/FlushTask.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

Fix typo and remove unused code.
As title.
No
No logical change.

[MINOR] Fix typo and remove unused code

---

pom.xml

Fix issue #1380   by update dependency org.yaml:snakeyaml:1.33

[CELEBORN-482] Fix CVE dependency issue

---

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java

Same as JIRA#477.
Dotto.
NO.
UT and cluster.

[CELEBORN-477][FOLLOWUP] Report failed partition to flink framework.

---

.rat-excludes

Remove `LimitedInputStream.java` exclusion from Apache Rat.
The `LimitedInputStream.java` has a standard Apache License v2 header, which can pass the Apache Rat Check.
No.
```
build/mvn apache-rat:check
```
Also passed the CI license check.

[CELEBORN-372][FOLLOWUP][LICENSE] Remove exclusion from Apache Rat

---

pom.xml

Jacoco supports the multi-module project.
To get an accurate code coverage report.

[CELEBORN-280] Enable Jacoco multi-module mode to collect coverage report.

---

.github/workflows/maven.yml
common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java
pom.xml

Fix and enable JDK 11 for CI. We need to add ```--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED```
in extraJavaTestArgs to support java 10 and higher
No
UT

[CELEBORN-497]Fix and enable JDK 11 for CI

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md

Some of users and new comers don't want replication on, so better to make is default to false.
Yes, the default value of celeborn.push.replicate.enabled changes from true to false.
UT.

[CELEBORN-485] Make celeborn.push.replicate.enabled default to false

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md
docs/configuration/worker.md
worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java

Fix typo of SHUFFLE_CHUCK_SIZE

[CELEBORN-505] Fix typo of SHUFFLE_CHUCK_SIZE

---

charts/celeborn/values.yaml

Streamline the `Values File`.
We will not use this field `celebornVersion` and we have rename some configurations like:
celeborn.worker.fetch.chunk.size => celeborn.shuffle.chunk.size
celeborn.push.io.threads => celeborn.worker.push.io.threads
In order not to mislead users and streamline the `Values File`.
No

[CELEBORN-504] Remove useless fields and modify misnamed configurations in `Values.yaml `

---

client/src/main/scala/org/apache/celeborn/client/ApplicationHeartbeater.scala
client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala
client/src/main/scala/org/apache/celeborn/client/CommitManager.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleBlacklistManager.scala
client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
client/src/main/scala/org/apache/celeborn/client/WorkerStatusTracker.scala
common/src/main/proto/TransportMessages.proto
common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/metrics/source/RPCSource.scala
common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
docs/configuration/client.md
master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

Merge GetBlacklistResponse to HeartbeatFromApplication

[CELEBORN-502][REFACTOR] Merge GetBlacklistResponse to HeartbeatFromApplication

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

[CELEBORN-502][FOLLOWUP] HeatbeatFromApplicationResponse should remove workersSnapshot from localBlacklist

---

common/src/main/scala/org/apache/celeborn/common/meta/WorkerPartitionLocationInfo.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala

[CELEBORN-523][REFACTOR] Remove unnecessary code in WorkerPartitionLocationInfo

---

docs/monitoring.md

Remove removed RPC metrics in metric doc

[CELEBORN-516][FOLLOWUP] Remove removed RPC metrics in metric doc

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
common/src/main/scala/org/apache/celeborn/common/rpc/netty/NettyRpcEnv.scala
docs/configuration/network.md

Add config entity of celeborn.rpc.io.threads

[CELEBORN-540][Refactor] Add config entity of celeborn.rpc.io.threads

---

README.md

Add DingTalk contact info.
Ditto.
NO.

Add dingTalk contact info.

---

README.md

[CELEBORN-549] Update readme about deploy flink client.

---

pom.xml

Update Netty version to 4.1.92. According to Netty's release note, this shall introduce some performance benefits.
Ditto.
NO.
UT.

[CELEBORN-569] Update netty version to 4.1.92.

---

README.md
docs/cluster_planning.md
docs/deploy.md
docs/monitoring.md

1. Add cluster planning docs.
2. Add some description for metrics.
3. Update deploy description for flink.
Ditto.
NO.
There is no need to test.

[CELEBORN-570] Update docs about monitor and deployment.

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala

```
23/05/08 14:16:09,904 DEBUG [dispatcher-event-loop-36] Worker: Received CommitFiles request, application_1681801473427_4055742_1-50, master files 1011-0,75-0; slave files 1010-0,74-0.
23/05/08 14:16:09,905 DEBUG [dispatcher-event-loop-36] Worker: Done processed CommitFiles request with shuffleKey application_1681801473427_4055742_1-50, in 1ms.
23/05/08 14:16:09,906 INFO [async-reply] Worker: CommitFiles for application_1681801473427_4055742_1-50 success with 0 master partitions and 0 slave partitions! 
```
Above logs is so confusing, it didn't show the committed empty partition location. This pr indicate this

[CELEBORN-578][REFACTOR] Refine commit file's log to indicate more clear about empty partitions

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/client.md
docs/configuration/worker.md

Remove test conf's category to avoid make user confused.

[CELEBORN-588] Remove test conf's category

---

common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala

Refactor PbSerDeUtils's some foreach code format

[CELEBORN-592][REFACTOR] Refactor PbSerDeUtils's some foreach code format

---

master/src/main/java/org/apache/celeborn/service/deploy/master/SlotsAllocator.java

Check rack should use nextMasterInd

[CELEBORN-446][FOLLOWUP]  Check rack should use nextMasterInd

---

README.md

[CELEBORN-598] Fix Typos in README

---

pom.xml

[CELEBORN-603] Update version to 0.4.0-SNAPSHOT

---

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala

1. Remove unused method
2. Refactor master's worker info HTTP request
```
====================== Workers Info in Master ===========================xx.xx.xx.xx:9092:9094:9093:9095
Host: xx.xx.xx.xx
RpcPort: 9092
PushPort: 9094
FetchPort: 9093
ReplicatePort: 9095
SlotsUsed: 0
LastHeartbeat: 1684921290537
HeartBeatElapsedSeconds: 17
Disks:
DiskInfo0: DiskInfo(maxSlots: 53445, committed shuffles 0 shuffleAllocations: Map(), mountPoint: /mnt/ssd/1, usableSpace: 3586638958592, avgFlushTime: 0, avgFetchTime: 0, activeSlots: 0) status: HEALTHY dirs
DiskInfo1: DiskInfo(maxSlots: 53445, committed shuffles 0 shuffleAllocations: Map(), mountPoint: /mnt/ssd/0, usableSpace: 3586638917632, avgFlushTime: 0, avgFetchTime: 0, activeSlots: 0) status: HEALTHY dirs
DiskInfo2: DiskInfo(maxSlots: 53445, …
```

[CELEBORN-609] Refactor master's worker info HTTP request

---

.github/workflows/maven.yml
README.md
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java
client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java
client-spark/spark-3/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java
pom.xml
tests/spark-it/pom.xml

- Add new profile `spark-3.4`
- Change code to adapt SPARK-39391
- Test Celeborn against Spark 3.4.0
Support the latest Spark 3.4
Yes, brings Spark 3.4 support officially.
Pass GA

[CELEBORN-604][SPARK] Support Spark 3.4

---

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala

[CELEBORN-614] Simplify StorageManager's flushFileWriters to avoid too much cost on collection operation

---

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
docs/configuration/worker.md
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala

now flink client hasn't support partition split, so server side add a configuration to close split.

[CELEBORN-618] [FLINK] worker side adds partition split configuration options

---

client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/RssColumnarBatchCodeGenBuild.scala

Fix columnar shuffle codegen exception. This is a refactoring of #1523.

[CELEBORN-620] Fix columnar shuffle codegen exception

---

docs/developers/glutensupport.md

As title.
As title.
No.
Manual test.

[CELEBORN-870][FOLLOWUP][DOC] Document on usage together with Gluten

---

client/src/main/java/org/apache/celeborn/client/write/DataPusher.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/CreditStreamManager.java
worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala

Make all single thread use standard ThreadUtils to simplify the code

[CELEBORN-1226][BRANCH-0.4.0] Unify creation of thread using ThreadUtils

---

assets/grafana/celeborn-dashboard.json

To correct layout of Celeborn grafana dashboard

[CELEBORN-1468] update dashboard layout for Celeborn 0.5

---

assets/tez-patch/Customize-tez-main-class.patch
assets/tez-patch/for_local_test.patch

Add a Tez patch to support customizing the main class.
NO.
Cluster test.

[CELEBORN-1540] Add patch to customize tez main class.
