client-spark/shuffle-manager-2/pom.xml
[BUG] Correct the pom for shuffle-manager-2 for include com.aliyun.emr:client
Update the shuffle-manager-2 for include com.aliyun.emr:client-java to com.aliyun.emr:client
Without this fix, shuffle-manager-2 will throw ClassNotForndException
N/A
#23 
N/A
./dev/make-distribution.sh -Pspark-2 -Dspark.version=2.4.5
grep -lr "ShuffleClient" ${package}/spark/*
/cc @waitinfuture @FMX 
/assign @wangshengjie123
=> [BUG] Correct the pom for shuffle-manager-2 for include com.aliyun.emr:client

client/src/main/java/com/aliyun/emr/rss/client/write/LifecycleManager.scala
When testing close and restart a worker when  running application
Worker in blacklist and WorkerRef is null
```
22/03/29 15:01:46 WARN LifecycleManager: [reserve buffer] failed due to blacklist:
Host: xxx.xxx.xxx.xx
RpcPort: 45149
PushPort: 46795
FetchPort: 38947
TotalSlots: -1
SlotsUsed: 0
SlotsAvailable: -1
LastHeartBeat: 0
WorkerRef: null
```
Cause task throw NPE when reserveSlot 
```
22/03/29 15:01:46 ERROR Inbox: Ignoring error
at com.aliyun.emr.rss.client.write.LifecycleManager.$anonfun$reserveSlotsWithRetry$2(LifecycleManager.scala:803)
at com.aliyun.emr.rss.client.write.LifecycleManager.$anonfun$reserveSlotsWithRetry$2$adapted(LifecycleManager.scala:787)
at scala.collection.Iterator.foreach(Iterator.scala:943)
at …
```
=> [ISSUE-80] When rss is in blacklist and failed for reserve, rpcRef could be null

CONFIGURATION_GUIDE.md, client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java, common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala
When test RSS I noticed that register shuffle failed too quickly and seems not retry, after read the code found that the retry times and retry wait time can't be customized and the original retry wait is 3ms, seems. wrong.
=> [BUG] Register shuffle with configurable retry times and retry wait time

pom.xml, server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java
For improved performance and bugfix.
There are some changes in memory.
https://netty.io/news/2022/03/10/4-1-75-Final.html
Netty 4.1.77
ratis 2.2.0
Betty 4.1.73
ratis 2.0.0
=> [Feature] update netty and ratis version.

common/pom.xml, common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/JVMCPUSource.scala, common/src/main/scala/com/aliyun/emr/rss/common/metrics/source/JVMSource.scala, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
Add metric source for JVM and JVMCPU, register on master and work for performance monitor.
Help to monitor the JVM performance of master and worker, if cluster has a large number of new users/shuffles we can better judge whether current cluster situation can support them.
name format of new added metrics under JVMSource is different with previous Source's metrics, because it directly use MetricSet under com.codahale.metrics.jvm to register. 
New added metrics example:
(JVMSource metrics)
metrics_PS_Scavenge_count_Value{role="Worker"} 1 1653560687351
metrics_PS_Scavenge_time_Value{role="Worker"} 121 1653560687351
metrics_PS_MarkSweep_count_Value{role="Worker"} 1 1653560687351
metrics_PS_MarkSweep_time_Value{role="Worker"} 140 1653560687351
metrics_heap_committed_Value{role="Worker"} …
=> [FEATURE]Add metrics source for JVM and CPU

client/src/main/java/com/aliyun/emr/rss/client/ShuffleClientImpl.java
Fix bug about success response replied by inFlightBatch not clean the corresponding batch. Finally stage failed caused by check inFlighBatchs
Fix Bug
=> [ISSUE-148][BUG] MapEnd but speculation task's inFlightBatch not cleaned

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala, server-worker/pom.xml
In current code, handRevive will throw below exception
```
22/06/23 02:21:15 ERROR LifecycleManager: [reserveSlots] Failed to reserve buffers for application_1655794079700_241721_1-1 from worker Host:10.169.21.29:RpcPort:28295:PushPort:21395:FetchPort:26315:ReplicatePort:32247. Reason: Exception when askSync Res
erveSlots for application_1655794079700_241721_1-1, Exception thrown in awaitResult:
22/06/23 02:21:15 ERROR Inbox: Ignoring error
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
at java.util.LinkedList.get(LinkedList.java:476)
at com.aliyun.emr.rss.client.write.LifecycleManager.handleChangePartitionLocation(LifecycleManager.scala:466)
at com.aliyun.emr.rss.client.write.LifecycleManager.com$aliyun$emr$rss$client$ …
```
=> [ISSUE-158][BUG] When revive meet reserve slot filed, will throw ArrayBoundOutOfIndex exception

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
Fix worker pushserverPort and replicateServerPort conflict
add rss.replicateserver.port configuration item
https://github.com/alibaba/RemoteShuffleService/issues/164
=> [BUG] Fix worker pushserverPort and replicateServerPort conflict

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/MasterArguments.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/WorkerArguments.scala
Add worker rpc port config, replace the master & worker arguments port's default value with config from RssConf.
For better monitor the rpc port workload of worker.
And in previous Master, it will use the value from MasterArguments to create master's rpcEnv, but if user also set the "rss.master.port" or "rss.master.address", it may cause the RssHARetryClient use different port value with Master. Currently if user set master's port by -p/--port in command line when launching master, it may cause RssHARetryClient could not find the real rpc port of master, thus i think may need to find a replacement of current RssHARetryClient's constructor logic or forbid user to set master's port by -p/--port.
masterPort used by RssHARetryClient's constructor may conflict with Master's real port.
#211 …
=> [Feature] Support set rpc port config

client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Compressor.java
We encounter issue 
in compress method , it require `maxDestLen >= maxCompressedLength(srcLen)`
But we use `length` to check
```
if (compressedBuffer.length - HEADER_LENGTH < length) 
```
but ` maxCompressedLength(length)` can  greater than  `length`, then cause this issue.
=> [ISSUE-281][BUG] Use correct maxDestLength to check if buffer can satisfy compress result

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala
```
22/08/02 07:19:11 INFO LifecycleManager: Received Blacklist from Master, blacklist: null unkown workers: null
22/08/02 07:19:26 ERROR LifecycleManager: Init rpc client for 
Host: 10.169.32.83
RpcPort: 33767
PushPort: 32305
FetchPort: 28383
ReplicatePort: 32093
TotalSlots: -1
SlotsUsed: 0
SlotsAvailable: -1
LastHeartBeat: 0
WorkerRef: null
failed
com.aliyun.emr.rss.common.rpc.RpcTimeoutException: Futures timed out after [30 seconds]. This timeout is controlled by rss.rpc.lookupTimeout
at com.aliyun.emr.rss.common.rpc.RpcTimeout.com$aliyun$emr$rss$common$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:46)
at com.aliyun.emr.rss.common.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:61)
at com.aliyun.emr.rss.common.rpc.RpcTimeout$$anonfun$addMessageIfT …
```
=> [ISSUE-291][REFACTOR]  When worker endpoint initializing failed, print clear warning log

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/PartitionFilesSorter.java
mark `ShuffleBlockInfo` static
Perf improvement, to avoid creating unnecessary outer class
Existing test
=> ShuffleBlockInfo should be static inner class

server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/MasterSource.scala
[ISSUE-305][FEATURE] Add metrics for marking active master
Add metric to monitor the status of master, if it is active under HA mode.
In order to be more convenient to check the active master under HA mode in dashboard. Using the Int instead of Boolean type to represent the status could more intuitively observe the election status of the Ratis cluster.
Using Int instead of Boolean or IP to represent status.
#305 
unit test
=> [ISSUE-305][FEATURE] Add metrics for marking active master

.github/workflows/maven.yml, CONTRIBUTING.md, README.md, build/mvn, client-spark/shuffle-manager-2/pom.xml, client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala, client-spark/shuffle-manager-3/pom.xml, client-spark/shuffle-manager-common/pom.xml, client/pom.xml, common/pom.xml, dev/check-spark-2.4.sh, dev/check-spark-3.0.sh, dev/check.sh, dev/checkForSpark2.sh, dev/checkForSpark3.sh, dev/make-distribution.sh, pom.xml, server-common/pom.xml, server-master/pom.xml, server-worker/pom.xml, server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/integration/SkewJoinTest.scala
- `build/mvn` is introduced for auto-downloading Apache Maven if no suitable candidate `mvn` in the PATH, the suitable `mvn` means the version of `mvn` must be equal or great than `maven.version` defined in `pom.xml`
- `spark-2` and `spark-3` are changed into `spark-2.4` and `spark-3.0`, another versions like `spark-3.1`, `spark-3.2` will be added in the following PRs.
- simplify GitHub workflow yaml by using matrix syntax
- enable build cache on GitHub workflow
- extract version of most deps into maven properties
To make `pom.xml` and CI script more clear and flexible to build w/ different spark versions
=> Build: Enhance build system

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HANodeDetails.java, server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/ha/HARaftServer.java, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
Ratis HA port being occupied makes master cannot normally launch
In original logic, it doesn't check if the port is occupied here, it will only check if the port is located in the valid port range.
And if the HA port is occupied (images pasted in Issue), it will throw below exception during Ratis server’s learder election, then make the Master's process stuck there and block the other component's initialization such as prometheus http endpoint.
So it is necessary to check whether the HA is occupied before the Ratis server launch, and exit the Master process if it is.
After changed, Master will throw below exception if HA port is occupied.
```
starting com.aliyun.emr.rss.service.deploy.master.Master, logging to /var/log/rss/rss-root-com.aliyun.emr.rss.service.deploy.master.xxxx.xxxr.xxx.io. …
```
=> [ISSUE-304][BUG]HA port being occupied makes master cannot normally launch

client/src/main/java/com/aliyun/emr/rss/client/read/RetryingChunkClient.java
When closing worker open stream failed
```
22/08/18 15:25:45,764 WARN [fetch-server-11-12] TransportRequestHandler: Fail to sending result ChunkFetchSuccess{streamChunkId=StreamChunkId{streamId=1675775640085, chunkIndex=0}, buffer=FileSegmentManagedBuffer{file=/mnt/disk/0/rss-worker/shuffle_data/application_1659496226079_3301656/3/2-0-0, offset=0, length=8566516}} to /xx.xx.xx.xx:38074; closing connection
io.netty.channel.StacklessClosedChannelException
at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
```
RetryingChunkClient.openChunks directly failed after 4 tries
```
Caused by: java.io.IOException: Could not open chunks after 4 tries.
at com.aliyun.emr.rss.client.read.RetryingChunkClient.openChunks(RetryingChunkClient.java:139)
at …
```
=> [ISSUE-385][FEATURE] RetryingChunkClient openChunks failed should wait

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/StorageManager.scala
```
22/08/19 22:09:49,057 ERROR [local-storage-scheduler] LocalDeviceMonitor: Receive report exception, ArrayBuffer(/mnt/disk2/hadoop/rss-worker/shuffle_data, /mnt/disk2/hadoop/rss-worker/shuffle_data), java.io.IOException: Slow Flusher!
```
=> [ISSUE-396] Incorrectly report Slow Flusher

common/src/main/java/com/aliyun/emr/rss/common/network/server/MemoryTracker.java, common/src/main/java/com/aliyun/emr/rss/common/network/util/ByteUnit.java
Improve MemoryTracker log format and change it's thread to daemon
the current format looks not friendly.
```
22/08/27 20:33:09 INFO MemoryTracker: Track all direct memory usage :1928.0/4096.0,disk buffer size:1.2319183349609375, sort memory size : 0.0
22/08/27 20:33:19 INFO MemoryTracker: Track all direct memory usage :1928.0/4096.0,disk buffer size:1.2319183349609375, sort memory size : 0.0
22/08/27 20:33:29 INFO MemoryTracker: Track all direct memory usage :1928.0/4096.0,disk buffer size:1.2319183349609375, sort memory size : 0.0
```
A monitor thread should be a daemon, otherwise, it may block shutdown.
=> Improve MemoryTracker log format and change it's thread to daemon

server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/SlotsAllocator.java, server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/SlotsAllocatorSuiteJ.java
When `workers.size() < 2 && shouldReplicate`, `SlotsAllocator#offerSlotsRoundRobin` and `SlotsAllocator#offerSlotsLoadAware` should return empty Map instead of `null`.
Fix NPE
```
22/08/28 00:48:55 ERROR Inbox: Ignoring error
at com.aliyun.emr.rss.service.deploy.master.SlotsAllocator.slotsToDiskAllocations(SlotsAllocator.java:388)
at com.aliyun.emr.rss.service.deploy.master.Master.handleRequestSlots(Master.scala:412)
at com.aliyun.emr.rss.service.deploy.master.Master$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$10(Master.scala:194)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at com.aliyun.emr.rss.service.deploy.master.Master.executeWithLeaderChecker(Master.scala:167)
at …
```
=> Fix NPE caused by SlotsAllocator returns null

common/pom.xml, common/src/test/scala/com/aliyun/emr/rss/common/meta/WorkerInfoSuite.scala, server-master/pom.xml
Add scalatest-maven-plugin in common's module pom.
These 3 unit tests which use scalatest not be launched in pipeline when using maven test.
WorkerInfoSuite, RssConfSuite, UtilsSuite
Should we use the same configs of `scalatest-maven-plugin` for all module's pom which has this plugin in <extensions> ? Current new added config is copied from worker module's pom. And should we add this plugin in advance for other modules which have scala unit test only in the Junit style? Such as client-spark/shuffle-manager-2/3.
#465 
unit tests
=> [ISSUE-465][Bug] Common module scalatest style unit test don't actually run

server-master/pom.xml, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/http/HttpRequestHandler.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/http/HttpRequestHandler.scala
Implement more info for admin to directly know cluster's status
Master
```
(base) [root@ip-xx-xx-xx-xx ~]# curl localhost:9098/applications
application_1661229435673_1827267(base) 
[root@ip-xx-xx-xx-xx ~]# curl localhost:9098/shuffles
application_1661229435673_1827267-0(base)
```
Worker
```
[root@ip-xx-xx-xx-xx ~]# curl localhost:9096/workerInfo
Host: xx-xx-xx-xx
RpcPort: 37699
PushPort: 11114
FetchPort: 11113
ReplicatePort: 11115
TotalSlots: 40000
SlotsUsed: 15
SlotsAvailable: 39985
LastHeartBeat: 0
WorkerRef: null
[root@ip-xx-xx-xx-xx ~]# curl localhost:9096/shuffles
application_1661229435673_1827267-0
application_1661229435673_1827267-2
application_1661229435673_1827267-1
```
https://github.com/alibaba/RemoteShuffleService/issues/489
=> [ISSUE-489][FEATURE] Implement more info for master and worker

pom.xml
Recover maven property `rss.shuffle.manager`
It was removed in https://github.com/alibaba/RemoteShuffleService/pull/497, but `make-distribution.sh` depends on this property to find the client jar folder.
=> Recover maven property rss.shuffle.manager

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala
Added `releaseSlots` in `Worker.cleanup`
Slots should be released when workers cleaning expired shuffle, otherwise `WorkerInfo` will be incorrect.
assign @waitinfuture
=> [BUG]Fix slots release when cleanup expired shuffle

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala, common/src/test/scala/com/aliyun/emr/rss/common/meta/WorkerInfoSuite.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/StorageManager.scala
1. Worker would clean shuffle data before close if it doesn't enable `rss.worker.graceful.shutdown`
2. Modify RssConf.hdfsDir() logic
3. Modify a wrong unit test name
After adding clean logic
As mentioned in #498 ,  if we set `rss.disk.minimum.reserve.size` as a big value like 500GB, and shutdown the worker during handling shuffle without enabling `rss.worker.graceful.shutdown`, it will leave the shuffle data there. Let's assume the rest shuffle data is huge data and it make the free space be less than 500GB, then it would trigger the DeviceMonitor's check alert and put worker into blacklist when restart worker.
1. do we need to leave a time period which is in code to wait for worker to submit all delete file task into threadpool before threadpool shutdown? and do these 2 timeout's …
=> [ISSUE-498][FEATURE] Worker should clean shuffle data if not enable graceful shutdown

client-spark/shuffle-manager-2/pom.xml, client-spark/shuffle-manager-3/pom.xml, dev/make-distribution.sh, pom.xml, server-worker/pom.xml
Use different artifact names for shuffle manager 2/3
Duplicated module name may cause some issues for Maven command, e.g. 
```
build/mvn versions:set -DnewVersion=0.2.0-netease -DgenerateBackupPoms=false -Pspark-3.1
```
the bump version command does not work well before, but does after this change.
```
dev/make-distribution.sh -Pspark-2.4
```
```
dev/make-distribution.sh -Pspark-3.1
```
```
build/mvn versions:set -DnewVersion=0.2.0-netease -DgenerateBackupPoms=false -Pspark-3.1
```
=> Use different artifact name for shuffle manager 2/3

dev/make-distribution.sh
To suppress such warning when run `dev/make-distribution.sh`
```
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but this         *
[WARNING] * project contains the following plugin(s) that have goals not  *
[WARNING] * marked as thread-safe to support parallel execution.          *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against Apache Maven.                           *
[WARNING] …
```
=> [BUILD] Build in serial mode

common/src/main/java/com/aliyun/emr/rss/common/network/protocol/TransportMessage.java, common/src/main/java/com/aliyun/emr/rss/common/protocol/PartitionLocation.java, common/src/main/java/com/aliyun/emr/rss/common/protocol/StorageInfo.java, common/src/main/java/com/aliyun/emr/rss/common/util/PBSerDeUtils.java, common/src/main/proto/TransportMessages.proto, common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala, common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala, common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala
Generate TransportMessages.proto into multiple files instead of static inner classes in single outer class
=> Generate TransportMessages.proto into multiple files

docker/Dockerfile
To close #508 & #381
According to https://github.com/docker-library/openjdk/issues/505
/cc @pan3793 
=> [REFACTOR] Switch docker base image to Eclipse Temurin

server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/StorageManager.scala
```
22/09/09 13:01:50,532 ERROR [dispatcher-event-loop-19] LocalStorageManager: Create Writer failed, report to DeviceMonitor
java.io.IOException: Permission denied
at java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.io.File.createNewFile(File.java:1012)
at com.aliyun.emr.rss.service.deploy.worker.LocalStorageManager.createWriter(LocalStorageManager.scala:441)
at com.aliyun.emr.rss.service.deploy.worker.LocalStorageManager.createWriter(LocalStorageManager.scala:415)
at com.aliyun.emr.rss.service.deploy.worker.Worker.$anonfun$handleReserveSlots$3(Worker.scala:344)
at scala.runtime.java8.JFunction1$mcZI$sp.apply(JFunction1$mcZI$sp.java:23)
at scala.collection.immutable.Range.foreach(Range.scala:158)
at com.aliyun.emr.rss.service.deploy.worker.Worker.com$aliyun$emr$rss$serv …
```
=> [ISSUE-584][REFACTOR] Create FileWriter failed should show clear pathan mount point to help debug

client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Compressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Decompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Trait.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdCompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdDecompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdTrait.java
negative level will be transformed to a unique positive number, and add a default case for RssZstdDecompressor for better debug.
When zstd level is negative, it will compute a wrong token inside data head of buffer, because the negative number's complementary code(e.g: -1 is 1111 1111) can't meet the requirement that store the compressMethod and level info into one byte by bit operation. 
```
compressedBuffer[MAGIC_LENGTH] = (byte) (compressMethod | compressionLevel);
``` 
And when decompressor decompresses the data, it will get a wrong compress method from the wrong token, then it will skip the switch cases and directly using the given dst array to calculate the checksum, then finally get a wrong checksum.
```
switch (compressionMethod) {
case COMPRESSION_METHOD_RAW: …
```
=> [ISSUE-551][BUG] CompressionMethod and checksum are not consistent when zstd level is negative

client/pom.xml, client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Compressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Decompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssLz4Trait.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdCompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdDecompressor.java, client/src/main/java/com/aliyun/emr/rss/client/compress/RssZstdTrait.java, client/src/test/java/com/aliyun/emr/rss/client/compress/CodecSuite.java
Add independent unit test for lz4 and zstd codec
To prevent #551 by unit test rather than finding the problem when running real jobs on prod cluster.
Need to merge #577 first, then cherrypick it into current branch to fix the workflow which can't pass when zstd level is negative.
#578 
=> [ISSUE-578][FEATURE] Add unit test for codec

docker/Dockerfile
Use `xxx.tgz` in Dockerfile
`dev/make-distribution.sh` produces `xxx.tgz`, but `docker/Dockerfile` uses `xxx.tar.gz`
=> Correct binary tarball extension name in Dockerfile

client-spark/shuffle-manager-2/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java, client-spark/shuffle-manager-3/src/main/java/org/apache/spark/shuffle/rss/SortBasedShuffleWriter.java
Change log level
SortBasedShuffleWriter will print too many log when enable INFO level
#609 
=> [ISSUE-609][REFACTOR] Change SortBasedShuffleWriter push giant record log level

server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/storage/PartitionFilesSorter.java
Refactor the error log to use the format of print error trace since it's not convenient when use grep to check the error log
```
22/09/16 11:35:58,923 ERROR [worker-file-sorter-execute-360] PartitionFilesSorter: sort shuffle file 724-0-0 error
22/09/16 11:35:58,943 ERROR [fetch-server-11-23] PartitionFilesSorter: file application_1661230813707_5515788_1-31-724-0-0 sort failed
```
https://github.com/alibaba/RemoteShuffleService/issues/612
=> [ISSUE-612][Refactor] Refactor error log of PartitionFileSorter

common/src/main/scala/com/aliyun/emr/rss/common/meta/DeviceInfo.scala, server-worker/src/test/scala/com/aliyun/emr/rss/service/deploy/worker/storage/DeviceMonitorSuite.scala
If multiple directories are mounted to the same disk,the mounting information of the working directory may not be found .As a result,the npe occurs,causing DeviceMonitor  initialization failure.
=> DeviceMonitor init failed because of NPE.

client-spark/shuffle-manager-2/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala, client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleReader.scala
Create RssInputStreamImpl partition by partition to prevent multiple RssInputStreamImpl instances from being created at one time, resulting in overrun of off-heap memory usage
/cc @waitinfuture 
=> Make shuffle read consume less off-heap memory when CoalescePartition occurs

assets/grafana/rss-dashboard.json
For multiple Prometheus sources, the table does not display properly. The Datasource needs to be specified manually. Follow other indicators, modify the correlation.
For compatibility with Granfana 7.5.5
=> [IMPORVE] Fix grafana dashboard json `metrics_OfferSlotsTime_Max` & `metrics_OfferSlotsTime_Mean` target datasource

common/src/main/proto/TransportMessages.proto, common/src/main/scala/com/aliyun/emr/rss/common/protocol/message/ControlMessages.scala, common/src/main/scala/com/aliyun/emr/rss/common/util/Utils.scala, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala
This is an alternative of #674, in this approach, I keep the transparent transformation between TransportMessage and PbXXX, and we always use PbXXX the application layer.
If this approach is accepted, #674, #675, #676 should be reverted.
=> Drop control message Scala wrapper V2 - CheckForWorkerTimeOut

client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/ShuffleInMemorySorter.java, client-spark/shuffle-manager-common/src/main/java/org/apache/spark/shuffle/rss/SortBasedPusher.java
Backport from [SPARK-32901](https://jira.shopee.io/browse/SPARK-32901)
To fix the bug caused by allocateArray(0)
#691 
=> [ISSUE-691][BUG] SortBasedPusher pass 0 to allocateArray when calling growPointerArrayIfNecessary

common/src/main/scala/com/aliyun/emr/rss/common/meta/WorkerInfo.scala, server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/clustermeta/AbstractMetaManager.java, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/Worker.scala, server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/storage/StorageManager.scala
Worker collect user level resource usage
Because the StorageManager is limited to being called within the scope of worker, current implementation seems not feel elegant (storageManager calculate snapshot first, then update it into the workerInfo). 
#635 
=> [ISSUE-635][FEATURE] Worker collect user level resource usage

pom.xml
lz4 and zstd should respect Spark build-in versions
Since compression and decompression occurs on Spark side, and Celeborn does not ship lz4/zstd classes, we should always respect Spark build-in versions
=> [BUILD] lz4 and zstd should respect Spark build-in versions

docker/helm/templates/master-statefulset.yaml, docker/helm/templates/worker-statefulset.yaml, docker/helm/values.yaml
Common environment variables should be grouped together in values.yaml instead of scattered in each pod file, for easier modifications with user setting and devs improve.
Also, rename `RSS_NO_DAEMONIZE` to `CELEBORN_NO_DAEMONIZE `,  according to #724 
=> [K8S] Should move common env to values.yml instead of set in each yaml

client-spark/common/pom.xml, client-spark/spark-2/pom.xml, client-spark/spark-3/pom.xml, client/pom.xml, common/pom.xml, master/pom.xml, pom.xml, service/pom.xml, tests/spark-it/pom.xml, worker/pom.xml
Simplify the project version management, and it's easy to overwrite by changing one placing in the root pom.xml or `build/mvn deploy -Dproject.version=$RELEASE_VERSION`
I found that the usual way does not take effect, it may be caused by `flatten-maven-plugin`
`build/mvn versions:set -DnewVersion=$RELEASE_VERSION -DgenerateBackupPoms=false`
=> [BUILD] Extract project.version to Maven Property

common/src/main/java/org/apache/celeborn/common/util/PbSerDeUtils.java, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, common/src/test/scala/org/apache/celeborn/common/meta/WorkerInfoSuite.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, master/src/test/java/org/apache/celeborn/service/deploy/master/SlotsAllocatorSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Move userResourceConsumption to WorkerInfo's parameter and format WorkerInfo's toString()
Make its structure more reasonable, and reformat the string output to be more clear.
1. Has modified the `hashCode()` method of WorkerInfo, because it doesn't look quite right before.
2. Output of `WorkerInfo.toString` when diskInfos and userResourceConsumption are not empty
3. Output of `WorkerInfo.toString` when diskInfos and userResourceConsumption are empty
#751 
=> [ISSUE-751][REFACTOR] Move userResourceConsumption to WorkerInfo's parameter and format WorkerInfo's toString()

common/src/main/java/org/apache/celeborn/common/util/PbSerDeUtils.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Add cache to avoid redundant UserIdentifier object when recover fileinfo
avoid generate redundant UserIdentifier object when restore fileinfo with graceful shutdown.
#774 
=> [ISSUE-774][REFACTOR] Add cache to avoid redundant UserIdentifier object when recover fileinfo

common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala
WorkerInfos hashCode() should be consistent with equals()
Decrease the possibility of hash collision.
#773 
=> [ISSUE-773][BUG] WorkerInfos hashCode() should be consistent with equals()

common/src/main/scala/org/apache/celeborn/common/RssConf.scala, common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigBuilder.scala, common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala, common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, common/src/test/scala/org/apache/celeborn/ConfigurationSuite.scala, docs/configuration/client.md, docs/configuration/index.md, docs/configuration/master.md, docs/configuration/metrics.md, docs/configuration/worker.md, mkdocs.yml, requirements.txt
This PR introduces a test suite to generate markdown files for `ConfigEntry`s and treats `docs/configuration/*.md` as golden files.
The golden files can be generated by
```
UPDATE=1 build/mvn test -pl common -am -Pspark-3.3 -Dtest=none -DwildcardSuites=org.apache.celeborn.ConfigurationSuite
```
UT will fail if the contributor updated the configuration code but forgot to re-generate docs.
Site previews
Reduce configuration documentation maintenance effort, and keep the documentation consistent w/ code.
=> Auto generate configuration docs

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-2/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
Use rssConf instead of sparkConf to avoid unnecessary parsing to generate rssConf.
=> [MINOR] Use rssConf instead of sparkConf to avoid unnecessary parsing to generate rssConf.

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
Currently ReserveSlotsWithRetry will increase epoch, which means after RegisterShuffle the epoch may not all be zero. As a result, the follow-up registerShuffle might not return all registered PartitionLocations because it filters out partitions whose epoch not equal to zero.
```
val initialLocs = workerSnapshots(shuffleId)
.values()
.asScala
.flatMap(_.getAllMasterLocationsWithMinEpoch(shuffleId.toString).asScala)
.filter(_.getEpoch == 0)
.toArray
```
Then shuffle client will trigger revive
```
if (!map.containsKey(partitionId)
&& !revive(
applicationId,
shuffleId,
mapId,
attemptId,
partitionId,
0,
null,
StatusCode.PUSH_DATA_FAIL_NON_CRITICAL_CAUSE))
```
And eventually leads to lots of revive request in LifeCycleManager
```
22/10/22 20:22:46 WARN LifecycleManager: Do Revive for shuffle …
```
=> [BUG] RegisterShuffle should not increase epoch

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
33-478-1 create file twice
Worker
```
22/10/25 15:09:21,828 DEBUG [dispatcher-event-loop-14] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:09:21,828 INFO [dispatcher-event-loop-14] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]
22/10/25 15:25:27,728 DEBUG [dispatcher-event-loop-43] Worker: Received CommitFiles request, application_1665646136650_2510409_1-33, master files 64-1,833-0,1345-1,164-1,584-2,1161-1,1129-2,1131-0,237-0,818-1,819-1,1429-0,535-0,733-1,478-1; slave files …
```
=> [ISSUE-863][BUG]LifecycleManager should ignore change partition request when shuffle ended and not remove workersnapshot when commit success

docker/DEPLOY_ON_K8S.md, docker/Dockerfile
User can custom build tgz with their prefer name, old dockerfile need fixed name tgz to build docker image.
Theoretically, users should build custom images from binary rather than adding tgz directly.
Close #882 
=> [ISSUE-882][REFACTOR][K8S] Refactor dockerfile to build docker image from binary instead of ADD tgz

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
onTrim when flushFileWriters() should catch each file writer's exception, avoid block flush all file writers
To avoid some file writer's exception blocked all file writer's execution
#880 
=> [ISSUE-880][BUG] onTrim when flushFileWriters() should catch each file writer's exception, avoid block flush all file writers

worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceObserver.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Create writer failed should report non-critical error instead of critical error
To avoid the problem that execute createWriter() method twice will make all Flusher‘s thread stop and hang on the normal execution of worker.
Could we just ignore the request if we check that the target file of fileWriter already exists. And if there is other I/O issue when creating filewriter, we could handle it by previous way.
close #867 
=> [ISSUE-867][BUG] Create writer failed should report non-critical error instead of critical error

common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/metrics/source/RPCSource.scala, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/IMetadataHandler.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/SingleMasterMetaManager.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAMasterMetaManager.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MetaHandler.java, master/src/main/proto/Resource.proto, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
=> [ISSUE-901][BUG] During worker graceful shutdown, worker should report itself as unavailable and avoid master allocate slots on it.

master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterNode.scala
Fix MasterNode RPC endpoint info
```
2022-11-03 20:11:44 [WARN] [dispatcher-event-loop-4] org.apache.celeborn.common.haclient.RssHARetryClient#256 - Connect to celeborn-master-2.celeborn-master-svc.spark.svc.cluster.local:9872 failed.
org.apache.celeborn.common.rpc.RpcTimeoutException: Futures timed out after [30000 milliseconds]. This timeout is controlled by celeborn.rpc.lookupTimeout
at org.apache.celeborn.common.rpc.RpcTimeout.org$apache$celeborn$common$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:46) ~[celeborn-client-spark-3-shaded_2.12-0.2.0.4.jar:0.2.0.4]
at org.apache.celeborn.common.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:61) ~[celeborn-client-spark-3-shaded_2.12-0.2.0.4.jar:0.2.0.4]
at …
```
=> Fix MasterNode RPC endpoint info

worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
When trigger notifyError, StorageManager will destroy corresponding file writers
To destroy the related fileWriters when their related flusher(they bind with same mount) faces I/O Exception then trigger                     `processIOException(e, DiskStatus.READ_OR_WRITE_FAILURE)`
1. do we need to wait rest file workers to finish their work(like close()?) or just immediately destroy them because there is existed write error of disk
#879 
=> [ISSUE-879][BUG] When notifyError, should destroy corresponding file writers

client-spark/spark-3-shaded/pom.xml
Exclude unused files from Spark shaded client
We does not relocate and use proto files and native-image files, so just exclude them from the shaded jar.
=> Exclude unused files from Spark shaded client

common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, common/src/test/scala/org/apache/celeborn/common/util/PbSerDeUtilsTest.scala
Replace userResourceConsumption of WorkerInfo with empty value for unnecessary ControlMessages
Because in some rpc message the userResourceConsumption inside WorkerInfo is redundant, we won't use them in late logic, so we can replace it with empty map to reduce the RPC pressure.
Could we directly use null as the empty value instead of empty hashmap?
closed #948 
=> [ISSUE-948][REFACTOR] Replace userResourceConsumption of WorkerInfo with empty value for unnecessary ControlMessages

client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala
Add and modify warning log of fallback policy
applyForceFallbackPolicy() doesn't have log to notice user when enable, and if applyShufflePartitionsFallbackPolicy()'s log level is WARN could better catch the eyes.
New log's output would looks like
closed #958 
=> [ISSUE-958][REFACTOR] Add and modify log of fallback policy

dev/checkout_pr.sh
Assuming you name the upstream repo "apache", this shell script conveniently checkout GitHub PR to local w/ temporary branch `PR_<NUM>`
```
(celeborn) ➜  apache-celeborn git:(checkout-pr) git remote -v
apache  git@github.com:apache/incubator-celeborn.git (fetch)
apache  git@github.com:apache/incubator-celeborn.git (push)
origin  git@github.com:pan3793/RemoteShuffleService.git (fetch)
origin  git@github.com:pan3793/RemoteShuffleService.git (push)
```
Usages:
```
dev/checkout_pr.sh 1234
dev/checkout_pr.sh -f 1234
dev/checkout_pr.sh --force 1234
```
=> [INFRA] Inroduce checkout_pr.sh shell script

client/src/main/scala/com/aliyun/emr/rss/client/write/LifecycleManager.scala, common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/NettyRpcEnv.scala, common/src/main/scala/com/aliyun/emr/rss/common/rpc/netty/Outbox.scala
=> [ISSUE-228][BUG] When CommitFile, worker endpoint may be closed by ReserveSlots failed, we should try reconnect endpoint when endpoint not active

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
To support quick restart, during worker shutdown, return HARD_SPLIT for existed reserved partition
close #987
=> [ISSUE-987][FEATURE] During worker shutdown, return HARD_SPLIT for all existed partition

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/RequestLocationCallContext.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala
- implements registerMapPartitionTask rpc to supportr first map task and  later map attempt task at the same time
- rename handleChangePartitionLocation to handleRequestPartitionLocation, and extend the function to be able request new location resource for attempt task(at the register time)
=> [CELEBORN-14] [ISSUE-955] support register attempt map task

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
```
22/11/22 16:58:08,316 ERROR [push-server-6-14] TransportRequestHandler: [processPushMergedData] Process PushMergedData onFailure! ShuffleKey: application_1668568794504_1376477-0, partitionUniqueId: 1-0,4-0,7-0,10-0,13-0
java.lang.Exception: PushDataFailSlave
at com.aliyun.emr.rss.service.deploy.worker.Worker$$anon$8.onFailure(Worker.scala:834)
at com.aliyun.emr.rss.service.deploy.worker.Worker.$anonfun$handlePushMergedData$1(Worker.scala:862)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at …
```
=> [CELEBORN-42][BUG] PushMergedData use wrong call back when partition not found

master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/StateMachine.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java
Refresh snapshot cache when statemachine takes a new snapshot.
Currently, `getLatestSnapshot` only returns cached snapshot. However, when StateMachine takes a new snapshot, it will not update cache, so `getLatestSnapshot` cannot get the latest snapshot.
I add the update cache step in the last of `takeSnapshot`. 
Add new unit tests to verify.
=> [CELEBORN-44][BUG] StateMachine not update currentSnapshot after takeSnapshot cause getLatestSnapshot return null

client/src/main/java/org/apache/celeborn/client/read/Replica.java
=> [CELEBORN-50] Channel inActive may cause new client use old stream id to fetch data cause IllegalStateException.

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
Support LifeCycleManager to send destroy slots request in parallel
In order to reduce the time consumed by sending Destroy RPC one by one. Currently, LifeCycleManager needs to wait for Worker finish `handleDestroy` one by one. 
[CELEBORN-59](https://issues.apache.org/jira/browse/CELEBORN-59)
=> [CELEBORN-59][REFACTOR] Support send destroy slots request in parallel

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/java/org/apache/celeborn/common/protocol/message/StatusCode.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md, docs/configuration/worker.md, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/HugeDataTest.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RetryCommitFilesTest.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/RssSortSuite.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SparkTestBase.scala, worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/FileWriter.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/CommitInfo.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Add config in client side
```
spark.celeborn.test.retryCommitFiles=true
```
Optionally, can also add a config in worker side
```
celeborn.test.retryCommitFiles=true
```
We can see logs like
```
22/11/26 20:45:30 ERROR LifecycleManager: AskSync CommitFiles for 10 failed (attempt 2/3).
java.lang.Exception: Mock fail for CommitFiles
at org.apache.celeborn.client.LifecycleManager.requestCommitFilesWithRetry(LifecycleManager.scala:1653) ~[celeborn-client-spark-3-shaded_2.12-0.2.0-SNAPSHOT.jar:?]
at org.apache.celeborn.client.LifecycleManager.$anonfun$handleStageEnd$4(LifecycleManager.scala:997) ~[celeborn-client-spark-3-shaded_2.12-0.2.0-SNAPSHOT.jar:?]
at org.apache.celeborn.client.LifecycleManager.$anonfun$handleStageEnd$4$adapted(LifecycleManager.scala:971) …
```
=> [CELEBORN-12]Retry on CommitFile request

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
Aggregate reserve failed logs together
Avoid to print too many log when fail to reserve slots.
The log will looks like , there will be dot at the end of each error statement in real situation.
[CELEBORN-58](https://issues.apache.org/jira/browse/CELEBORN-58)
=> [CELEBORN-58][REFACTOR] Aggregate reserve failed logs together

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
1. Fix the wrong logic of check if shuffle is regsitered 
2. Add the same logic to pushMergedData about checking if a partition location has been hard split
=> [CELEBORN-70][FOLLOWUP] Add epoch for each commitFiles request. 

common/src/main/java/org/apache/celeborn/common/haclient/RssHARetryClient.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md, docs/configuration/network.md
Rename CLIENT_RPC_ASK_TIMEOUT to HA_CLIENT_RPC_ASK_TIMEOUT, and move its category from `client` module to `network` module.
Because current name is a bit easily confused with ShuffleClient related config, and its categories is `client`, but maybe `network` may better. 
`celeborn.client.maxRetries` also has same problem
/cc @pan3793 @AngersZhuuuu 
=> [CELEBORN-95][REFACTOR]Rename CLIENT_RPC_ASK_TIMEOUT to HA_CLIENT_RPC_ASK_TIMEOUT

master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/StateMachine.java
Meet such problem 
```
22/11/30 19:11:14,814 INFO [main] Dispatcher: Dispatcher numThreads: 64
22/11/30 19:11:14,842 INFO [main] TransportClientFactory: mode NIO threads 64
22/11/30 19:11:14,996 DEBUG [main] TransportServer: Shuffle server started on port: 9097
22/11/30 19:11:14,999 INFO [main] Utils: Successfully started service 'MasterSys' on port 9097.
22/11/30 19:11:15,108 INFO [main] RaftServer: raft.rpc.type = NETTY (custom)
22/11/30 19:11:15,215 INFO [main] NettyConfigKeys$Server: raft.netty.server.host = null (default)
22/11/30 19:11:15,217 INFO [main] NettyConfigKeys$Server: raft.netty.server.port = 9872 (custom)
22/11/30 19:11:15,219 INFO [main] DataStreamServerImpl: raft.datastream.type = DISABLED (default)
22/11/30 19:11:15,299 INFO [main] RaftServerConfigKeys: …
```
=> [CELEBORN-94][BUG] StateMachine should implement pause to change status

master/src/main/scala/org/apache/celeborn/service/deploy/master/MasterArguments.scala, master/src/test/scala/org/apache/celeborn/service/deploy/master/MasterArgumentsSuite.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerArguments.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/WorkerArgumentsSuite.scala
Host and port check will alway isn't null, due to default value.
Remove this un-reach code block to keep the code neat.
https://issues.apache.org/jira/projects/CELEBORN/issues/CELEBORN-98?filter=allissues
=> [CELEBORN-98][IMPROVEMENT] Remove unreachable code block in master/work arguments

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/network.md
GetReducerFileGroup should support separated timeout configuration
Because currently when requesting GetReducerFileGroup it will use default timeout of askSync which is same with the stageEnd timeout `PUSH_STAGE_END_TIMEOUT`, we need an independent config to control the timeout of GetReduceFileGroup request to ensure we can control it.
[CELEBORN-90](https://issues.apache.org/jira/browse/CELEBORN-90)
=> [CELEBORN-90][REFACTOR] GetReducerFileGroup should support separated timeout configuration

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/ShuffleClientHelper.scala, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/network.md
Revive/PartitionSplit should set separated timeout configuration
Because we need to ensure that Revive/PartitionSplit won't use same timeout with ReserveSlots to avoid the issue that once ReserveSlots timeout, Revive/PartitionSplit must timeout.
[CELEBORN-88](https://issues.apache.org/jira/browse/CELEBORN-88)
=> [CELEBORN-88][REFACTOR] Revive/PartitionSplit should set separated timeout configuration

common/src/main/java/org/apache/celeborn/common/meta/DiskStatus.java, common/src/main/scala/org/apache/celeborn/common/util/Utils.scala
Add new DiskStatus to represent critical error
To represent the critical error when DeviceMonitor collects a certain number of non-critical error.
[CELEBORN-109](https://issues.apache.org/jira/browse/CELEBORN-109)
=> [CELEBORN-109][FEATURE] Add new DiskStatus to represent critical error

pom.xml
Bump Log4j2 from 2.17.1 to 2.17.2
2.17.1 is a rushed version, and we'd better to use the latest patched version of 2.17
https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2
=> [CELEBORN-128] Bump Log4j2 to 2.17.2

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-2/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-3/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java, client/src/main/java/org/apache/celeborn/client/ShuffleClient.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/test/java/org/apache/celeborn/client/DummyShuffleClient.java, worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala
Remove interface `Cloneable` declaration from `ShuffleClient`, and minor code improvement.
ShuffleClient should not implement Cloneable, the original intention here is Closeable, but the close method throws IOException (which is a checked exception, so catch or throw is necessary), to make the code clean and simple, here just remove the implement Cloneable.
=> [CELEBORN-132] ShuffleClient should not implement Cloneable

master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/StateMachine.java
1. add a pre-check to reject obsolete snapshots
2. throw exception and fail immediately when snapshot is not loaded
Snapshot loading happens when:
1. A server restarts from crash.
2. A new Server joins the group.
In both situation, when snapshot loading is failed, the server is not able to service. We should throw exception and fails immediately.
=> [CELEBORN-133] Improve snapshot loading

common/src/main/scala/org/apache/celeborn/common/quota/DefaultQuotaManager.scala, common/src/test/resources/test-quota.yaml, common/src/test/scala/org/apache/celeborn/common/quota/DefaultQuotaManagerSuite.scala
Bytes's setting support such as `1m`. `1G`
=> [CELEBORN-140][IMPROVEMENT] Quota yaml should support byte string

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, docs/configuration/quota.md
Fix read wrong yaml file format when loading config
its file format should be yaml rather than yml when creating quota config file.
yes
=> [CELEBORN-139][BUG] Fix read wrong yaml file format when loading config

conf/quota.yaml.template
After #1085 , yaml file not support default quota value -1, if we don't want to set this quota, can just not set the value, default will be -1, means no limit.
Fix incorrect template quota.yaml
Yea, quota.yaml file setting should not use -1 to set default value.
=> [CELEBORN-140][FOLLOWUP] quota.yaml file not support default value -1 no2

client-spark/spark-2/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala, client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/RssShuffleFallbackPolicyRunner.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, common/src/main/scala/org/apache/celeborn/common/quota/Quota.scala, common/src/test/scala/org/apache/celeborn/common/quota/QuotaSuite.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
Add reason in CheckQuotaResponse return result and related unit test.
To be convenient to check which parts of consumption exceed quota  when shuffle fallback, and no need to check the server log for details each time when excessive quota happens.
no
Add unit test to check if quota can return correct result.
=> [CELEBORN-145][REFACTOR] Add reason in CheckQuotaResponse

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/worker.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
1. Notify critical error after collecting a certain number of non-critical error.
2. Set an expire time for non-critical error, only when non-critical errors concentrated at a certain time period then will notify critical error. For occasional errors, we don't hope its accumulation affect the jobs execution.
3. Remove reportDeviceError() from DeviceMonitor and related unit tests, because we don't allow code to directly notify critical error anymore.
4. DiskStatus may become back healthy if accumulated errors expires and their sum is less than threshold.
Because we want that only when a certain number of non-critical error is detected the device monitor will notify error instead of the occasional error. To reduce the impact of  occasional device errors when job runs. …
=> [CELEBORN-110][REFACTOR] Notify critical error after collecting a certain number of non-critical error

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/CommitManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala
This is the second refactor step according to [CELEBORN-116](https://issues.apache.org/jira/browse/CELEBORN-116), follow up [CELEBORN-117](https://issues.apache.org/jira/browse/CELEBORN-117)
It's about refactor batchHandleCommitPartition, as we can use specific commit handler for the R/M shuffle type.
Use specific commit handler  to do batchHandleCommitPartition for the R/M shuffle type,  will make the whole logic clearer and the code cleaner.
No
trigger test
=> [CELEBORN-121] Refactor batchHandleCommitPartition

docker/DEPLOY_ON_K8S.md, docker/Dockerfile, docker/helm/templates/configmap.yaml, docker/helm/templates/master-statefulset.yaml, docker/helm/templates/worker-statefulset.yaml, docker/helm/values.yaml
- new args `celeborn_uid` and `celeborn_gid` for `Dockerfile`
- add `busybox` to docker image
- updated outdated configurations for helm charts
For security, we should avoid using `root` to run image.
No, it's not officially released
Run `helm templates celeborn docker/helm`
=> [CELEBORN-151][K8S] Celeborn should run as celeborn instead of root in container

common/src/test/java/org/apache/celeborn/common/meta/DiskStatusSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
Add metrics to monitor non-critical error number on local device. The metrics will looks like below
In order to better add metrics to trace the current valid non-critical error number(differentiate based on DiskStatus) when local device has issue.
no
unit test
=> [CELEBORN-113][FEATURE] Add metrics to monitor non-critical error number on local device

common/src/main/scala/com/aliyun/emr/rss/common/RssConf.scala, server-master/src/main/java/com/aliyun/emr/rss/service/deploy/master/MasterUtil.java, server-master/src/main/scala/com/aliyun/emr/rss/service/deploy/master/Master.scala, server-master/src/test/java/com/aliyun/emr/rss/service/deploy/master/MasterUtilSuiteJ.java
Optimize the master offerSlots algorithm, such as the maximum/minimum number of workers, etc.; 
If it fails, the original algorithm will be rolled back 
the original algorithm will choose too many workers if the cluster is big
MasterUtilSuiteJ.java
testAllocateSlotsForOrderByFreeSlots
testAllocateSlotsByReduceIdsWithReplicate
testAllocateSlotsByReduceIdsWithoutReplicate
=> [CELEBORN-152] [0.1] limit the max workers while offerSlots

pom.xml
Disable `attach-scaladocs`.
To recover the following building command
```
build/mvn clean install -DskipTests -Pspark-2.4
```
No.
Run `build/mvn clean install -DskipTests -Pspark-2.4`.
Before
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Celeborn Project Parent POM 0.2.0-SNAPSHOT:
[INFO]
[INFO] Celeborn Project Parent POM ........................ SUCCESS [  4.156 s]
[INFO] Celeborn Common .................................... FAILURE [ 32.095 s]
[INFO] Celeborn Client .................................... SKIPPED
[INFO] Celeborn Service ................................... SKIPPED
[INFO] Celeborn Master .................................... SKIPPED
[INFO] Celeborn Worker .................................... SKIPPED
[INFO] …
```
=> [CELEBORN-161][BUILD] Disable scaladocs

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
Fix wrong conf mapping of  `celeborn.worker.flusher.ssd.threads`
Fix bug
No
Not need
=> [CELEBORN-176][BUG] Fix wrong alternative conf of celeborn.worker.flusher.ssd.threads

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
1. If the worker side doesn't enable rate limit, the client side maxReqs value will always increase. So here add a new param to control this behavior.
2. Fix the concurrent issue of currentMaxReqsInFlight(it could be accessed(limitMaxInFlight) when is modified by other threads(slowStart and congestionControl))
=> [CELEBORN-61][CELEBORN-62][FOLLOW_UP] Fix some issues for slow start

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
When restart worker, throw NPE, caused by default registered flag is null before attach value
```
22/12/29 13:28:06,355 WARN [push-server-6-43] TransportChannelHandler: Exception in connection from /10.169.41.1:29528
at org.apache.celeborn.service.deploy.worker.PushDataHandler.checkRegistered(PushDataHandler.scala:509)
at org.apache.celeborn.common.network.server.TransportRequestHandler.checkRegistered(TransportRequestHandler.java:82)
at org.apache.celeborn.common.network.server.TransportRequestHandler.handle(TransportRequestHandler.java:76)
at org.apache.celeborn.common.network.server.TransportChannelHandler.channelRead(TransportChannelHandler.java:117)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379 …
```
=> [CELEBORN-178][BUG] Default registered flag should be false, not null

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Repeat remove expired shuffle throw NPE
```
22/12/29 12:54:06,145 INFO [Cleaner] Worker: Cleaned up expired shuffle application_1670989463623_3306414-0
22/12/29 12:54:06,146 INFO [Cleaner] StorageManager: Cleanup expired shuffle application_1670989463623_3306414-0.
22/12/29 12:54:06,152 INFO [Cleaner] Worker: Cleaned up expired shuffle application_1670989463623_3306414-0
22/12/29 12:54:06,152 INFO [Cleaner] StorageManager: Cleanup expired shuffle application_1670989463623_3306414-0.
22/12/29 12:54:06,153 DEBUG [Disk-cleaner-/mnt/disk/0-0] StorageManager: Deleted expired shuffle file /mnt/disk/0/hadoop/rss-worker/shuffle_data/application_1670989463623_3306414/0.
22/12/29 12:54:06,153 ERROR [Cleaner] Worker: Cleanup failed
at …
```
=> [CELEBORN-179][BUG] Repeat remove expired shuffle throw NPE

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
StorageManager should not delete shuffle file when enable graceful shutdown
=> [CELEBORN-182][BUG] StorageManager should not delete shuffle file when enable graceful shutdown

client/src/main/scala/org/apache/celeborn/client/CommitManager.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala
This is the third refactor step according to [CELEBORN-116](https://issues.apache.org/jira/browse/CELEBORN-116).
In this patch we move shuffleMapperAttempts and getReducerFileGroup to CommitManager.
MapperAttemptsFinished process and final valid file groups are strongly related to commit，So move them to CommitManager.
=> [CELEBORN-146] refactor ShuffleMapperAttempts & GetReducerFileGroup

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
add shuffle id to sortShuffleIds while getWriter if rss fallback to native shuffle service
if rss fallback to native shuffle service, RssShuffleManager.unregisterShuffle won't call SortShuffleManager to release shuffle data on executor size
=> [CELEBORN-185][SPARK] Can't release shuffle data if rss fallback to nss

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
When ShuffleClient print put why registerShuffle failed, miss RESERVE_SLOTS_FAILED
=> [CELEBORN-191][BUG] ShuffleClient registerShuffle return RESERVE_SLOTS_FAILED should also been print out

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
Add disk usage related metrics for Worker.
BTW, shall we modify the PromServlet to support add customized label for Prom metrics, such as `device_type` or `mount_point` for disk related metrics?
And do we need to add metrics to monitor the hdfs capacity usage of each Worker, not sure if it is necessary.
Better display current OS device's (not disk's) capacity of each Worker on monitor.
No
UTs
cc: @AngersZhuuuu
=> [CELEBORN-168][FEATURE] Add disk usage related metrics for Worker

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
Device metrics should use long value and add size unit in metric name
=> [CELEBORN-168][FOLLOWUP] Device metrics should use long value and add size unit in metric name

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
In our cluster, we meet a case that some worker is stuck, but if it's a slave partition, celeborn won't add it to blacklist, when revive, it may be offered as another partition, cause push data stuck again.
But for some small cluster, this policy is too strict, so I add a configuration to control if we should add peer partition into blacklist.
=> [CELEBORN-189][IMPROVEMENT] PushDataFailedSlave should add slave worker to blacklist

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/ShuffleTaskInfo.scala, client/src/test/scala/org/apache/celeborn/client/ShuffleTaskInfoSuite.scala
as title
if lifecycleManager doesn't encode shuffle task, then there is no shuffle taskInfo
NO
ut
=> [CELEBORN-203] Fix NPE when removeExpiredShuffle in LifecycleManager.

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitor.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
Collect disk usage info in byte unit by default for disk usage metrics and check high disk usage risk in LocalDeviceMonitor.
Currently LocalDeviceMonitor use df -B 1G to collect disk usage metrics, which returns the usage as GiB. It will lose some precision because of rounding if user wanna get the exact consumed bytes and user can build more flexible monitor if it return as byte by default.
`df -B1 ` Will looks like 
Metrics name change
UT
=> [CELEBORN-204][IMPROVEMENT] Collect disk usage info in byte unit by default

pom.xml
As title.
For dynamic artifactId(with scala-binary-version), IDE support is not very friendly，for Flink current default version(2.11), It would still use 2.12 for other module, then we can't find the correct module dependencies, so we need align to 2.12. When Flink becomes ready for release we should document this.
No
Manual test
=> [CELEBORN-208][IMPROVEMENT] Make flink default scala version to 2.12.

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/worker.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Push/Replicate/Fetch io threads should be decoupled from number of WORKER_STORAGE_DIRS
`celeborn.worker.push.io.threads`
`celeborn.worker.fetch.io.threads`
`celeborn.worker.replicate.io.threads`
default value is 16
=> [CELEBORN-214] Push/Replicate/Fetch io threads should be decoupled from number of WORKER_STORAGE_DIRS

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
As title.
CloseIdleConnections is hard-coded to true when new TransportContext in ShuffleClientImpl , It would be better to support configuration to control this behavior as needed.
No
Manual.
=> [CELEBORN-213]  Add  configuration for whether to close idle connections in client side

client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java, common/src/main/java/org/apache/celeborn/common/util/ExceptionUtils.java
Refresh client when WorkerPartitionReader fetches trunks.
After WorkerPartitionReader fetches trunks normally, transportClient would be inactive If the reader takes too long to process the results between two fetch trunks request(such as exceeds 240s as channel will be idle and timeout to close), when the reader tries to fetches the next trunk use the inactive transportClient, netty channel StacklessClosedChannelException will be raised up. So here need refresh client when fetch trunks. 
No
UT
=> [CELEBORN-212] Refresh client if current client is inactive for WorkerPartitionReader

worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java, worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriterSuiteJ.java
Currently, MapPartitionFileWriter's logic is not completable。
Now, this pr compeletes core logic such as close/regionFinish.
In regionFinish method, the important logic is to flush region's index file.
@waitinfuture @RexXiong @FMX
=> [CELEBORN-195][Flink] MapPartitionFileWriter improves logic about flushing region index file

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
… while sending messages
Currently, While Sending MapPartitiion's Message like PushData/HandShake/RegionStart/RegionFinish, transportClient is got from clientPool which may create new transportClient.
In MapPartition, the key important thing is to keep the data orderly. 
so if new transportClient is created, it should wait that old transportClient has sent out all the messages before sending message by current transportClient.
@waitinfuture @FMX @RexXiong
=> [CELEBORN-197][Flink] In mappartition new client should wait until old client has sent out all the messages

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/worker.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Now the default number of pushServer/replicateServer/fetchServer is `storageManager.disksSnapshot().size * 2`. If the worker's pressure is very high, the client's fetch block time will be very bad, increase the number of these server may has better performance.
=> [CELEBORN-223] The default rpc thread num of pushServer/replicateServer/fetchServer should be the number of total of Flusher's thread

client-spark/common/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedPusher.java, client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client/src/main/java/org/apache/celeborn/client/write/DataPusher.java, client/src/main/java/org/apache/celeborn/client/write/InFlightRequestTracker.java, client/src/main/java/org/apache/celeborn/client/write/PushState.java, common/src/main/java/org/apache/celeborn/common/protocol/PartitionLocation.java, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/HugeDataTest.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushdataTimeoutTest.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/SkewJoinSuite.scala
This is a follow-up of [CELEBORN-55](https://github.com/apache/incubator-celeborn/pull/1102) , which has some code refinement.
1. make _hostPushPort a transient member of PartitionLocation
2. remove the configuration spark.celeborn.shuffle.register.maxRetries in HugeDataTest, PushdataTimeoutTest, SkewJoinSuite
3. start dataPusher after construction
=> [CELEBORN-55][FOLLOWUP] Code refine

common/src/main/scala/org/apache/celeborn/common/metrics/MetricLabels.scala, common/src/main/scala/org/apache/celeborn/common/metrics/source/AbstractSource.scala, common/src/test/scala/org/apache/celeborn/common/metrics/source/CelebornSourceSuite.scala
Modify API to ensure they can find metrics with labels.
After supporting metrics with customized label, there will be some scenario that metrics has same name but their labels are different(such as user consumed quota), currently when storing NamedTimer, NamedCounter and NamedHistogram(not implemented yet) Celeborn only use metric name to deduplicate, we should keep the uniqueness of named  metrics based on both metrics name and label.
no
ut
=> [CELEBORN-229][FOLLOWUP] Support collect metrics with customized labels

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
Currently push data failed only show failed reason, but don't have partition info. In this pr, we enable push failed error message both show the error type and show the partition location.
=> [CELEBORN-237][IMPROVEMENT] push failed error message should show partition info

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
PUSH_LIMIT_IN_FLIGHT_TIMEOUT must > PUSH_DATATIMEOUT
=> [CELEBORN-241][IMPROVEMENT] limit inflight push timeout should >  push data timeout

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/test/scala/org/apache/celeborn/common/CelebornConfSuite.scala
`haMasterNodeIds` could resolve the `celeborn.ha.master.node.id` if we set it,
```java
assertion failed: id does not contain .
java.lang.AssertionError: assertion failed: id does not contain .
at scala.Predef$.assert(Predef.scala:223)
at org.apache.celeborn.common.CelebornConf.extractPrefix$1(CelebornConf.scala:570)
at org.apache.celeborn.common.CelebornConf.$anonfun$haMasterNodeIds$3(CelebornConf.scala:577)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at scala.collection.TraversableLike.map(TraversableLike.scala:238)
at …
```
=> [CELEBORN-253][MINOR] Fix the wrongly resolve celeborn.ha.master.node.id issue if enable HA

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala, client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala, common/src/main/scala/org/apache/celeborn/common/meta/WorkerPartitionLocationInfo.scala, common/src/main/scala/org/apache/celeborn/common/util/CollectionUtils.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
as title
PartitionLocationInfo in LifecycleManager is related to specific app shuffle but related to all app shuffle in worker. Seems It would be better to separate.
No
ut & ft
=> [CELEBORN-201] Separate partitionLocationInfo in LifecycleManager and worker

pom.xml
Auto activate `jdk-8` maven profile when using JDK 8.
The `jdk-*` profile should be activate based on the JDK version automatically.
No.
Pass CI.
=> [CELEBORN-171][FOLLOWUP] Auto activate jdk-8 profile

common/src/main/java/org/apache/celeborn/common/network/client/TransportClient.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportResponseHandler.java, common/src/test/java/org/apache/celeborn/common/network/TransportResponseHandlerSuiteJ.java
Separate outstandingPushes from outstandingRpcs so that we can timeout PushData requests in both client side and worker side.
=> [CELEBORN-244][IMPROVEMENT] Separate outstandingPushes from outstandingRpcs

sbin/restart-worker.sh
`sbin/restart-worker.sh` should respect `CELEBORN_WORKER_OFFHEAP_MEMORY` and `CELEBORN_WORKER_MEMORY`
If we restart the worker using `sbin/restart-worker.sh`, `CELEBORN_WORKER_OFFHEAP_MEMORY` and `CELEBORN_WORKER_MEMORY` will not take effect, this pr fixes this.
Yes, bug fix.
MT.
=> [CELEBORN-258] `sbin/restart-worker.sh` should respect CELEBORN_WORKER_MEMORY and CELEBORN_WORKER_OFFHEAP_MEMORY

sbin/restart-worker.sh
Follow up the pr #1192 to read the `sbin/celeborn-config.sh` firstly, otherwise `CELEBORN_WORKER_MEMORY` and `CELEBORN_WORKER_OFFHEAP_MEMORY ` set in the `celeborn-env.sh` will not take effect 
If users set `CELEBORN_WORKER_MEMORY` and `CELEBORN_WORKER_OFFHEAP_MEMORY ` in the `celeborn-env.sh`, calling `sbin/restart-worker.sh` actually omit these settings.
No
MT.
=> [CELEBORN-258][FOLLOW UP] `sbin/restart-worker.sh` should also import the `sbin/celeborn-config.sh`

client/src/main/java/org/apache/celeborn/client/write/InFlightRequestTracker.java
Give inFlightRequest's `pushTime` an initial negative value, and `InFlightRequestsTracker` will only expire requests if it's `pushTime` is not negative
`ShuffleClientImpl` first add batch to the `pushState`, and `pushTime` is assigned value in `pushState.pushStarted`, which is after the method `pushState.addBatch`, so it's possible to wrongly throw the exception `PushDataTimeout`.
For example,
1. pushState add batch 1, whose `pushTime` is initialized by 0 (Long)
2. Another push request calls `limitMaxInFlight` to check the limit, and batch 1 will be expired (since currentTime - 0 usually is larger than pushTimeoutMs)
No
MT. After add the patch, the issue doesn't occur anymore.
=> [CELEBORN-264] InFlight requests should not be expired if it's not pushed yet

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/WorkerSuite.scala
StorageManager.workingDirWriters doesn't cleanup expired filewriter, so that it will exceed disk capacity by summing all the history filelength. 
In woker's log , we will see the error log as follows:
WARN [device-check-thread-36004] DeviceMonitor: /mnt/disk1 usage is above threshold. Disk usage(Report by OS):{total:1759 GB, free:1647 GB, used_percent:2%} usage(Report by Celeborn):{total:1669.4 GB free:-16921305251.0 B }
ERROR [worker-disk-checker] LocalDeviceMonitor: /mnt/disk1 high_disk_usage error, notify observers
@RexXiong @waitinfuture @FMX
=> [CELEBORN-243] fix bug that os's disk usage is low but celeborn thinks that it's high_disk_usage

client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/ShuffleFallbackSuite.scala
```
Driver stacktrace:
at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGSchedule …
```
=> [CELEBORN-265] Integration with Spark3.0 cast class exception of ShuffleHandler

common/src/main/java/org/apache/celeborn/common/network/server/ChunkStreamManager.java, common/src/test/java/org/apache/celeborn/common/network/server/ChunkStreamManagerSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Reuse the stream when channel inactive while fetching trunk.
Stream will be removed when channel inactive while fetching trunk, so even if the client is reconnected, fetch trunk would not success and then client will retry other peer reader for same partition location. We can reuse the stream when client is reconnected to avoid this.
No
random kill workers & worker high-pressure test
=> [CELEBORN-267] reuse stream when client channel reconnected

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
Don't do replication should directly use callback not wrappedCallback
=> [CELEBORN-272][BUG] Non-replication should use callback instead of wrappedCallback

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
Fix NPE of 
```
[INFO] Running com.aliyun.emr.rss.service.deploy.integration.HugeDataTest
23/02/06 06:35:26,272 ERROR [dispatcher-event-loop-2] Inbox: Ignoring error
at com.aliyun.emr.rss.service.deploy.master.Master.computeUserResourceConsumption(Master.scala:482)
at com.aliyun.emr.rss.service.deploy.master.Master.com$aliyun$emr$rss$service$deploy$master$Master$$handleCheckQuota(Master.scala:507)
at com.aliyun.emr.rss.service.deploy.master.Master$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$24(Master.scala:229)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at com.aliyun.emr.rss.service.deploy.master.Master.executeWithLeaderChecker(Master.scala:163)
at com.aliyun.emr.rss.service.deploy.master.Master$$anonfun$receiveAndReply$1.ap …
```
=> [CELEBORN-247][FOLLOWUP] Fix NPE issue

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
1. Move `WrappedCallback` in the `doReplicate` block
2. Remove unnecessary check in the wrappedCallback
3. Currently slave push data timer metric is not well calculated, need to fix it
Clean the codes and fix the bug of calculating slave push data timer
no
MT. and existing UT.
=> [CELEBORN-275] WrappedCallback should only handle response from replica

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/PushDataTimeoutTest.scala
PUSH_DATA_TIMEOUT_MASTER/SLAVE should support convert through  RPC， without this LifecycleManager side will revive null status code, now is 
```
Received Revive request, local-1675825716934, 0, 3, 0, ,1, 0, PartitionLocation[
id(rawId-attemptId)-epoch:1(1-0)-0
host-rpcPort-pushPort-fetchPort-replicatePort:10.53.37.111-53650-53651-53653-53652
mode:MASTER
peer:(empty)
storage hint:StorageInfo{type=MEMORY, mountPoint='/', finalResult=false, filePath=}
mapIdBitMap:null], StatusCode{value=PUSH_DATA_TIMEOUT_MASTER}.
Received Revive request, local-1675825729662, 0, 2, 0, ,0, 0, PartitionLocation[
id(rawId-attemptId)-epoch:0(0-0)-0
host-rpcPort-pushPort-fetchPort-replicatePort:10.53.37.111-53650-53651-53653-53652
mode:MASTER
peer:(host-rpcPort-pushPort-fetchPort-replicatePort:10.53.37.111-53654-53 …
```
=> [CELEBORN-239][FOLLOWUP] PUSH_DATA_TIMEOUT_MASTER/SLAVE should support convert through  RPC

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
If a master is not a leader, it won't try to update the partition size.
To reduce log size.
NO.
UT.
=> [CELEBORN-300] fix a bug about non-leader master try to update partition size.

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala
1. for map partition, correct the right partitionId would be committed.
2. for map partition, correct the final result in finishMapperAttempt. 
Use wrong partitionId and result will cause shuffle data lost in next stage. And because of the above two interrelated issues, the test just passed.
no
UT
=> [CELEBORN-296] fix map partition commit using wrong partitionId and result

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
Change the parameter passed in the registerShuffle method to numPartitions instead of numMappers
ShuffleClientImpl's registerShuffle method should pass numPartitions instead of numMappers
NO
=> [CELEBORN-305] Change the parameter passed in the registerShuffle method to numPartitions instead of numMappers

worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala
pushmergedata  chooses a random TransportClient ,but pushdata only choose a specfic TransportClient. 
the defaut value of celeborn.data.io.numConnectionsPerPeer is 2, so the client maybe different between pushdata and  pushmergedata.
Two TransportClient means two threads to send message and worker server will has two threads to flush data, so the data in the file maybe unorder. lastly, Assert.assertArrayEquals(targetArr, readBytes) will occur error because the data is unorder.
so set celeborn.data.io.numConnectionsPerPeer to 1 to slove the problem above
=> [CELEBORN-307] fix ArrayComparisonFailure while running lz4 ut

common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala
Export usage about buffer stream's read buffer.
Export buffer stream memory data to Prometheus.
NO
=> [CELEBORN-281] Add metrics about buffer stream's read buffer.

client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala
With this patch celeborn lifecycleManager don't cache file groups for map partition shuffle type. But would do best effort cache at client-side if map partition already finished, this will be done in following pr.
Only Reduce partition mode supports cache all file groups for reducer. Map partition doesn't guarantee that all partitions are complete by the time the method is called, as downstream tasks may start early before all tasks are completed.So map partition may need refresh reducer file group if needed.
No
UT
=> [CELEBORN-297] don't cache file groups for map partition shuffle type

common/src/main/java/org/apache/celeborn/common/meta/FileInfo.java, common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriter.java, worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriterSuiteJ.java
add logs
modify flushindex from async to sync
modify reading header from platform method to bytebuf read
=> [CELEBORN-292] optimize mappartitionfilewriter flushing index and reading data header

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java, client/src/main/java/org/apache/celeborn/client/ShuffleClient.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/test/java/org/apache/celeborn/client/DummyShuffleClient.java, client/src/test/java/org/apache/celeborn/client/ShuffleClientImplSuiteJ.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportClient.java
…appartition
optimize  currentClient to concurrentmap to avoid that different maptask use the same currentclient
the first int of data header in mappartition should be partitionid(subpartitionid) rather than mappid
closefunction is called while successfullly writeandflush insteading of get successfull response
=> [CELEBORN-291] optimize shuffleclientimpl creating client and pushdata for mappartition

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala
If a flush task fails, the flusher should not stop. If a flusher stopped, related file writers would be left with unflushed data in memory and the worker will be stuck because of high memory usage or commit files failed.
To make sure that workers with unstable disks can work well.
NO.
UT and cluster.
=> [CELEBORN-308] Fix flusher will exit unexpectedly if flush task write failed.

common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
The worker's list might add two identical workers if the masters failed to connect to the worker while setting up the endpoint.
Change the worker's list to set to remove redundant workers.
NO.
UT.
=> [CELEBORN-302] Fix workers count out of sync in HA mode.

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java, client/src/main/java/org/apache/celeborn/client/ShuffleClient.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala
not retry when register occurs exception and response original status to client
1. No need for another retry when register shuffle for map partition occurs exception.
2.Retry will cause lose original response message, and it is impossible to succeed.
NO
UT
=> [CELEBORN-311] not retry when register for map partition occurs exception 

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/FlinkTransportClientFactory.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
Do not reuse the transport client in flink plugin.
1. Flink channels have different buffer suppliers so we can not reuse transport clients.
2. Readdata message needs to copy out from the netty stack to the flink memory stack.
NO.
UT.
=> [CELEBORN-319][FLINK] FlinkTransportClient should not reuse connection.

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/protocol/ReadData.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
Copyout ReadData only.
This is used in the flink plugin to make sure that buffer won't be exhausted unexpectedly.
NO.
UT
=> [CELEBORN-322][Flink] Copy out message if it‘s readData only.

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java
…all readers in multiple threads
add synchronized on readBuffers
recycle buffer will call readers in multiple threads
NO
manual test
=> [CELEBORN-323] [FLINK] readBuffers of BufferStreamManager need synchronized

client/src/main/java/org/apache/celeborn/client/write/DataPushQueue.java
ShuffleClientI side log when register shuffle failed
```
23/02/21 12:07:41 WARN ShuffleClientImpl: LifecycleManager request slots return StatusCode{value=ReserveSlotFailed}, retry again, remain retry times 2
23/02/21 12:07:44 WARN ShuffleClientImpl: LifecycleManager request slots return StatusCode{value=ReserveSlotFailed}, retry again, remain retry times 1
23/02/21 12:07:48 WARN ShuffleClientImpl: LifecycleManager request slots return StatusCode{value=ReserveSlotFailed}, retry again, remain retry times 0
23/02/21 12:07:51 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[DataPusher-458,5,main]
at com.aliyun.emr.rss.client.write.DataPushQueue.takePushTask(DataPushQueue.java:97)
at …
```
=> [CELEBORN-321] When register shuffle failed, DataPushQueue should directly take the task queue to avoid NPE

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
```
23/02/22 12:11:57,048 ERROR [push-server-6-8] TransportRequestHandler: Error while invoking RpcHandler#receive() on PushMergedData PushMergedData{requestId=7305, mode=0, shuffleKey=application_1676010707928_2449604-0, partitionIds=[188-0, 191-0, 194-0, 197-0], batchOffsets=[0, 3720, 7800, 11991], body size=15979}
at com.aliyun.emr.rss.service.deploy.worker.Worker.$anonfun$handlePushMergedData$2(Worker.scala:984)
at com.aliyun.emr.rss.service.deploy.worker.Worker.$anonfun$handlePushMergedData$2$adapted(Worker.scala:960)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at …
```
=> [CELEBORN-325] After worker restart, throw NPE when receive not found partition

client-flink/flink-1.14/pom.xml, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/FlinkResultPartitionInfo.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleDescriptor.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGate.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleResource.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/utils/FlinkUtils.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleMasterTest.java, client-flink/flink-1.14/src/test/resources/log4j2-test.xml, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
…n mode to handle multiple Flink jobs
lifecycleManager in FlinkJobMaster supports flink-yarn-session mode to handle multiple Flink jobs
As yarn session mode, jobManager and taskManagers will share across multiple jobs, if we use one lifecycleManager perJob, that will cause two major problem
1. (map)ShuffleClientImpl can not reuse  in taskManager 
2. multiple jobs register will use many connection and port that will consume lots of system resource.
No
UT/Manual Test
=> [CELEBORN-326)] [Flink] lifecycleManager supports flink-yarn-session mode to handle multiple Flink jobs.

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java
To make sure that writeAndFlush operation is done out of Netty worker threads.
WriterAndFlush operation executed in Netty worker thread is different from non-netty threads.
NO.
UT.
=> [CELEBORN-327][Flink] BufferStreamMananger should recycle buffer in reader thread.

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java, client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java, client/src/main/java/org/apache/celeborn/client/write/DataPusher.java, common/src/main/java/org/apache/celeborn/common/util/ExceptionUtils.java, common/src/main/java/org/apache/celeborn/common/write/InFlightRequestTracker.java, common/src/main/java/org/apache/celeborn/common/write/SlowStartPushStrategy.java, common/src/main/scala/org/apache/celeborn/common/exception/CelebornIOException.scala
When we enable spark blacklist mechanism, many executor was excluded from current stage caused by RSS exception, but for all RSS exception we should not been excluded and this mechanism caused less and less executor to return the task, caused job slower. 
We should wrap RSS exception with CelebonrIOException then we can do something in spark side
=> [CELEBORN-316] Wrap Celeborn exception with CelebornIOException

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
```
23/02/22 16:38:47 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:47 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:47 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:47 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:48 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:49 ERROR LifecycleManager: OfferSlots for 0 failed!
23/02/22 16:38:49 ERROR LifecycleManager: OfferSlots for 0 …
```
=> [CELEBORN-328][MPROVEMENT] Too much noisy log when reserve slot failed

client/src/main/java/org/apache/celeborn/client/write/DataPusher.java
Should not wrap CelebornIOException with CelebornIOException
=> [CELEBORN-316][FOLLOWUP] Should not wrap CelebornIOException with CelebornIOException

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
Do two thing in this pr:
1. Change callback to wrappedCallback here since here pass the wrappedCallBack
2. submitRetryPushData should throw PUSH_DATA_CREATE_CONNECTION_FAIL_MASTER too
=> [CELEBORN-331] submitRetryPushData should throw PUSH_DATA_CREATE_CONNECTION_FAIL_MASTER too

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java, common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
…e data while other thread wait the response
No need wait the open stream rpc response, just use async way and celeborn server need guarantee response the streamId before send back backlog/data in the same channel.
stream will opened when Flink streamTask processInput and  this operation(open stream) will hold the object lock inputGatesWithData(for all inputGates),  but at the same time the same channel which wait this open stream response possibly received other inputGate data and also need inputGatesWithData(for all inputGates) lock. That's how the deadlock happened.
No
TPCDS
=> [CELEBORN-330] [Flink] fix pollNext deadlock when process data recevied while open stream

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java
…losed.
bypass backlog message if stream reader already closed
if stream reader already closed, stream handler will be removed from ReadClientHandler. But backlog message would still can received from server, this will cause consumer of the handler NPE and then the channel will be closed.
NO
UT & manual test
=> [CELEBORN-333] [Flink]bypass unexpected backlog message when stream already closed

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
Current log in `ShuffleClientImpl` have below problem:
1. Use `logger.error` but can't show error stack
2. Different format of log
3. Wrong log level of error type log
In this pr, I prefer to unify the log format
=> [CELEBORN-332] Unify the log of ShuffleClientImpl

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java
1. Ignore backlog in ReadData structure.
It will reserve backlog repeatedly if not ignore the backlog.
NO.
UT and Cluster Test.
=> [CELEBORN-339][Flink] Should ignore readdata's backlog.

client-spark/common/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedPusher.java, common/src/main/java/org/apache/celeborn/common/protocol/PartitionLocation.java, common/src/main/scala/org/apache/celeborn/common/meta/PartitionLocationInfo.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Refactor PartitionLocationInfo, replace HashMap with ConcurrentHashMap and removed synchronized blocks. Also change the core data structure from ```(shuffleKey  -> (partitionId -> List[PartitionLocation]))``` to ```(shuffleKey -> (encodedUniqueId -> partitionLocation))```, where ```encodedUniqueId``` is ```partitionId.toLong << 32 | epoch```
For very large test case, say 300T terasort with 30w * 15w parallelism with sort pusher, the synchronization lock becomes the bottleneck. Tried with ReentrantReadWriteLock, task duration decreases from 7min to 5.6min. The PR further uses ConcurrentHashMap to avoid lock.
I tested the following with sort pusher
```
spark.sparkContext.parallelize(1 to 3000).repartition(2000).flatMap( _ => (1 to 15000000).iterator.map(num => …
```
=> [CELEBORN-301] Refactor PartitionLocationInfo to use ConcurrentHashMap

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala
1. Provide finished partitionIds(only for map partition) in reducer file group as partition may be committed early when split. So we need know whether the partition is ready for reader.
2.Cache file group in task Manager and use cached file group if partition which needed is ready.
Cache file group in Flink task manager will reduce useless/duplicate rpc call to jobManager.
No
TPCDS
=> [CELEBORN-341][Flink] cache file group for map partition in Flink plugin

worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/BufferStatusHub.java, worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/CongestionController.java, worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/TimeSlidingHub.java, worker/src/test/java/org/apache/celeborn/service/deploy/worker/congestcontrol/TestCongestionController.java
Change the avg calculation in Congestion control to use `currentTimeWindow` instead of `maxTimeTimeWindow`(sampleTimeWindowSeconds)
If a user just connect to a worker, we'll directly calculate the avg bytes by all bytes produced / sampleTimeWindowSeconds, but this is not right, we should use the current time window instead of the max time window
no
Existing tests.
=> [CELEBORN-342] Fix the wrong avg produce bytes in Congestion control

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java, common/src/main/java/org/apache/celeborn/common/network/server/memory/BufferRecycler.java, common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferDispatcher.java, common/src/main/java/org/apache/celeborn/common/network/server/memory/Recycler.java, common/src/main/java/org/apache/celeborn/common/network/server/memory/WrappedDataBuffer.java
1. refactor bufferStreamManager, move DataPartitionReader out of it and decouple DataPartitionReader/bufferStreamManager
2. fix memory leak(buffers) when map data partition allocates new buffer as the buffers already allocated.
3. fix memory leak(buffersRead) when reader encounter exception
4. fix memory leak when release the reader but sendData not really complete in Netty thread
1.We need recycle/release all the buffers the reader used, such as Buffers which used to read Data, BuffersRead which used to keep already read data, the readData buffer used in sendData which can be return to Buffers when netty thread complete.
2.bufferStreamManager/DataPartitionReader/MapDataPartition need take their own responsibility to manage the setup/close(for next layer)/release their own resources.
No …
=> [CELEBORN-347][Flink] fix memory leak and refactor BufferStreamManager

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
For revive failed:
1. If we just pass StatusCode.REVIVE_FAILED, then the next retry may miss the real cause of last retry. Then LifecycleManager may miss some blacklist information.
2. If we just pass revive's cause, WrappedCallback miss the revive failed when print error message
3. So here we combine two status code here, make it more clear and won't miss information.
=> [CELEBORN-336] Revive Failed should use keep the corresponding StatusCode

common/src/main/java/org/apache/celeborn/common/network/server/ChunkStreamManager.java, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/meta/DeviceInfo.scala, common/src/main/scala/org/apache/celeborn/common/meta/TimeWindow.scala, common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, common/src/test/java/org/apache/celeborn/common/network/server/ChunkStreamManagerSuiteJ.java, common/src/test/scala/org/apache/celeborn/common/meta/TimeWindowSuite.scala, common/src/test/scala/org/apache/celeborn/common/meta/WorkerInfoSuite.scala, common/src/test/scala/org/apache/celeborn/common/util/PbSerDeUtilsTest.scala, docs/configuration/master.md, docs/configuration/worker.md, master/src/main/java/org/apache/celeborn/service/deploy/master/SlotsAllocator.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/MetaUtil.java, master/src/main/proto/Resource.proto, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, master/src/test/java/org/apache/celeborn/service/deploy/master/SlotsAllocatorSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/DefaultMetaSystemSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/Flusher.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala, worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/FileWriterSuiteJ.java, worker/src/test/java/org/apache/celeborn/service/deploy/worker/storage/MapPartitionFileWriterSuiteJ.java, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/DeviceMonitorSuite.scala
Currently load-aware slots assignment strategy only considers flush time, but flush time might not correctly
reflects disk performance because we do not flush to disk. It's more reasonable to also consider fetch time,
which more precisely reflects disk perf.
This PR considers both flush and fetch time, and uses ```celeborn.slots.assign.loadAware.flushTimeWeight```
and ```celeborn.slots.assign.loadAware.fetchTimeWeight``` for flush/fetch time weight respectively.
As above.
Yes, adds two more configs: ```celeborn.slots.assign.loadAware.flushTimeWeight```
and ```celeborn.slots.assign.loadAware.fetchTimeWeight```.
UT and regression.
=> [CELEBORN-348] Support fetchTime in load-aware slots assignment strategy

.rat-excludes, common/src/main/java/org/apache/celeborn/common/network/util/LimitedInputStream.java
This PR aims to remove the standard Apache License header from the top of third-party source files.
This was discussed via general@incubator mailing list when releasing Celeborn
- https://lists.apache.org/thread/q8hchs4n2twhjl0qf3rn0ln0hyrvrnnp
and discussed in dev@spark
- https://lists.apache.org/thread/wfy9sykncw2znhzlvyd18bkyjr7l9x43
Here is the ASF legal policy.
- https://www.apache.org/legal/src-headers.html#3party
> Do not add the standard Apache License header to the top of third-party source files.
No. This is a source code distribution.
Manual review.
=> [CELEBORN-372] Remove the standard Apache License header from the top of third-party source files

.rat-excludes, common/src/main/java/org/apache/celeborn/common/network/util/LimitedInputStream.java
This PR aims to remove the standard Apache License header from the top of third-party source files.
This was discussed via general@incubator mailing list when releasing Celeborn
- https://lists.apache.org/thread/q8hchs4n2twhjl0qf3rn0ln0hyrvrnnp
and discussed in dev@spark
- https://lists.apache.org/thread/wfy9sykncw2znhzlvyd18bkyjr7l9x43
Here is the ASF legal policy.
- https://www.apache.org/legal/src-headers.html#3party
> Do not add the standard Apache License header to the top of third-party source files.
No. This is a source code distribution.
Manual review.
=> [CELEBORN-372][0.2] Remove the standard Apache License header from the top of third-party source files

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/MessageDecoderExt.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java, common/src/main/java/org/apache/celeborn/common/network/protocol/BufferStreamEnd.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java, common/src/main/java/org/apache/celeborn/common/network/protocol/TransportableError.java, common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java, common/src/main/java/org/apache/celeborn/common/util/ExceptionUtils.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
1. Pass the worker's exception to the client in the buffer stream reader.
2. Remove stream resources from worker if a client has an exception.
1. To improve debug process.
2. To release resources timely.
NO.
UT.
=> [CELEBORN-368][FLINK] Pass exceptions in buffer stream.

client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java
case1: test shuffle write about normal record with setting datacompress true or false 
case2: test shuffle write about large record 
case3:  test shuffle write about broadcast record
case4: test shuffle write to spill and flush
=> [CELEBORN-369] [FLINK] Add ut for RemoteShuffleResultPartition

build/mvn
Make `build/mvn` always respect `maven.version` defined in `pom.xml`.
The new version of maven may contains unexpected change which affects our build and test process. e.g. the Maven 3.9.0 has about ~10% performance downgrade [MNG-7677](https://issues.apache.org/jira/browse/MNG-7677) which slows the CI.
No.
Pass CI.
=> [CELEBORN-377][BUILD] `build/mvn` should always respect `maven.version` defined in `pom.xml`

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/PushDataHandler.scala
Call checkDiskFullAndSplit in the handlePushData method to avoid repeated definitions
Simplify the code
NO
passing CI
=> [CELEBORN-382] Call checkDiskFullAndSplit in the handlePushData method to avoid repeated definitions

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
Currently RssInputStreamImpl#locations references the array in ShuffleClientImpl#reduceFileGroupsMap, the array is in place randomized in RssInputStreamImpl's constructor.
```
this.locations = (PartitionLocation[]) Utils.randomizeInPlace(locations, RAND);
```
For non-skew-join cases, in which reducer tasks do not share locations, it's fine. But for skew-join cases, sub-reducers share the locations, then it might cause data lost. Say locations are [1,2,3], sub-reducer-1 randomizes to [1,3,2], and starts fetching data in this order, after fetching partition-1, sub-reducer-2 is created and randomizes the array to [3,1,2], after that, sub-reducer-1 will fetch [1,2], and finally lost partition 3.
As above.
NO.
UT and IT.
=> [CELEBORN-383][BUG] Fix read data might fetch the wrong partition location.

charts/celeborn/templates/master-statefulset.yaml
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
Error: INSTALLATION FAILED: YAML parse error on celeborn/templates/master-statefulset.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
```
fix …
=> [CELEBORN-384] Fix master-statefulset.yaml syntax error

conf/log4j2.xml.template
Add a rolling log4j configuration template.
Celeborn logs can be very large so we need to limit log's disk usage.
NO.
UT and manual cluster run.
=> [CELEBORN-385] Add rolling file in log4j configuration template

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java
OpenStream RPC is handled in netty worker thread group with blocking operation. This will hold a thread until the blocking operation is complete. This reduced the rpc process throughput. 
The time-consuming blocking operation like open file is moved to fetcher thread so that netty thread processes RPC only.
Before:
After:
NO.
UT and manual cluster run.
=> [CELEBORN-386][FLINK] Async open DataPartitionReader to release Netty thread earlier.

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java
To improve push performance in flink write.
There is no need to ensure that all push data is processed when send RPCs like REGION_START or REGION_FINISH.
NO.
=> [CELEBORN-387][FLINK] Remove unnecessary limitZeroInFlight from sendMessageInternal.

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java
1. Check transport client is null or not when sending BufferStreamEnd Rpc to worker.
2. Remove redundant code.
Ditto.
NO.
=> [CELEBORN-389][FLINK] Fix remove transportClient from readClientHandler caused NPE

charts/celeborn/templates/prometheus-podmonitor.yaml
Change the matchLabels of podMonitor from` app.kubernetes.io/name` to `app.kubernetes.io/role`
when deploy celeborn on k8s, master pods will be labeled as
This does not match` app.kubernetes.io/name: celeborn-master` in `prometheus-podmonitor.yaml`, in fact, this label is a combination of `name `and `role`, after changing it to `app.kubernetes.io/role` to match The metrics of the pod can be captured normally.
No
=> [CELEBORN-401] Modify prometheus-podmonitor.yaml to collect metrics correctly

.asf.yaml
Enable autolink to Jira.
Example: https://github.com/apache/flink-connector-kafka/commits/main
=> [CELEBORN-402] Enable autolink to Jira

common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java, common/src/main/java/org/apache/celeborn/common/network/server/memory/ReadBufferDispatcher.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala
To show metrics about buffer dispatcher requests queue length.
To show the busyness of workers in allocating read memory.
NO.
PR and cluster run.
=> [CELEBORN-403][FLINK] Add metrics about buffer dispatcher requests queue length.

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/FlinkTransportClientFactory.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java
Change flink shuffle plugin memory allocator to UnpooledBytebufAllocator because flink task manager  off-heap memory is quite limited.
Ditto.
NO.
=> [CELEBORN-397][FLINK] Flink plugin support UnpooledByteBufAllocator.

common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/MasterSource.scala
Currently, if the worker is just lost, the blacklist will remove it too, we need to add metrics to indicate the lost workers and later add it to the HTTP request.
=> [CELEBORN-405] Add metrics about lost workers

charts/celeborn/templates/prometheus-podmonitor.yaml
Fix two syntax error in prometheus-podmonitor.yaml to enable helm deployment.
Extra space causes syntax error when deploying,
No.
=> [CELEBORN-415] Fix syntax error in prometheus-podmonitor.yaml

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java
release buffer of readData when the handler already be removed
This will cause possible memory leaks.
No
Tpcds 1T with random kill workers, this will cause task fail.
=> [CELEBORN-417][FLINK] fix memory leak when handler already removed

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java
TransportFrameDecoderWithBufferSupplier should not pass converted Bytebuffer which converted from netty bytebuf. The bytebuf is needed and there is no need to wrap it again.
The wrapping operation breaks the retain and release pair which caused the memory leak.
Ditto.
NO.
=> [CELEBORN-419][FLINK] Fix memory leak when receive RPCs with body.

common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java, common/src/test/java/org/apache/celeborn/common/network/TestUtils.java, common/src/test/java/org/apache/celeborn/common/network/server/BufferStreamManagerSuiteJ.java
1.fix the condition when recycle stream.
2.add channel remote address to the log.
3.add ut for BufferStreamManager.
4.Don't send data when buffersRead is already released.
1.Currently will recycle stream with extra try as it need meet all stream finished.
2.Register stream with remote channel address would make debug easier.
No
UT & TPCDS 1T
=> [CELEBORN-391][FLINK][FOLLOW UP] fix clean stream twice & refine log & add ut

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java, client-flink/common/src/test/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplierSuiteJ.java
drop data buffers which belongs to the failed task from Netty bytebuf.
The task which shared the same channel with the previous failed task, would read the wrong buffer. Then the task may stuck.
No
UT & TPCDS 1T with random worker kill.
=> [CELEBORN-418][FLINK]Need drop unused bytes from netty when task was already failed

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/MessageDecoderExt.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/protocol/ReadData.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java, common/src/main/java/org/apache/celeborn/common/network/protocol/ReadData.java, common/src/main/java/org/apache/celeborn/common/network/server/DataPartitionReader.java
1. Remove offset from ReadData.
2. Remove backlog from ReadData
To reduce rpc size and improve performance.
NO.
UT.
=> [CELEBORN-422][FLINK] Remove unused fields in ReadData.

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java, client-flink/common/src/test/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplierSuiteJ.java
…n task was already failed
it's very rare for supplier.get() cause exception, but we need handle that
drop bytes when supplier.get encounter exception.
No
UT & TPCDS random kill
=> [CELEBORN-418][FLINK][FOLLOW UP]Need drop unused bytes

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/buffer/PartitionSortedBuffer.java
Remove unnecessary lock in PartitionSortedBuffer, see https://github.com/apache/flink/pull/18364
ditto
NO
UT
=> [CELEBORN-428][FLINK] Remove unnecessary lock in PartitionSortedBuffer

sbin/restart-worker.sh, sbin/start-worker.sh
`JAVA_VERSION` in start-work.sh get a blank return when no `java` command in system. Use ${JAVA} instead.
No
local
=> [CELEBORN-439] Fix java version check in start-worker

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
More and more companies use hdfs compatible distributed file system, such as juicefs, jindofs, ozone. We do not always use the 'hdfs' scheme in the production environment(juicefs uses jfs://xxx/yyy), so when using Celeborn as an RSS service, we have to hardcode to change Celeborn's current implementation logic of isHdfsPath(String path).
It's wonderful that we can use Celeborn normally just after adding the necessary jar package dependencies and core-site.xml configuration.
As above.
Allows wider configuration for distributed filesystem backend
=> [CELEBORN-442]Support hdfs compatible file system

charts/celeborn/templates/master-statefulset.yaml, charts/celeborn/templates/worker-statefulset.yaml
After https://github.com/apache/incubator-celeborn/pull/1269 should use the url with namespace to nsloolup
Cluster Test
=> [CELEBORN-447][Helm]Should nslookup dns with namespace before start master & worker

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/ShuffleTaskInfo.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/ShuffleTaskInfoSuitJ.java
In the removeExpiredShuffle method, the taskShuffleId should be removed instead of the shuffleId
In the removeExpiredShuffle method, the taskShuffleId should be removed instead of the shuffleId
NO
UT
=> [CELEBORN-453] [FLINK] In the removeExpiredShuffle method, the taskShuffleId should be removed instead of the shuffleId

charts/celeborn/Chart.yaml, charts/celeborn/templates/configmap.yaml, charts/celeborn/templates/master-service.yaml, charts/celeborn/templates/master-statefulset.yaml, charts/celeborn/templates/prometheus-podmonitor.yaml, charts/celeborn/templates/worker-service.yaml, charts/celeborn/templates/worker-statefulset.yaml
After https://github.com/apache/incubator-celeborn/pull/1156 PR, Celeborn Master\Worker Statefulset will contains  `app.kubernetes.io/version` label with image tag as value.
Due to [Kubenretes StatefulSet Update only allow 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds'](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates)
We may face Error when `helm upgrade` with image version changed.
No
Kubernetes Cluster Test
=> [CELEBORN-460][BUG][HELM]Helm Upgrade Release Fail due to change image version

common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, common/src/test/scala/org/apache/celeborn/common/util/UtilsSuite.scala
change the hdfs path regex
Path protocols are all started with xxx://, and is unnecessary to restrict the content after that. Actually, it makes an error when write shuffle files which like "xxx://abc/shuffle/hadoop/rss-worker/shuffle_data/spark-0de72e2ce2e24f6db69c2228dd12a514/0/0-0-0"
has been tested in testing environment within the company
=> [CELEBORN-449] Repair the hdfs path regex

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client/src/main/scala/org/apache/celeborn/client/CommitManager.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/ReleasePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/test/scala/org/apache/celeborn/client/WithShuffleClientSuite.scala, common/src/main/java/org/apache/celeborn/common/protocol/PartitionLocation.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala, common/src/test/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfoSuite.scala, docs/configuration/client.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
1.use destroy rpc to support release single partition resource for flink
2.support batch mode to reduce the number of total rpcs
Here would try to release resources for later using,  anything which not released successfully will be released when the shuffle /job is expired.
The unit of Flink resource management(or Map Partition mode) is partition，and if a partition is no longer needed, it can be immediately released, this will reduce the resources used by the Flink job, and the released partition resources can be reused later even in the same job. 
No
UT & manual TPCDS 1T
=> [CELEBORN-356] [FLINK] Support release single partition resource

common/src/main/java/org/apache/celeborn/common/network/client/TransportResponseHandler.java, common/src/main/java/org/apache/celeborn/common/network/util/TransportConf.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
The current `TransportResponseHandler` will create one thread for each channel, it's too much. In this pr, we make it use one public thread pool.
=> [CELEBORN-345] TransportResponseHandler create too much thread

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/FlinkTransportClientFactory.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client-flink/common/src/test/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplierSuiteJ.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/ShuffleTaskInfo.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala, client/src/test/java/org/apache/celeborn/client/DummyShuffleClient.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportResponseHandler.java, common/src/main/java/org/apache/celeborn/common/network/server/BufferStreamManager.java, common/src/main/java/org/apache/celeborn/common/network/server/ChunkStreamManager.java, common/src/main/java/org/apache/celeborn/common/util/JavaUtils.java, common/src/main/java/org/apache/celeborn/common/write/InFlightRequestTracker.java, common/src/main/java/org/apache/celeborn/common/write/PushState.java, common/src/main/java/org/apache/celeborn/common/write/SlowStartPushStrategy.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java, worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/CongestionController.java, worker/src/main/java/org/apache/celeborn/service/deploy/worker/storage/PartitionFilesSorter.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Respect the issue in uniffle community https://github.com/apache/incubator-uniffle/issues/519 
Below content is from that issue:
> According to the bug mentioned in https://bugs.openjdk.org/browse/JDK-8161372, we could check the key existence before invoking computeIfAbsent, especially for the critical path like ShuffleTaskManager#refreshAppId.
> The detailed fix could refer to https://juejin.cn/post/7094561581631012878
Because now celeborn also supports JDK8 and should also meet this issue.
No.
Existing UT.
=> [CELEBORN-474] Speed up ConcurrentHashMap#computeIfAbsent

client/src/main/java/org/apache/celeborn/client/ShuffleClient.java
This pr enable cache both for hdfs and viewfs filesystems.
For HDFS, hdfs and viewfs are two popular schemas.
No.
Existing UT.
=> [CELEBORN-473] Enable file system cache for viewfs in ShuffleClient as well

client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java
Support using Celeborn in the scenario of switching multiple SparkContexts in the same process.
In the current celeborn, after using a SparkContext, close it and create another in the same process, when using the new SparkContext to execute SQL. The following exception will occur.
```
[Executor task launch worker for task 0.0 in stage 8.0 (TID 8)] WARN  org.apache.celeborn.shaded.io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xca6cd07d]
java.util.concurrent.RejectedExecutionException: event executor terminated
at org.apache.celeborn.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932) ~[celeborn-client-spark-3-shaded_2.12-0.2.0-incubating.jar:?]
at …
```
=> [CELEBORN-472] Support using Celeborn in the scenario of switching multiple SparkContexts in the same process

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/CommitManager.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/ReleasePartitionManager.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/MapPartitionCommitHandler.scala, client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala, common/src/main/java/org/apache/celeborn/common/util/JavaUtils.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala, common/src/main/scala/org/apache/celeborn/common/meta/DeviceInfo.scala, common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, common/src/main/scala/org/apache/celeborn/common/meta/WorkerPartitionLocationInfo.scala, common/src/main/scala/org/apache/celeborn/common/metrics/source/AbstractSource.scala, common/src/main/scala/org/apache/celeborn/common/quota/QuotaManager.scala, common/src/main/scala/org/apache/celeborn/common/rpc/netty/Dispatcher.scala, common/src/main/scala/org/apache/celeborn/common/rpc/netty/NettyRpcEnv.scala, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, common/src/main/scala/org/apache/celeborn/common/util/Utils.scala, common/src/test/scala/org/apache/celeborn/common/meta/WorkerInfoSuite.scala, common/src/test/scala/org/apache/celeborn/common/util/PbSerDeUtilsTest.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterStateMachineSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/ObservedDevice.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/worker/storage/WorkerSuite.scala
Using inner static ConcurrentHashMap class and bypass for JDK9 above.
Address comments: https://github.com/apache/incubator-celeborn/pull/1383#discussion_r1148521718 
No
Existing UT.
=> [CELEBORN-474][FOLLOWUP] Using inner static ConcurrentHashMap class and only apply for JDK8

client/src/main/java/org/apache/celeborn/client/write/DataPushQueue.java, client/src/main/java/org/apache/celeborn/client/write/DataPusher.java, client/src/test/java/org/apache/celeborn/client/write/DataPushQueueSuitJ.java, common/src/main/java/org/apache/celeborn/common/write/InFlightRequestTracker.java, common/src/main/java/org/apache/celeborn/common/write/PushState.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
Currently DataPushQueue.takePushTasks will busy looping workingQueue, which causes CPU waste:
This PR returns all available tasks in takePushTasks instead of one, and sleep a while if non task is available.
No.
UT.
=> [CELEBORN-479][PERF] Refactor DataPushQueue.takePushTask to avoid busy wait

client/src/main/java/org/apache/celeborn/client/write/DataPushQueue.java, client/src/main/java/org/apache/celeborn/client/write/DataPusher.java
Should add null check for return tasks
=> [CELEBORN-479][FOLLOWUP] Return empty tasks instead of null to avoid NPE

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/utils/FlinkUtils.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleMasterTest.java
implements computeShuffleMemorySizeForTask for remote shuffle service
see [FLINK-15031](https://github.com/apache/flink/pull/16173)
No
UT
=> [CELEBORN-488] [FLINK] Calculate required shuffle memory before allocating slots if resources are specified

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
Improving logging of exceptions in `RssInputStream`. 
Currently, the error logs are not surfaced in the logs, making it difficult to realize why something is failing. This will log the exception in both the log message and also the exception itself. 
For example, it just looks like this:
```
/02/24 06:22:11 WARN task 2462.0 in stage 2.0 (TID 10872) RssInputStream: CreatePartitionReader failed 2/3 times, retry the same location 
```
This does not help with debugging issues that come up. 
No
Trivial change - Tested on our own cluster internally to ensure that the exception is being shown.
=> [CELEBORN-491] Improve exception logging in RssInputStream

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/FlinkTransportClientFactory.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java
use new TransportFrameDecoderWithBufferSupplier for creating client
Can not use the same TransportFrameDecoderWithBufferSupplier to retry create client
No
Manual kill worker test
=> [CELEBORN-489][FLINK]fix retry create client for open stream

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
Return shutting worker is empty also need to retain LifecycleManager's shutting workers
=> [CELEBORN-484][FOLLOWUP] Return shutting worker is empty also need to retain LifecycleManager's shutting workers

master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/StateMachine.java, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java
Add a notifyLogFailed method implementation in class StateMachine and a stepDown method in class HARaftServer and relative UT.
https://issues.apache.org/jira/projects/CELEBORN/issues/CELEBORN-495?filter=allopenissues
If the metadata directory of leader has some exceptions(Input/Output error in my case) , resulting in IOException of log entries, the leader may not be able to process the requests anymore, but it will not step down, as a result, the service will be unavailable. 
LifecycleManager's log:
```
ERROR RssHARetryClient: Send rpc with failure, has tried 0, max try 15!
com.aliyun.emr.rss.common.rpc.RpcTimeoutException: Futures timed out after [30 seconds]. This timeout is controlled by rss.haclient.rpc.askTimeout
at com.aliyun.emr.rss.common.rpc.RpcTimeout.com$aliyun$emr$rss$common$rp …
```
=> [CELEBORN-495] Leader should step down when its metadata directory has IO exception

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
Use context partitionId to apply new slots.
Flink task may retry register with new attemptId while lifecycle manager still offer slots for the attempt 0 tasks. 
No
Random kill workers
=> [CELEBORN-503][FLINK] fix attempt task may use wrong partitionId.

common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, common/src/test/scala/org/apache/celeborn/common/meta/WorkerInfoSuite.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
1. Remove setup worker endpoint
2. Remove Compare workerInfos
1. Should not set up endpoint while updateWorkerHeartbeatMeta while this will potentially block celeborn master startup progress. 
2. Remove Compare workerInfos, as Heartbeat will keep them consist.
No
UT
=> [CELEBORN-507] don't set up worker endpoint when update meta and remove compare meta with workers

master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Test
```
test("CELEBORN-512: Sort timestamp and show in date format") {
Map("11111" -> (System.currentTimeMillis()+10000L),
"222222" -> (System.currentTimeMillis() + 1000L),
"333333333" -> (System.currentTimeMillis() + 200000L)).toSeq
.sortBy(_._2).foreach { case (worker, time) =>
println(s"${worker.padTo(50, " ").mkString}${new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(time)}\n")
}
}
```
Result 
```
222222                                            2023-04-11T18:58:37.224+0800
11111                                             2023-04-11T18:58:46.224+0800
333333333                                         2023-04-11T19:01:56.224+0800
```
=> [CELEBORN-512][IMPROVEMENT] Sort timestamp and show in date format

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/ReadClientHandler.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/RssBufferStream.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java
Guarantee close the stream when rssbufferStream is already closed by Flink framework.
StreamId may not received when rssbufferStream is already closed by Flink framework, then the stream may not closed.
No
Manual with Tpcds
=> [CELEBORN-514][FLINK] RssBufferStream need guarantee close the stream.

common/src/main/java/org/apache/celeborn/common/network/server/memory/MemoryManager.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
Currently, if we call trim. in StorageManager, it still just add it to actionService, then return, the flag will directly set to false, then add a new trim action, here we should directly execute the onTrim in StorageManager.
=> [CELEBORN-511][IMPROVE] Move onTrim tag to StorageManager to avoid frequent trim action

worker/src/main/java/org/apache/celeborn/service/deploy/worker/congestcontrol/CongestionController.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/WorkerSource.scala
Add a new metric `WorkerConsumeSpeed` to monitor the whole flush speed from worker side.
Help us to track if the worker has bottleneck to flush data to storages.
no
Existing UT
=> [CELEBORN-522] Add worker consume speed metric

README.md, client-spark/spark-2/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java, client-spark/spark-3/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java, client/src/test/java/org/apache/celeborn/client/ShuffleClientBaseSuiteJ.java, client/src/test/java/org/apache/celeborn/client/ShuffleClientSuiteJ.java, docs/configuration/index.md, docs/deploy.md, tests/spark-it/src/test/scala/org/apache/celeborn/tests/client/ShuffleClientSuite.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/cluster/ReadWriteTestBase.scala
Replac `celeborn.push.buffer.size` with the correct parameter `celeborn.push.buffer.max.size`.
The documentation is incorrect.
Users who read the documentation.
exist UT
=> [CELEBORN-525] Fix wrong parameter celeborn.push.buffer.size

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteBufferStreamReader.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGate.java, common/src/main/java/org/apache/celeborn/common/network/server/MapDataPartitionReader.java, common/src/main/java/org/apache/celeborn/common/util/ExceptionUtils.java, common/src/main/scala/org/apache/celeborn/common/exception/FileCorruptedException.scala, common/src/main/scala/org/apache/celeborn/common/exception/PartitionUnRetryAbleException.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala
…rtitionUnRetryableException
Correct exception and unify unRetryableException
Currently Some Exception Type is not correct for client to identify what should do next. Such as throw RuntimeException when file corrupted in MapDataPartitionReader / OpenStream when FileNotFoundException. We can unify to PartitionUnRetryableException for reader can give up this partition and choose to regenerate the partition data, And this would benefit Flink to regenerate upstream data.
No
Tpcds & Random worker kill.
=> [CELEBORN-521] correct exception and unify unRetryableException

docs/monitoring.md
=> [CELEBORN-527][DOC] Fix incorrect monitor the arrangement of documents

common/src/main/java/org/apache/celeborn/common/write/InFlightRequestTracker.java
Currently exceed limitZeroInFlight didn't show the target ip, hard to found out unhealthy worker. This pr make it show the target IP
```
23/04/13 15:41:21 ERROR Executor: Exception in task 31906.0 in stage 8.0 (TID 30304)
com.aliyun.emr.rss.common.exception.RssIOException: wait timeout for task 14-31906-0
at com.aliyun.emr.rss.client.ShuffleClientImpl.limitZeroInFlight(ShuffleClientImpl.java:371)
at com.aliyun.emr.rss.client.ShuffleClientImpl.mapperEnd(ShuffleClientImpl.java:969)
at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.close(SortBasedShuffleWriter.java:269)
at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.write(SortBasedShuffleWriter.java:166)
at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
at …
```
=> [CELEBORN-528][REFACTOR] limitZeroInFlight should show inflight target

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleDescriptor.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/ShuffleResourceTracker.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/ShuffleResourceTrackerTest.java, client/src/main/java/org/apache/celeborn/client/listener/WorkerStatusListener.java, client/src/main/java/org/apache/celeborn/client/listener/WorkersStatus.java, client/src/main/scala/org/apache/celeborn/client/ApplicationHeartbeater.scala, client/src/main/scala/org/apache/celeborn/client/CommitManager.scala, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/WorkerStatusTracker.scala, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, common/src/main/scala/org/apache/celeborn/common/util/PbSerDeUtils.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
1、support stopTrackingAndReleasePartitions when celeborn workers were not available.
When encounter celeborn worker shutdown, data would be lost, Flink tasks will be retry but still try to read the lost data, but the job would not success. So we need to let the Flink framework known which data of the partitions can't be reading anymore, then Flink will schedule these partitions to regenerate
No
TPCDS with random worker kill
=> [CELEBORN-470][FLINK] support stopTrackingAndReleasePartitions 

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/TransportFrameDecoderWithBufferSupplier.java
To reduce message decoding overhead.
Before:
After:
NO.
=> [CELEBORN-535][FLINK] Reduce message decoder overhead.

master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterClusterInfo.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterNode.scala
I am looking to deploy Apache Celeborn on Kubernetes in host network mode, with the aim of facilitating communication between Spark and Celeborn through IP addresses. Currently, the master node retrieves the container hostname by default, rather than taking into consideration the address settings configured by the user.
here is my `celeborn-defaults.conf`
```
celeborn.master.endpoints=192.168.1.2,192.168.1.3,192.168.1.4
celeborn.ha.master.node.0.host=192.168.1.2
celeborn.ha.master.node.1.host=192.168.1.3
celeborn.ha.master.node.2.host=192.168.1.4
celeborn.ha.master.node.0.ratis.host=192.168.1.2
celeborn.ha.master.node.1.ratis.host=192.168.1.3
celeborn.ha.master.node.2.ratis.host=192.168.1.4
```
hostnames:
```
k8s2  192.168.1.2
k8s3  192.168.1.3
k8s6  192.168.1.4
```
spark conf
```scala …
```
=> [CELEBORN-534] Respect the user's configured master host settings

charts/celeborn/templates/master-statefulset.yaml, charts/celeborn/templates/worker-statefulset.yaml, sbin/celeborn-daemon.sh, sbin/start-master.sh, sbin/start-worker.sh
Use `exec` in bootstrap scripts to avoid fork subprocess
In K8s pod,  run  `ps -ef |grep celeborn`, the result as follows. when killing -15 pod, the sigterm pass to pid 1 by k8s and tini will pass sigterm to pid 22,  but pid 60(the real worker process) can't get the sigterm. so worker's ShutdowHookManager can't be called and master also can't know the worker have shutdown.
```
root          1      0  0 12:11 ?        00:00:00 /usr/bin/tini -- /bin/sh -c until nslookup celeborn-master-0.celeborn-master-svc.flink-celeborn.svc.cluster.local && nslookup celeborn-master-1.celeborn-master-svc.flink-celeborn.svc.cluster.local && nslookup celeborn-master-2.celeborn-master-svc.flink-celeborn.svc.cluster.local && true; do echo waiting for master; sleep 2; done && /opt/celeborn/sbin/start-worker.sh …
```
=> [CELEBORN-533] Bootstrap scripts should use exec to avoid fork subprocess

client-flink/flink-1.14/src/main/java/org/apache/celeborn/plugin/flink/ShuffleResourceTracker.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/ShuffleResourceTrackerTest.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/WorkerStatusTracker.scala, client/src/test/scala/org/apache/celeborn/client/WorkerStatusTrackerSuite.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala, common/src/test/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfoSuite.scala
1. use local shutdown workers as cache, refreshed by master when heartbeat
2. make unknown workers can expired, refreshed by master when heartbeat
3. refresh blacklist when new shuffle registered
4. donot remove worker when notify unknown workers for Flink.
5. Flink don't support revive, we just return exception for this.
when test graceful shutdown for Flink, there encounter some problems like blacklist list seems not reasonable, early remove worker from shuffleAllocationWorkers. 
1. work shutdown message would be reported to master/remove from master timely, so shutdown worker info in local can be regarded as cache. it can be refreshed by app heartbeat
2. if worker became unknown workers, this worker can never become alive, IMO it would be better added to checked list and if when …
=> [CELEBORN-537] Improve blacklist compute & minor fix for Flink

client/src/main/scala/org/apache/celeborn/client/commit/ReducePartitionCommitHandler.scala
Follow missed comment  https://github.com/apache/incubator-celeborn/pull/1444/files#r1173430611
=> [CELEBORN-541][FOLLOWUP] handleGetReducerFileGroup occupy too much RPC thread cause other RPC can't been handled

client/src/main/scala/org/apache/celeborn/client/WorkerStatusTracker.scala, client/src/test/scala/org/apache/celeborn/client/WorkerStatusTrackerSuite.scala
Record shuttingWorkers & improve remove
1. if workers returned by heartbeat contains being removed workers, It would better don't remove from blacklist.
2. blacklist need record every worker in heartbeat workers list. (Currently may lost record shuttingWorkers)
No
UT
=> [CELEBORN-537][FOLLOWUP] Fix blacklist potentially lost failure workers

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/network.md
HA_CLIENT_RPC_ASK_TIMEOUT should fallback to RPC_ASK_TIMEOUT
=> [CELEBORN-557] HA_CLIENT_RPC_ASK_TIMEOUT should fallback to RPC_ASK_TIMEOUT

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, client/src/main/scala/org/apache/celeborn/client/WorkerStatusTracker.scala, client/src/main/scala/org/apache/celeborn/client/commit/CommitHandler.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala
1.Filter out empty workers when reserver/commit.
1.Master will potentially offer extra empty slots for LifecycleManager, And these can filter out to avoid useless reserve/commit
No
UT
=> [CELEBORN-554][Tuning]  Improve For LM to avoid reserve/commit empty worker resources

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/proto/TransportMessages.proto, common/src/main/scala/org/apache/celeborn/common/protocol/message/ControlMessages.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Controller.scala
Currently `Destroy` and `DestroyResponse` is a little misleading, this pr rename it to make it more clear
=> [CELEBORN-562][REFACTOR] Rename Destroy and DestroyResponse to make it more clear

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala
Spark rerun a success task (may be caused by TaskSuccess rpc delay)
But Celeborn side have handledStageEnd and remove shuffle key from `shuffleAllocatedWorker`
then the rerun task throw NPE
```
23/04/25 11:08:44 ERROR ShuffleClientImpl: Exception raised while registering shuffle 19 with 201 mapper and 200 partitions.
com.aliyun.emr.rss.common.exception.RssException: Exception thrown in awaitResult: 
at com.aliyun.emr.rss.common.util.ThreadUtils$.awaitResult(ThreadUtils.scala:224)
at com.aliyun.emr.rss.common.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:74)
at com.aliyun.emr.rss.common.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:90)
at com.aliyun.emr.rss.client.ShuffleClientImpl.registerShuffle(ShuffleClientImpl.java:329)
at com.aliyun.emr.rss.client.ShuffleClientImpl.lambda$getPartition …
```
=> [CELEBORN-560][BUG] Rerun task in spark later then RSS stageEnd cause NPE then job failed

sbin/stop-all.sh
Modify comments in `stop-all.sh`, the right comments should be `stop masters` and `stop workers`.  
Ditto.
No.
No need to add any UT.
=> [CELEBORN-564] stop-all.sh has wrong comment

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/scala/org/apache/celeborn/common/meta/ShufflePartitionLocationInfo.scala
The original design  for handling rerun & speculative task after handleStageEnd is
1. shuffle StageEnd handled and remove PartitionLocations in shuffleAllocatedWorkers
2. rerun & speculative task running and call registerShuffle
3. registergedShuffle contains shuffle id and shuffleAllocatedWorkers also contains shuffle id, return an empty location map
4. ShuffleClient side get partitionId corresponding location return null (since we change the DataPushQueue so we also need merge https://github.com/apache/incubator-celeborn/pull/1404)
5. ShuffleClient side revive for a new PartitionLocation
6. New partitionLocation will add to shuffleAllocatedWorkers
7. Stage finished an call unregister shuffle, then partitionResourceExists return true and re-release allocated slots.
=> [CELEBORN-560][FOLLOWUP] Follow the original design for handling rerun & speculative task after handleStageEnd  

client/src/main/java/org/apache/celeborn/client/write/DataPushQueue.java
According to CELEBORN-560, call rerun task and speculative task after LifecycleManager
handle StageEnd will return an empty PartitionLocation map, here loc can be null
```
23/04/03 11:14:24 INFO CodeGenerator: Code generated in 1017.663846 ms
23/04/03 11:14:24 INFO SortBasedShuffleWriter: Pushdata in close, memory used 100663296
23/04/03 11:14:24 INFO Executor: Executor is trying to kill task 24.0 in stage 2.0 (TID 248), reason: another attempt succeeded
23/04/03 11:14:24 INFO DataPusher: Thread interrupted while joining pushThread
23/04/03 11:14:25 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[DataPusher-248,5,main]
at com.aliyun.emr.rss.client.write.DataPushQueue.takePushTasks(DataPushQueue.java:100)
at …
```
=> [CELEBORN-479][FOLLOWUP]   Add push task should check if loc is null

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
Fetch max retry times should double when enable replicates
=> [CELEBORN-565] FETCH_MAX_RETRIES should double when enable replicates

README.md
The default value of the HTTP port is  9098. The example configuration will cause malfunctioning.
Ditto.
NO.
No need for test.
=> [CELEBORN-566] Refine docs to eliminate misleading configs.

client/src/main/java/org/apache/celeborn/client/read/RssInputStream.java
```
23/04/25 17:25:41 WARN RssInputStream: CreatePartitionReader failed 1/3 times, change to peer
java.io.IOException: Failed to connect to /10.169.33.213:9093
at com.aliyun.emr.rss.common.network.client.TransportClientFactory.internalCreateClient(TransportClientFactory.java:234)
at com.aliyun.emr.rss.common.network.client.TransportClientFactory.createClient(TransportClientFactory.java:180)
at com.aliyun.emr.rss.common.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
at com.aliyun.emr.rss.client.read.PartitionReader.openStream(PartitionReader.java:99)
at com.aliyun.emr.rss.client.read.PartitionReader.<init>(PartitionReader.java:94)
at com.aliyun.emr.rss.client.read.RssInputStream$RssInputStreamImpl.createReader(RssInputStream.java:250)
at …
```
=> [CELEBORN-559][IMPROVEMENT] createReader should also wait for retry when change to same peer

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/RssShuffleManager.java, client/src/main/java/org/apache/celeborn/client/ShuffleClient.java
Two `ShuffleClient.get()` implement is same logic, remove unnecessary one.
=> [CELEBORN-551] Remove unnecessary ShuffleClient.get()

client/src/main/scala/org/apache/celeborn/client/ChangePartitionManager.scala
Worker
```
22/10/25 15:09:21,828 DEBUG [dispatcher-event-loop-14] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:09:21,828 INFO [dispatcher-event-loop-14] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]
22/10/25 15:25:27,728 DEBUG [dispatcher-event-loop-43] Worker: Received CommitFiles request, application_1665646136650_2510409_1-33, master files 64-1,833-0,1345-1,164-1,584-2,1161-1,1129-2,1131-0,237-0,818-1,819-1,1429-0,535-0,733-1,478-1; slave files 832-0,672-1,130-1,134-1,1130-0,1034-1,236-0,268-1,883-1,1428-0,564-1, …
```
=> [CELEBORN-563] Remove unnecessary code about handle Revive rpc after handle StageEnd

master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAHelper.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala
increase timeout deadline when leader changed to avoid app/worker status unexpected changes.
Consider the situation in ha mode，if master election period exceeds the workerHeartbeatTimeout or appHeartbeatTimeout, all workers/apps may timeout immediately when new leader elected。And This will also cause every shuffle of the apps timeout, every register/every change partition fail and all data would be lost in worker. For Flink same system, It's  also bad as the resource of Flink dataset would be timeout while even Flink app retry to connect the master. (Flink support long time retry strategy for one job, then this job would fail because of shuffle expired in Celeborn Cluster)
No
Would test in k8s environment.
=> [CELEBORN-567] Timeout workers/app need consider long leader election period

common/src/main/scala/org/apache/celeborn/common/meta/WorkerPartitionLocationInfo.scala, common/src/test/scala/org/apache/celeborn/common/meta/WorkerPartitionLocationInfoSuite.scala
New WorkerPartiionLocationInfo's change forgot to remove empty shuffle key from PartitionInfo, cause `isEmpty` method always return false.
#1278 change this
=> [CELEBORN-575] PartitionLocationInfo change cause quick upgrade impacted

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/identity/HadoopBasedIdentityProvider.scala, common/src/main/scala/org/apache/celeborn/common/identity/IdentityProvider.scala, docs/configuration/quota.md
1. Add DefaultIdentityProvider to eliminate Hadoop dependency.
2. Add manually settable IdentityProvider to let the users decide their own tenant and username.
3. Rename the previous DefaultIdentityProvider to HadoopBasedIdentityProvider.
Ditto.
Yes, config's default value has been changed.
UT.
=> [CELEBORN-576] Add static identity provider and manually settable identity provider for non-hadoop environment.

client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
Currently, reserve slot uses same timeout with default RPC_ASK_TIMEOUT, 
we know that the register shuffle's max time out should be the min value of (RPC_ASK_TIMEOUT, REGISTER_SHUFFLE_RPC_ASK_TIMEOUT), if one worker is being reserving slots stuck, the the register shuffle process time must greater than the min value of (RPC_ASK_TIMEOUT, REGISTER_SHUFFLE_RPC_ASK_TIMEOUT).
The ShuffleClient side will throw register shuffle timeout exception,  so we should support customize the reserve slots rpc timeout, if worker stuck, we can give this process a chance to retry according to the timeout configuration
=> [CELEBORN-556][BUG] ReserveSlot should not use default RPC time out since register shuffle max timeout is network timeout

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/network/MessageDecoderExt.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java, common/src/main/java/org/apache/celeborn/common/network/TransportContext.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Heartbeat.java, common/src/main/java/org/apache/celeborn/common/network/protocol/Message.java, common/src/main/java/org/apache/celeborn/common/network/server/TransportChannelHandler.java, common/src/main/java/org/apache/celeborn/common/network/util/TransportConf.java, common/src/main/java/org/apache/celeborn/common/network/util/TransportFrameDecoder.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/test/java/org/apache/celeborn/common/network/TransportClientFactorySuiteJ.java, docs/configuration/client.md, docs/configuration/worker.md, tests/flink-it/src/test/scala/org/apache/celeborn/tests/flink/HeartbeatTest.scala, tests/spark-it/src/test/scala/org/apache/celeborn/tests/spark/HeartbeatTest.scala, worker/src/main/java/org/apache/celeborn/service/deploy/worker/memory/MemoryManager.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/test/java/org/apache/celeborn/service/deploy/worker/network/RequestTimeoutIntegrationSuiteJ.java, worker/src/test/scala/org/apache/celeborn/service/deploy/HeartbeatFeature.scala, worker/src/test/scala/org/apache/celeborn/service/deploy/MiniClusterFeature.scala
1. worker's channel inactive occurs: client close/ kill -9 then os close tcp ;
if os is died or network is not usable, then worker's channel wait about 2hours (depending os's tcp keeping alive duration) 
So this pr adds heartbeat to worker, worker will be channel inactive afer readidle timeout (it's more quickly to close connection when os is died or network is not usable)
2. if client is busy and no free time to shuffle read, we often see client will close connection after idletimeout(4min by default) and reconnect to worker . this pr add hearts from work to client to avoid closing connectiton and reconnecting
3. by default ,flink client set heartbeat enabled and idlestatechannel will be changed from allidle to readidle.
=> [CELEBORN-552] Add HeartBeat between the client and worker to keep alive

common/src/main/scala/org/apache/celeborn/common/metrics/source/SystemMiscSource.scala, docs/monitoring.md, master/src/main/scala/org/apache/celeborn/service/deploy/master/Master.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Add SystemMiscSource to indicate system running status
=> [CELEBORN-586] Add SystemMiscSource to indicate system running status

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleInputGateDelegation.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleMaster.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleOutputGate.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/RemoteShuffleResource.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/utils/FlinkUtils.java, client-flink/common/src/test/java/org/apache/celeborn/plugin/flink/FlinkShuffleClientImplSuiteJ.java, client-flink/flink-1.14/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java, client-flink/flink-1.15/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java, client-flink/flink-1.17/src/test/java/org/apache/celeborn/plugin/flink/RemoteShuffleResultPartitionSuiteJ.java, common/src/main/scala/org/apache/celeborn/common/exception/DriverChangedException.scala, tests/flink-it/src/test/scala/org/apache/celeborn/tests/flink/HeartbeatTest.scala
1. Introduce timestamp version for ShuffleMaster(LifecycleManager).
2. Add timestamp with first jobId, to expire exist shuffles when jobManager failover.
3. Refresh client when lifecycleManager changed.
1. In Session Mode, When Flink JobManager failover, the host-port of LifecycleManager would change to new host-port, so we need refresh the client instance in TaskManager for new launching tasks.
3.For job recovering when Flink JobManager failover, Flink will reschedule the whole job from the start(but still keep the job id as the same),  so shuffle framework need guarantee all previous shuffles belong this jobId need to be expired.
No
UT & jobManager HA in ecs & k8s
=> [CELEBORN-581][Flink] Support JobManager failover.

common/src/main/java/org/apache/celeborn/common/network/TransportContext.java, common/src/main/java/org/apache/celeborn/common/network/server/TransportServer.java, common/src/test/java/org/apache/celeborn/common/network/TransportClientFactorySuiteJ.java, docs/monitoring.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala, worker/src/test/java/org/apache/celeborn/service/deploy/worker/network/RequestTimeoutIntegrationSuiteJ.java
Worker side should expose Netty allocator metrics
=> [CELEBORN-584] Worker side should expose push/replicate/fetch Netty allocator metrics

worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
When worker graceful shutdown is enabled and defined recoverPath `celeborn.worker.graceful.shutdown.recoverPath` does not exists, init leveldb will fail in `NativeDB.open`(caused by: IO error: /tmp/recover/recovery.ldb/LOCK: No such file or directory),  and then recover function is not actually enabled.
We can create the recoverPath before init leveldb to avoid this error.
Improve user experience
No
Use the company test env
=> [CELEBORN-585] Create if not exists worker recoverPath when graceful shutdown is enabled

common/src/main/java/org/apache/celeborn/common/network/server/ChunkStreamManager.java, common/src/test/java/org/apache/celeborn/common/network/server/ChunkStreamManagerSuiteJ.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/FetchHandler.scala, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Cherry-picked from main.
Reuse the stream when channel inactive while fetching trunk.
Stream will be removed when channel inactive while fetching trunk, so even if the client is reconnected, fetch trunk would not success and then client will retry other peer reader for same partition location. We can reuse the stream when client is reconnected to avoid this.
No
random kill workers & worker high-pressure test
=> [CELEBORN-267] reuse stream when client channel reconnected (#1200)

build/mvn
Update `build/mvn` to download maven from `www.apache.org/dyn/closer.lua` instead of `archive.apache.org`
To speed up maven download and overcome temporary outage of `archive.apache.org`
No, dev only.
Pass CI
=> [CELEBORN-589][INFRA] Using Apache CDN to download maven

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/worker.md, docs/migration.md, toolkit/reg.sh
Remove hadoop prefix of WORKER_WORKING_DIR
=> [CELEBORN-590] Remove hadoop prefix of WORKER_WORKING_DIR

README.md, common/src/main/java/org/apache/celeborn/common/network/client/TransportClientFactory.java, common/src/main/java/org/apache/celeborn/common/network/server/TransportServer.java, common/src/main/java/org/apache/celeborn/common/network/util/NettyMemoryMetrics.java, common/src/main/java/org/apache/celeborn/common/network/util/NettyUtils.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md, docs/configuration/worker.md, worker/src/main/java/org/apache/celeborn/service/deploy/worker/memory/MemoryManager.java, worker/src/main/java/org/apache/celeborn/service/deploy/worker/memory/ReadBufferDispatcher.java
Merging pooled memory allocators to improve memory usage efficiency. Due to Netty's memory allocator, it will cause some fragments and cannot be used.
Workload: 8x Flink TPC-DS 1TB 
Hardware: 8x 32vCPU 128GRam.
Celeborn Worker: 1G off-heap.
Before this patch, as you can see that workers have multiple memory allocators. Memory allocators will consume more memory than we thought it should be. And the workload will failed to run through q4.sql.
After this Path, running the same workload will not cause PausePushData state and q4.sql is passed.
NO.
UT and cluster.
=> [CELEBORN-583] Merge pooled memory allocators.

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala
Change default from 120s to 30s, then if no leader in ratis system would be notified and wait another 120s(default heartbeat timeout).
With current config, if two master(not leader) have a similar shut-down time,  the current leader will be notified to change it's role only when ratis reach the no-leader timeout, this would cause lost workers/apps. As when followers come back and current leader also may be elected as the leader, then the leader would not wait another app/worker heartbeat timeout. Although this situation rarely occurs, Celeborn should still try to avoid it.
No
UT & Manual Test
=> [CELEBORN-591] RatisSystem need decrease no leader timeout configuration.

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, conf/log4j2.xml.template, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java
1. To add new configs introduced by the recent Ratis upgrade.
2. Remove noisy logs.
Ratis 2.5.1 introduced new features but the implementation is strange. If a node becomes a follower, this node will continue to log raft config "first-election.timeout.min" and "first-election.timeout.max" repeatedly until this node becomes a leader.
NO.
Cluster and UT.
=> [CELEBORN-594] Eliminate Ratis noisy logs.

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
Remove wrong space of config SHUFFLE_CLIENT_PUSH_BLACK
=> [CELEBORN-487] Remove wrong space of config SHUFFLE_CLIENT_PUSH_BLACK

common/src/main/scala/org/apache/celeborn/common/meta/WorkerInfo.scala, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/AbstractMetaManager.java, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/Worker.scala
Two main points:
1. Avoid using estimatedPartitionSize in the worker side, unnecessary
2. Make the method simple
=> [CELEBORN-596] Worker don't need to update disk max slots

common/src/main/scala/org/apache/celeborn/common/meta/DeviceInfo.scala, common/src/test/scala/org/apache/celeborn/common/meta/DeviceInfoSuite.scala
Currently `DeviceInfo#getMountPoint` match the longest string to determine which mount point a directory attached. May get wrong judges in some scenarios.
Assume mount points are /, /data,and dir is /data1. /data1 will attach to /data(should be /), and actually create shuffle dir in /.  
Improve usage, and avoid filling the wrong mount point
No
UT and cluster test
=> [CELEBORN-599] Consolidate calculation of mount point

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/AbstractRemoteShuffleInputGateFactory.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/AbstractRemoteShuffleResultPartitionFactory.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/config/PluginConf.java, client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/utils/FlinkUtils.java
Flink does support floating buffers for input and output channels. Celeborn will consume quite noticeable memory when initializing channels. So I added new configs to make Celeborn plugin works the same as Flink task manager to make sure that Flink applications behave the same.
Ditto.
NO.
UT.
=> [CELEBORN-597][FLINK] Support flink floating buffer for input gate and output gate.

.github/workflows/maven.yml, README.md, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java, client-spark/spark-3/src/test/java/org/apache/spark/shuffle/celeborn/RssShuffleWriterSuiteJ.java, pom.xml, tests/spark-it/pom.xml
Cherry-picked from main.
- Add new profile `spark-3.4`
- Change code to adapt SPARK-39391
- Test Celeborn against Spark 3.4.0
Support the latest Spark 3.4
Yes, brings Spark 3.4 support officially.
Pass GA
=> [CELEBORN-604][SPARK] Support Spark 3.4

build/make-distribution.sh
Add option `--no-fflags` to macOS tar command in `build/make-distribution.sh`
Create binary tarball on macOS then unarchive on Linux, may print warnings
```
➜  ~ tar -xzf apache-celebron-0.3.0-SNAPSHOT-bin.tgz
tar: Ignoring unknown extended header keyword `SCHILY.fflags'
```
`--no-mac-metadata` is for excluding AppleDouble files; `--no-xattrs` is for excluding xattrs like `LIBARCHIVE.xattr.com.apple.FinderInfo`; `--no-fflags` is for excluding fflags like `SCHILY.fflags`
Reference from macOS `man tar`
```
--no-fflags
(c, r, u, x modes only) Do not archive or extract file attributes or file flags.  This is the reverse of --fflags and the default behavior if tar is run as non-root in x mode.
--no-mac-metadata
(x mode only) Mac OS X specific.  Do not archive or extract ACLs and extended file …
```
=> [CELEBORN-608][BUILD] Exclude macOS fflags in make-distribution.sh

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigBuilder.scala, common/src/main/scala/org/apache/celeborn/common/internal/config/ConfigEntry.scala, common/src/test/scala/org/apache/celeborn/common/CelebornConfSuite.scala
Consolidate configsWithAlternatives with `ConfigBuilder.withAlternative`
Current code if we use  below two function
```
def get(key: String): String = {
getOption(key).getOrElse(throw new NoSuchElementException(key))
}
def get(key: String, defaultValue: String): String = {
getOption(key).getOrElse(defaultValue)
}
```
They are not consist.
=> [CELEBORN-601] Consolidate configsWithAlternatives with `ConfigBuilder.withAlternative`

assets/spark-patch/RSS_RDA_spark2.patch, assets/spark-patch/RSS_RDA_spark3.patch
According to 
https://github.com/oap-project/gluten/blob/e012b50e3dc2f082c82b324f0be2b1d6f277511b/gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java#L24-L25
The celeborn shuffle manager of gluten is not `org.apache.spark.shuffle.celeborn.RssShuffleManager`, then it breaks the result of isRssEnabled.
This pr relax it to `contains("celeborn")` to compatible with gluten celeborn shuffle manager.
Make dra work with gluten + celeborn
yes
manually test
=> [CELEBORN-622] Relax isRssEnabled condition to compatible with gluten celeborn shuffle manager

charts/celeborn/templates/configmap.yaml, charts/celeborn/templates/master-statefulset.yaml, charts/celeborn/templates/worker-statefulset.yaml, charts/celeborn/values.yaml
Add `initContainer` to `chown` volumes dir for master and worker.
Previously, when users deployed celeborn on kubernetes for the first time (with the default HostPath mount), they encountered permission issues that could not be written.
Due to k8s create dir with start kubelet user and 0755, but Celeborn run as celeborn user(uid: 10006)
>DirectoryOrCreate | If nothing exists at the given path, an empty directory will be created there as needed with permission set to 0755, having the same group and ownership with Kubelet.
See more in [HostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)
No
Ack tested.
=> [CELEBORN-612][HELM] Tackle hostPath directory permission

client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java, common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/client.md
Celeborn expected UnsafeRow's memory layout has never changed but there might be changed by optimization. So we need a way to disable fast write.
Ditto.
NO.
UT and cluster.
=> [CELEBORN-625] Add a config to enable/disable UnsafeRow fast write.

common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala, docs/configuration/worker.md, worker/src/main/scala/org/apache/celeborn/service/deploy/worker/storage/StorageManager.scala
The current code has two problems:
1.  If the application running too long and it running longer than `workerApplicationDataKeepAliveTime`, it will cause job failed and it's not what we want
2. Now we support the graceful shutdown and we can recover file info from levelDB then we can still fetch data after restarting. If we don't enable the graceful shutdown. Even if we reserve the application data, we can't read it's data too
In this pr, we simplify the cleanup logic. We just remove all app directories that not have file info(If not, means we can't read the data)
=> [CELEBORN-624] StorageManager should only remove expired app dirs

client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
Push merged data task timeout and mapended should also remove push states, or it will cause push task timeout 
Worker side log shows Map eneded.
```
23/05/30 03:24:07,034 INFO [replicate-server-9-12] Worker: Receive push data from speculative task(shuffle application_1684207607609_2728653_1-2, map 5744, attempt 3), but this mapper has already been ended.
23/05/30 03:27:37,388 INFO [replicate-server-9-12] Worker: Receive push data from speculative task(shuffle application_1684207607609_2728653_1-2, map 5744, attempt 4), but this mapper has already been ended.
```
Client side timeout
```
23/05/30 03:33:27 ERROR Executor: Exception in task 5744.4 in stage 3.0 (TID 10124)
com.aliyun.emr.rss.common.exception.RssIOException: wait timeout for task 2-5744-4
at …
```
=> [CELEBORN-621][BUG] Push merged data task timeout and mapended should also remove push states

pom.xml
now our project  doesn't use netty's ssl feature, so it can be removed from netty dependencies.
=> [CELEBORN-635] Exclude unused ssl dependency(netty-handler-ssl-ocsp) from netty dependency

client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/HashBasedShuffleWriter.java, client-spark/spark-3/src/main/java/org/apache/spark/shuffle/celeborn/SparkUtils.java, client-spark/spark-3/src/main/scala/org/apache/spark/shuffle/celeborn/CelebornShuffleReader.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornBatchBuilder.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnAccessor.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnBuilder.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnStats.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnType.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnarBatchBuilder.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnarBatchCodeGenBuild.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornColumnarBatchSerializer.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornCompressibleColumnBuilder.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornCompressionScheme.scala, client-spark/spark-3/src/main/scala/org/apache/spark/sql/execution/columnar/CelebornCompressionSchemes.scala
Support fallback to non-columnar shuffle for schema that cannot be obtained from shuffle dependency. Cherry pick #2101  to branch-0.3.
When columnar shuffle is enabled, it was found that the shuffle class operator of Spark RDD is not supported. It's recommended to support fallback to non-columnar shuffle for schema that cannot be obtained from shuffle dependency.
No.
No.
=> [CELEBORN-1123][FOLLOWUP] Support fallback to non-columnar shuffle for schema that cannot be obtained from shuffle dependency

common/src/main/java/org/apache/celeborn/common/client/MasterClient.java, common/src/main/java/org/apache/celeborn/common/client/MasterNotLeaderException.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HAHelper.java, master/src/main/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/HARaftServer.java, master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterClusterInfo.scala, master/src/main/scala/org/apache/celeborn/service/deploy/master/clustermeta/ha/MasterNode.scala, master/src/test/java/org/apache/celeborn/service/deploy/master/clustermeta/ha/RatisMasterStatusSystemSuiteJ.java
`MasterNotLeaderException` should include not just the rpc address for applications, but also the internal rpc address (based on internal port) for workers to connect to the leader.
I am leveraging `adminAddress` in order to persist this information in ratis state - and have client reconnect to the right rpc endpoint based on whether it is application or worker.
Without this fix, workers connect to rpc endpoint which applications use (and not at internal port) when `MasterNotLeaderException` is thrown - resulting in failures.
No, bug fix.
Tested with a local deployment - 3 masters + 2 workers, with authentication and internal port enabled.
Without the fix, one or more worker fails to come up and fails with exception.
Additionally, existing tests pass and test updated.
=> [CELEBORN-1371] Update ratis with internal port endpoint address as well

client-flink/common/src/main/java/org/apache/celeborn/plugin/flink/readclient/FlinkShuffleClientImpl.java, client/src/main/java/org/apache/celeborn/client/ShuffleClientImpl.java
backport https://github.com/apache/celeborn/pull/2531 to `branch-0.4`
`ShuffleClientImpl` invokes `loadFileGroupInternal` only once when using the reduce partition mode.
`ShuffleClientImpl` may call `loadFileGroupInternal` multiple times when using reduce partition mode, which is not as expected. This bug was introduced in #2219.
No.
GA.
=> [CELEBORN-1432][0.4] ShuffleClientImpl should invoke loadFileGroupInternal only once when using the reduce partition mode

common/src/main/scala/org/apache/celeborn/common/metrics/source/AbstractSource.scala
backport https://github.com/apache/celeborn/pull/2548 to branch-0.4
Fix the thread safety bug in getMetrics of AbstractSource by changing the lock scope
When two threads access the getMetrics method in AbstractSource at the same time, one of the threads may get fewer metrics than the actual value, because the actual execution order may be like this: Thread A gets the lock, adds the metrics of the worker source to the innerMetrics queue and releases the lock, Thread B gets the lock, adds the metrics of the worker source to the innerMetrics queue and releases the lock, Thread A gets the lock, adds the metrics of other sources to the innerMetrics queue, assembles the values of innerMetrics, clears innerMetrics and releases the lock, Thread B gets the lock, adds the metrics of other sources …
=> [CELEBORN-1453][0.4] Fix the thread safety bug in getMetrics
